// Code generated by MockGen. DO NOT EDIT.
// Source: brokertop.go
//
// Generated by this command:
//
//	mockgen -source=brokertop.go -destination=../mocks/mock_brokertop_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm-server/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBrokerTopRepository is a mock of BrokerTopRepository interface.
type MockBrokerTopRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerTopRepositoryMockRecorder
	isgomock struct{}
}

// MockBrokerTopRepositoryMockRecorder is the mock recorder for MockBrokerTopRepository.
type MockBrokerTopRepositoryMockRecorder struct {
	mock *MockBrokerTopRepository
}

// NewMockBrokerTopRepository creates a new mock instance.
func NewMockBrokerTopRepository(ctrl *gomock.Controller) *MockBrokerTopRepository {
	mock := &MockBrokerTopRepository{ctrl: ctrl}
	mock.recorder = &MockBrokerTopRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerTopRepository) EXPECT() *MockBrokerTopRepositoryMockRecorder {
	return m.recorder
}

// GetBrokerTop mocks base method.
func (m *MockBrokerTopRepository) GetBrokerTop(ctx context.Context, sort, order, period, marketType string, eodOnly bool) (*domain.BrokerTopData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrokerTop", ctx, sort, order, period, marketType, eodOnly)
	ret0, _ := ret[0].(*domain.BrokerTopData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBrokerTop indicates an expected call of GetBrokerTop.
func (mr *MockBrokerTopRepositoryMockRecorder) GetBrokerTop(ctx, sort, order, period, marketType, eodOnly any) *MockBrokerTopRepositoryGetBrokerTopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrokerTop", reflect.TypeOf((*MockBrokerTopRepository)(nil).GetBrokerTop), ctx, sort, order, period, marketType, eodOnly)
	return &MockBrokerTopRepositoryGetBrokerTopCall{Call: call}
}

// MockBrokerTopRepositoryGetBrokerTopCall wrap *gomock.Call
type MockBrokerTopRepositoryGetBrokerTopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBrokerTopRepositoryGetBrokerTopCall) Return(arg0 *domain.BrokerTopData, arg1 error) *MockBrokerTopRepositoryGetBrokerTopCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBrokerTopRepositoryGetBrokerTopCall) Do(f func(context.Context, string, string, string, string, bool) (*domain.BrokerTopData, error)) *MockBrokerTopRepositoryGetBrokerTopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBrokerTopRepositoryGetBrokerTopCall) DoAndReturn(f func(context.Context, string, string, string, string, bool) (*domain.BrokerTopData, error)) *MockBrokerTopRepositoryGetBrokerTopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
