// Code generated by MockGen. DO NOT EDIT.
// Source: chartbit.go
//
// Generated by this command:
//
//	mockgen -source=chartbit.go -destination=../mocks/mock_chartbit_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm-server/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockChartbitUsecase is a mock of ChartbitUsecase interface.
type MockChartbitUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockChartbitUsecaseMockRecorder
	isgomock struct{}
}

// MockChartbitUsecaseMockRecorder is the mock recorder for MockChartbitUsecase.
type MockChartbitUsecaseMockRecorder struct {
	mock *MockChartbitUsecase
}

// NewMockChartbitUsecase creates a new mock instance.
func NewMockChartbitUsecase(ctrl *gomock.Controller) *MockChartbitUsecase {
	mock := &MockChartbitUsecase{ctrl: ctrl}
	mock.recorder = &MockChartbitUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChartbitUsecase) EXPECT() *MockChartbitUsecaseMockRecorder {
	return m.recorder
}

// GetChartPrice mocks base method.
func (m *MockChartbitUsecase) GetChartPrice(ctx context.Context, symbol, timeframe, from, to string, limit int) (*domain.ChartPriceData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChartPrice", ctx, symbol, timeframe, from, to, limit)
	ret0, _ := ret[0].(*domain.ChartPriceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChartPrice indicates an expected call of GetChartPrice.
func (mr *MockChartbitUsecaseMockRecorder) GetChartPrice(ctx, symbol, timeframe, from, to, limit any) *MockChartbitUsecaseGetChartPriceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChartPrice", reflect.TypeOf((*MockChartbitUsecase)(nil).GetChartPrice), ctx, symbol, timeframe, from, to, limit)
	return &MockChartbitUsecaseGetChartPriceCall{Call: call}
}

// MockChartbitUsecaseGetChartPriceCall wrap *gomock.Call
type MockChartbitUsecaseGetChartPriceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChartbitUsecaseGetChartPriceCall) Return(arg0 *domain.ChartPriceData, arg1 error) *MockChartbitUsecaseGetChartPriceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChartbitUsecaseGetChartPriceCall) Do(f func(context.Context, string, string, string, string, int) (*domain.ChartPriceData, error)) *MockChartbitUsecaseGetChartPriceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChartbitUsecaseGetChartPriceCall) DoAndReturn(f func(context.Context, string, string, string, string, int) (*domain.ChartPriceData, error)) *MockChartbitUsecaseGetChartPriceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
