// Code generated by MockGen. DO NOT EDIT.
// Source: subsector.go
//
// Generated by this command:
//
//	mockgen -source=subsector.go -destination=../mocks/mock_subsector_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm-server/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSubsectorRepository is a mock of SubsectorRepository interface.
type MockSubsectorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubsectorRepositoryMockRecorder
	isgomock struct{}
}

// MockSubsectorRepositoryMockRecorder is the mock recorder for MockSubsectorRepository.
type MockSubsectorRepositoryMockRecorder struct {
	mock *MockSubsectorRepository
}

// NewMockSubsectorRepository creates a new mock instance.
func NewMockSubsectorRepository(ctrl *gomock.Controller) *MockSubsectorRepository {
	mock := &MockSubsectorRepository{ctrl: ctrl}
	mock.recorder = &MockSubsectorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubsectorRepository) EXPECT() *MockSubsectorRepositoryMockRecorder {
	return m.recorder
}

// GetCompanies mocks base method.
func (m *MockSubsectorRepository) GetCompanies(ctx context.Context, sectorID, subsectorID string) ([]domain.SubsectorCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanies", ctx, sectorID, subsectorID)
	ret0, _ := ret[0].([]domain.SubsectorCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanies indicates an expected call of GetCompanies.
func (mr *MockSubsectorRepositoryMockRecorder) GetCompanies(ctx, sectorID, subsectorID any) *MockSubsectorRepositoryGetCompaniesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanies", reflect.TypeOf((*MockSubsectorRepository)(nil).GetCompanies), ctx, sectorID, subsectorID)
	return &MockSubsectorRepositoryGetCompaniesCall{Call: call}
}

// MockSubsectorRepositoryGetCompaniesCall wrap *gomock.Call
type MockSubsectorRepositoryGetCompaniesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubsectorRepositoryGetCompaniesCall) Return(arg0 []domain.SubsectorCompany, arg1 error) *MockSubsectorRepositoryGetCompaniesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubsectorRepositoryGetCompaniesCall) Do(f func(context.Context, string, string) ([]domain.SubsectorCompany, error)) *MockSubsectorRepositoryGetCompaniesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubsectorRepositoryGetCompaniesCall) DoAndReturn(f func(context.Context, string, string) ([]domain.SubsectorCompany, error)) *MockSubsectorRepositoryGetCompaniesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
