// Code generated by MockGen. DO NOT EDIT.
// Source: subsidiary.go
//
// Generated by this command:
//
//	mockgen -source=subsidiary.go -destination=../mocks/mock_subsidiary_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm-server/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSubsidiaryRepository is a mock of SubsidiaryRepository interface.
type MockSubsidiaryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubsidiaryRepositoryMockRecorder
	isgomock struct{}
}

// MockSubsidiaryRepositoryMockRecorder is the mock recorder for MockSubsidiaryRepository.
type MockSubsidiaryRepositoryMockRecorder struct {
	mock *MockSubsidiaryRepository
}

// NewMockSubsidiaryRepository creates a new mock instance.
func NewMockSubsidiaryRepository(ctrl *gomock.Controller) *MockSubsidiaryRepository {
	mock := &MockSubsidiaryRepository{ctrl: ctrl}
	mock.recorder = &MockSubsidiaryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubsidiaryRepository) EXPECT() *MockSubsidiaryRepositoryMockRecorder {
	return m.recorder
}

// GetSubsidiaries mocks base method.
func (m *MockSubsidiaryRepository) GetSubsidiaries(ctx context.Context, symbol string) (*domain.SubsidiaryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubsidiaries", ctx, symbol)
	ret0, _ := ret[0].(*domain.SubsidiaryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubsidiaries indicates an expected call of GetSubsidiaries.
func (mr *MockSubsidiaryRepositoryMockRecorder) GetSubsidiaries(ctx, symbol any) *MockSubsidiaryRepositoryGetSubsidiariesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubsidiaries", reflect.TypeOf((*MockSubsidiaryRepository)(nil).GetSubsidiaries), ctx, symbol)
	return &MockSubsidiaryRepositoryGetSubsidiariesCall{Call: call}
}

// MockSubsidiaryRepositoryGetSubsidiariesCall wrap *gomock.Call
type MockSubsidiaryRepositoryGetSubsidiariesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubsidiaryRepositoryGetSubsidiariesCall) Return(arg0 *domain.SubsidiaryData, arg1 error) *MockSubsidiaryRepositoryGetSubsidiariesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubsidiaryRepositoryGetSubsidiariesCall) Do(f func(context.Context, string) (*domain.SubsidiaryData, error)) *MockSubsidiaryRepositoryGetSubsidiariesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubsidiaryRepositoryGetSubsidiariesCall) DoAndReturn(f func(context.Context, string) (*domain.SubsidiaryData, error)) *MockSubsidiaryRepositoryGetSubsidiariesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
