// Code generated by MockGen. DO NOT EDIT.
// Source: indexsummary.go
//
// Generated by this command:
//
//	mockgen -source=indexsummary.go -destination=../mocks/mock_indexsummary_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm-server/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIndexSummaryRepository is a mock of IndexSummaryRepository interface.
type MockIndexSummaryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIndexSummaryRepositoryMockRecorder
	isgomock struct{}
}

// MockIndexSummaryRepositoryMockRecorder is the mock recorder for MockIndexSummaryRepository.
type MockIndexSummaryRepositoryMockRecorder struct {
	mock *MockIndexSummaryRepository
}

// NewMockIndexSummaryRepository creates a new mock instance.
func NewMockIndexSummaryRepository(ctrl *gomock.Controller) *MockIndexSummaryRepository {
	mock := &MockIndexSummaryRepository{ctrl: ctrl}
	mock.recorder = &MockIndexSummaryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexSummaryRepository) EXPECT() *MockIndexSummaryRepositoryMockRecorder {
	return m.recorder
}

// GetIndexSummary mocks base method.
func (m *MockIndexSummaryRepository) GetIndexSummary(ctx context.Context, symbol, from, to, interval string) (*domain.IndexSummaryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexSummary", ctx, symbol, from, to, interval)
	ret0, _ := ret[0].(*domain.IndexSummaryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexSummary indicates an expected call of GetIndexSummary.
func (mr *MockIndexSummaryRepositoryMockRecorder) GetIndexSummary(ctx, symbol, from, to, interval any) *MockIndexSummaryRepositoryGetIndexSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexSummary", reflect.TypeOf((*MockIndexSummaryRepository)(nil).GetIndexSummary), ctx, symbol, from, to, interval)
	return &MockIndexSummaryRepositoryGetIndexSummaryCall{Call: call}
}

// MockIndexSummaryRepositoryGetIndexSummaryCall wrap *gomock.Call
type MockIndexSummaryRepositoryGetIndexSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexSummaryRepositoryGetIndexSummaryCall) Return(arg0 *domain.IndexSummaryData, arg1 error) *MockIndexSummaryRepositoryGetIndexSummaryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexSummaryRepositoryGetIndexSummaryCall) Do(f func(context.Context, string, string, string, string) (*domain.IndexSummaryData, error)) *MockIndexSummaryRepositoryGetIndexSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexSummaryRepositoryGetIndexSummaryCall) DoAndReturn(f func(context.Context, string, string, string, string) (*domain.IndexSummaryData, error)) *MockIndexSummaryRepositoryGetIndexSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
