// Code generated by MockGen. DO NOT EDIT.
// Source: findata_financial.go
//
// Generated by this command:
//
//	mockgen -source=findata_financial.go -destination=../mocks/mock_findata_financial_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm-server/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFindataFinancialRepository is a mock of FindataFinancialRepository interface.
type MockFindataFinancialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFindataFinancialRepositoryMockRecorder
	isgomock struct{}
}

// MockFindataFinancialRepositoryMockRecorder is the mock recorder for MockFindataFinancialRepository.
type MockFindataFinancialRepositoryMockRecorder struct {
	mock *MockFindataFinancialRepository
}

// NewMockFindataFinancialRepository creates a new mock instance.
func NewMockFindataFinancialRepository(ctrl *gomock.Controller) *MockFindataFinancialRepository {
	mock := &MockFindataFinancialRepository{ctrl: ctrl}
	mock.recorder = &MockFindataFinancialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindataFinancialRepository) EXPECT() *MockFindataFinancialRepositoryMockRecorder {
	return m.recorder
}

// GetFindataFinancial mocks base method.
func (m *MockFindataFinancialRepository) GetFindataFinancial(ctx context.Context, symbol string, dataType, isPercentage, page, reportType, statementType int) (*domain.FindataFinancial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFindataFinancial", ctx, symbol, dataType, isPercentage, page, reportType, statementType)
	ret0, _ := ret[0].(*domain.FindataFinancial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFindataFinancial indicates an expected call of GetFindataFinancial.
func (mr *MockFindataFinancialRepositoryMockRecorder) GetFindataFinancial(ctx, symbol, dataType, isPercentage, page, reportType, statementType any) *MockFindataFinancialRepositoryGetFindataFinancialCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFindataFinancial", reflect.TypeOf((*MockFindataFinancialRepository)(nil).GetFindataFinancial), ctx, symbol, dataType, isPercentage, page, reportType, statementType)
	return &MockFindataFinancialRepositoryGetFindataFinancialCall{Call: call}
}

// MockFindataFinancialRepositoryGetFindataFinancialCall wrap *gomock.Call
type MockFindataFinancialRepositoryGetFindataFinancialCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFindataFinancialRepositoryGetFindataFinancialCall) Return(arg0 *domain.FindataFinancial, arg1 error) *MockFindataFinancialRepositoryGetFindataFinancialCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFindataFinancialRepositoryGetFindataFinancialCall) Do(f func(context.Context, string, int, int, int, int, int) (*domain.FindataFinancial, error)) *MockFindataFinancialRepositoryGetFindataFinancialCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFindataFinancialRepositoryGetFindataFinancialCall) DoAndReturn(f func(context.Context, string, int, int, int, int, int) (*domain.FindataFinancial, error)) *MockFindataFinancialRepositoryGetFindataFinancialCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
