// Code generated by MockGen. DO NOT EDIT.
// Source: corpaction.go
//
// Generated by this command:
//
//	mockgen -source=corpaction.go -destination=../mocks/mock_corpaction_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm-server/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCorpActionUsecase is a mock of CorpActionUsecase interface.
type MockCorpActionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCorpActionUsecaseMockRecorder
	isgomock struct{}
}

// MockCorpActionUsecaseMockRecorder is the mock recorder for MockCorpActionUsecase.
type MockCorpActionUsecaseMockRecorder struct {
	mock *MockCorpActionUsecase
}

// NewMockCorpActionUsecase creates a new mock instance.
func NewMockCorpActionUsecase(ctrl *gomock.Controller) *MockCorpActionUsecase {
	mock := &MockCorpActionUsecase{ctrl: ctrl}
	mock.recorder = &MockCorpActionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCorpActionUsecase) EXPECT() *MockCorpActionUsecaseMockRecorder {
	return m.recorder
}

// GetCorpActions mocks base method.
func (m *MockCorpActionUsecase) GetCorpActions(ctx context.Context, symbol string, limit int) ([]domain.CompanyCorpAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCorpActions", ctx, symbol, limit)
	ret0, _ := ret[0].([]domain.CompanyCorpAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCorpActions indicates an expected call of GetCorpActions.
func (mr *MockCorpActionUsecaseMockRecorder) GetCorpActions(ctx, symbol, limit any) *MockCorpActionUsecaseGetCorpActionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCorpActions", reflect.TypeOf((*MockCorpActionUsecase)(nil).GetCorpActions), ctx, symbol, limit)
	return &MockCorpActionUsecaseGetCorpActionsCall{Call: call}
}

// MockCorpActionUsecaseGetCorpActionsCall wrap *gomock.Call
type MockCorpActionUsecaseGetCorpActionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCorpActionUsecaseGetCorpActionsCall) Return(arg0 []domain.CompanyCorpAction, arg1 error) *MockCorpActionUsecaseGetCorpActionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCorpActionUsecaseGetCorpActionsCall) Do(f func(context.Context, string, int) ([]domain.CompanyCorpAction, error)) *MockCorpActionUsecaseGetCorpActionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCorpActionUsecaseGetCorpActionsCall) DoAndReturn(f func(context.Context, string, int) ([]domain.CompanyCorpAction, error)) *MockCorpActionUsecaseGetCorpActionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
