// Code generated by MockGen. DO NOT EDIT.
// Source: priceperformance.go
//
// Generated by this command:
//
//	mockgen -source=priceperformance.go -destination=../mocks/mock_priceperformance_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm-server/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPricePerformanceRepository is a mock of PricePerformanceRepository interface.
type MockPricePerformanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPricePerformanceRepositoryMockRecorder
	isgomock struct{}
}

// MockPricePerformanceRepositoryMockRecorder is the mock recorder for MockPricePerformanceRepository.
type MockPricePerformanceRepositoryMockRecorder struct {
	mock *MockPricePerformanceRepository
}

// NewMockPricePerformanceRepository creates a new mock instance.
func NewMockPricePerformanceRepository(ctrl *gomock.Controller) *MockPricePerformanceRepository {
	mock := &MockPricePerformanceRepository{ctrl: ctrl}
	mock.recorder = &MockPricePerformanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPricePerformanceRepository) EXPECT() *MockPricePerformanceRepositoryMockRecorder {
	return m.recorder
}

// GetPricePerformance mocks base method.
func (m *MockPricePerformanceRepository) GetPricePerformance(ctx context.Context, symbol string) (*domain.PricePerformanceData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPricePerformance", ctx, symbol)
	ret0, _ := ret[0].(*domain.PricePerformanceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPricePerformance indicates an expected call of GetPricePerformance.
func (mr *MockPricePerformanceRepositoryMockRecorder) GetPricePerformance(ctx, symbol any) *MockPricePerformanceRepositoryGetPricePerformanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPricePerformance", reflect.TypeOf((*MockPricePerformanceRepository)(nil).GetPricePerformance), ctx, symbol)
	return &MockPricePerformanceRepositoryGetPricePerformanceCall{Call: call}
}

// MockPricePerformanceRepositoryGetPricePerformanceCall wrap *gomock.Call
type MockPricePerformanceRepositoryGetPricePerformanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPricePerformanceRepositoryGetPricePerformanceCall) Return(arg0 *domain.PricePerformanceData, arg1 error) *MockPricePerformanceRepositoryGetPricePerformanceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPricePerformanceRepositoryGetPricePerformanceCall) Do(f func(context.Context, string) (*domain.PricePerformanceData, error)) *MockPricePerformanceRepositoryGetPricePerformanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPricePerformanceRepositoryGetPricePerformanceCall) DoAndReturn(f func(context.Context, string) (*domain.PricePerformanceData, error)) *MockPricePerformanceRepositoryGetPricePerformanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
