// Code generated by MockGen. DO NOT EDIT.
// Source: stock.go
//
// Generated by this command:
//
//	mockgen -source=stock.go -destination=../mocks/mock_stock_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStockUsecase is a mock of StockUsecase interface.
type MockStockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockStockUsecaseMockRecorder
	isgomock struct{}
}

// MockStockUsecaseMockRecorder is the mock recorder for MockStockUsecase.
type MockStockUsecaseMockRecorder struct {
	mock *MockStockUsecase
}

// NewMockStockUsecase creates a new mock instance.
func NewMockStockUsecase(ctrl *gomock.Controller) *MockStockUsecase {
	mock := &MockStockUsecase{ctrl: ctrl}
	mock.recorder = &MockStockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockUsecase) EXPECT() *MockStockUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStockUsecase) Create(ctx context.Context, input domain.StockCreateInput) (domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStockUsecaseMockRecorder) Create(ctx, input any) *MockStockUsecaseCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStockUsecase)(nil).Create), ctx, input)
	return &MockStockUsecaseCreateCall{Call: call}
}

// MockStockUsecaseCreateCall wrap *gomock.Call
type MockStockUsecaseCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockUsecaseCreateCall) Return(arg0 domain.Stock, arg1 error) *MockStockUsecaseCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockUsecaseCreateCall) Do(f func(context.Context, domain.StockCreateInput) (domain.Stock, error)) *MockStockUsecaseCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockUsecaseCreateCall) DoAndReturn(f func(context.Context, domain.StockCreateInput) (domain.Stock, error)) *MockStockUsecaseCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetBySymbol mocks base method.
func (m *MockStockUsecase) GetBySymbol(ctx context.Context, symbol string) (domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySymbol", ctx, symbol)
	ret0, _ := ret[0].(domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySymbol indicates an expected call of GetBySymbol.
func (mr *MockStockUsecaseMockRecorder) GetBySymbol(ctx, symbol any) *MockStockUsecaseGetBySymbolCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySymbol", reflect.TypeOf((*MockStockUsecase)(nil).GetBySymbol), ctx, symbol)
	return &MockStockUsecaseGetBySymbolCall{Call: call}
}

// MockStockUsecaseGetBySymbolCall wrap *gomock.Call
type MockStockUsecaseGetBySymbolCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockUsecaseGetBySymbolCall) Return(arg0 domain.Stock, arg1 error) *MockStockUsecaseGetBySymbolCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockUsecaseGetBySymbolCall) Do(f func(context.Context, string) (domain.Stock, error)) *MockStockUsecaseGetBySymbolCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockUsecaseGetBySymbolCall) DoAndReturn(f func(context.Context, string) (domain.Stock, error)) *MockStockUsecaseGetBySymbolCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockStockUsecase) List(ctx context.Context, filter domain.StockFilter) ([]domain.Stock, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]domain.Stock)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockStockUsecaseMockRecorder) List(ctx, filter any) *MockStockUsecaseListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStockUsecase)(nil).List), ctx, filter)
	return &MockStockUsecaseListCall{Call: call}
}

// MockStockUsecaseListCall wrap *gomock.Call
type MockStockUsecaseListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockUsecaseListCall) Return(arg0 []domain.Stock, arg1 int, arg2 error) *MockStockUsecaseListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockUsecaseListCall) Do(f func(context.Context, domain.StockFilter) ([]domain.Stock, int, error)) *MockStockUsecaseListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockUsecaseListCall) DoAndReturn(f func(context.Context, domain.StockFilter) ([]domain.Stock, int, error)) *MockStockUsecaseListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoftDelete mocks base method.
func (m *MockStockUsecase) SoftDelete(ctx context.Context, symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockStockUsecaseMockRecorder) SoftDelete(ctx, symbol any) *MockStockUsecaseSoftDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockStockUsecase)(nil).SoftDelete), ctx, symbol)
	return &MockStockUsecaseSoftDeleteCall{Call: call}
}

// MockStockUsecaseSoftDeleteCall wrap *gomock.Call
type MockStockUsecaseSoftDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockUsecaseSoftDeleteCall) Return(arg0 error) *MockStockUsecaseSoftDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockUsecaseSoftDeleteCall) Do(f func(context.Context, string) error) *MockStockUsecaseSoftDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockUsecaseSoftDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockStockUsecaseSoftDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SyncAll mocks base method.
func (m *MockStockUsecase) SyncAll(ctx context.Context) (domain.StockSyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncAll", ctx)
	ret0, _ := ret[0].(domain.StockSyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncAll indicates an expected call of SyncAll.
func (mr *MockStockUsecaseMockRecorder) SyncAll(ctx any) *MockStockUsecaseSyncAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncAll", reflect.TypeOf((*MockStockUsecase)(nil).SyncAll), ctx)
	return &MockStockUsecaseSyncAllCall{Call: call}
}

// MockStockUsecaseSyncAllCall wrap *gomock.Call
type MockStockUsecaseSyncAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockUsecaseSyncAllCall) Return(arg0 domain.StockSyncResult, arg1 error) *MockStockUsecaseSyncAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockUsecaseSyncAllCall) Do(f func(context.Context) (domain.StockSyncResult, error)) *MockStockUsecaseSyncAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockUsecaseSyncAllCall) DoAndReturn(f func(context.Context) (domain.StockSyncResult, error)) *MockStockUsecaseSyncAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockStockUsecase) Update(ctx context.Context, symbol string, input domain.StockUpdateInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, symbol, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStockUsecaseMockRecorder) Update(ctx, symbol, input any) *MockStockUsecaseUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStockUsecase)(nil).Update), ctx, symbol, input)
	return &MockStockUsecaseUpdateCall{Call: call}
}

// MockStockUsecaseUpdateCall wrap *gomock.Call
type MockStockUsecaseUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockUsecaseUpdateCall) Return(arg0 error) *MockStockUsecaseUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockUsecaseUpdateCall) Do(f func(context.Context, string, domain.StockUpdateInput) error) *MockStockUsecaseUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockUsecaseUpdateCall) DoAndReturn(f func(context.Context, string, domain.StockUpdateInput) error) *MockStockUsecaseUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
