// Code generated by MockGen. DO NOT EDIT.
// Source: admin.go
//
// Generated by this command:
//
//	mockgen -source=admin.go -destination=../mocks/mock_admin_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/nofendian17/sbterm/apps/core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminUsecase is a mock of AdminUsecase interface.
type MockAdminUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUsecaseMockRecorder
	isgomock struct{}
}

// MockAdminUsecaseMockRecorder is the mock recorder for MockAdminUsecase.
type MockAdminUsecaseMockRecorder struct {
	mock *MockAdminUsecase
}

// NewMockAdminUsecase creates a new mock instance.
func NewMockAdminUsecase(ctrl *gomock.Controller) *MockAdminUsecase {
	mock := &MockAdminUsecase{ctrl: ctrl}
	mock.recorder = &MockAdminUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUsecase) EXPECT() *MockAdminUsecaseMockRecorder {
	return m.recorder
}

// AssignPermissionToRole mocks base method.
func (m *MockAdminUsecase) AssignPermissionToRole(ctx context.Context, roleID, permissionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignPermissionToRole", ctx, roleID, permissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignPermissionToRole indicates an expected call of AssignPermissionToRole.
func (mr *MockAdminUsecaseMockRecorder) AssignPermissionToRole(ctx, roleID, permissionID any) *MockAdminUsecaseAssignPermissionToRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignPermissionToRole", reflect.TypeOf((*MockAdminUsecase)(nil).AssignPermissionToRole), ctx, roleID, permissionID)
	return &MockAdminUsecaseAssignPermissionToRoleCall{Call: call}
}

// MockAdminUsecaseAssignPermissionToRoleCall wrap *gomock.Call
type MockAdminUsecaseAssignPermissionToRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseAssignPermissionToRoleCall) Return(arg0 error) *MockAdminUsecaseAssignPermissionToRoleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseAssignPermissionToRoleCall) Do(f func(context.Context, string, string) error) *MockAdminUsecaseAssignPermissionToRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseAssignPermissionToRoleCall) DoAndReturn(f func(context.Context, string, string) error) *MockAdminUsecaseAssignPermissionToRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AssignRoleToUser mocks base method.
func (m *MockAdminUsecase) AssignRoleToUser(ctx context.Context, userID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoleToUser", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRoleToUser indicates an expected call of AssignRoleToUser.
func (mr *MockAdminUsecaseMockRecorder) AssignRoleToUser(ctx, userID, roleID any) *MockAdminUsecaseAssignRoleToUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoleToUser", reflect.TypeOf((*MockAdminUsecase)(nil).AssignRoleToUser), ctx, userID, roleID)
	return &MockAdminUsecaseAssignRoleToUserCall{Call: call}
}

// MockAdminUsecaseAssignRoleToUserCall wrap *gomock.Call
type MockAdminUsecaseAssignRoleToUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseAssignRoleToUserCall) Return(arg0 error) *MockAdminUsecaseAssignRoleToUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseAssignRoleToUserCall) Do(f func(context.Context, string, string) error) *MockAdminUsecaseAssignRoleToUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseAssignRoleToUserCall) DoAndReturn(f func(context.Context, string, string) error) *MockAdminUsecaseAssignRoleToUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateRole mocks base method.
func (m *MockAdminUsecase) CreateRole(ctx context.Context, role domain.Role) (domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, role)
	ret0, _ := ret[0].(domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockAdminUsecaseMockRecorder) CreateRole(ctx, role any) *MockAdminUsecaseCreateRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockAdminUsecase)(nil).CreateRole), ctx, role)
	return &MockAdminUsecaseCreateRoleCall{Call: call}
}

// MockAdminUsecaseCreateRoleCall wrap *gomock.Call
type MockAdminUsecaseCreateRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseCreateRoleCall) Return(arg0 domain.Role, arg1 error) *MockAdminUsecaseCreateRoleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseCreateRoleCall) Do(f func(context.Context, domain.Role) (domain.Role, error)) *MockAdminUsecaseCreateRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseCreateRoleCall) DoAndReturn(f func(context.Context, domain.Role) (domain.Role, error)) *MockAdminUsecaseCreateRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteRole mocks base method.
func (m *MockAdminUsecase) DeleteRole(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockAdminUsecaseMockRecorder) DeleteRole(ctx, id any) *MockAdminUsecaseDeleteRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockAdminUsecase)(nil).DeleteRole), ctx, id)
	return &MockAdminUsecaseDeleteRoleCall{Call: call}
}

// MockAdminUsecaseDeleteRoleCall wrap *gomock.Call
type MockAdminUsecaseDeleteRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseDeleteRoleCall) Return(arg0 error) *MockAdminUsecaseDeleteRoleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseDeleteRoleCall) Do(f func(context.Context, string) error) *MockAdminUsecaseDeleteRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseDeleteRoleCall) DoAndReturn(f func(context.Context, string) error) *MockAdminUsecaseDeleteRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteUser mocks base method.
func (m *MockAdminUsecase) DeleteUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockAdminUsecaseMockRecorder) DeleteUser(ctx, id any) *MockAdminUsecaseDeleteUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockAdminUsecase)(nil).DeleteUser), ctx, id)
	return &MockAdminUsecaseDeleteUserCall{Call: call}
}

// MockAdminUsecaseDeleteUserCall wrap *gomock.Call
type MockAdminUsecaseDeleteUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseDeleteUserCall) Return(arg0 error) *MockAdminUsecaseDeleteUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseDeleteUserCall) Do(f func(context.Context, string) error) *MockAdminUsecaseDeleteUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseDeleteUserCall) DoAndReturn(f func(context.Context, string) error) *MockAdminUsecaseDeleteUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExtendExpiry mocks base method.
func (m *MockAdminUsecase) ExtendExpiry(ctx context.Context, id string, days int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendExpiry", ctx, id, days)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtendExpiry indicates an expected call of ExtendExpiry.
func (mr *MockAdminUsecaseMockRecorder) ExtendExpiry(ctx, id, days any) *MockAdminUsecaseExtendExpiryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendExpiry", reflect.TypeOf((*MockAdminUsecase)(nil).ExtendExpiry), ctx, id, days)
	return &MockAdminUsecaseExtendExpiryCall{Call: call}
}

// MockAdminUsecaseExtendExpiryCall wrap *gomock.Call
type MockAdminUsecaseExtendExpiryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseExtendExpiryCall) Return(arg0 error) *MockAdminUsecaseExtendExpiryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseExtendExpiryCall) Do(f func(context.Context, string, int) error) *MockAdminUsecaseExtendExpiryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseExtendExpiryCall) DoAndReturn(f func(context.Context, string, int) error) *MockAdminUsecaseExtendExpiryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRole mocks base method.
func (m *MockAdminUsecase) GetRole(ctx context.Context, id string) (domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, id)
	ret0, _ := ret[0].(domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockAdminUsecaseMockRecorder) GetRole(ctx, id any) *MockAdminUsecaseGetRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockAdminUsecase)(nil).GetRole), ctx, id)
	return &MockAdminUsecaseGetRoleCall{Call: call}
}

// MockAdminUsecaseGetRoleCall wrap *gomock.Call
type MockAdminUsecaseGetRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseGetRoleCall) Return(arg0 domain.Role, arg1 error) *MockAdminUsecaseGetRoleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseGetRoleCall) Do(f func(context.Context, string) (domain.Role, error)) *MockAdminUsecaseGetRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseGetRoleCall) DoAndReturn(f func(context.Context, string) (domain.Role, error)) *MockAdminUsecaseGetRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUser mocks base method.
func (m *MockAdminUsecase) GetUser(ctx context.Context, id string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAdminUsecaseMockRecorder) GetUser(ctx, id any) *MockAdminUsecaseGetUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAdminUsecase)(nil).GetUser), ctx, id)
	return &MockAdminUsecaseGetUserCall{Call: call}
}

// MockAdminUsecaseGetUserCall wrap *gomock.Call
type MockAdminUsecaseGetUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseGetUserCall) Return(arg0 domain.User, arg1 error) *MockAdminUsecaseGetUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseGetUserCall) Do(f func(context.Context, string) (domain.User, error)) *MockAdminUsecaseGetUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseGetUserCall) DoAndReturn(f func(context.Context, string) (domain.User, error)) *MockAdminUsecaseGetUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListRoles mocks base method.
func (m *MockAdminUsecase) ListRoles(ctx context.Context) ([]domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockAdminUsecaseMockRecorder) ListRoles(ctx any) *MockAdminUsecaseListRolesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockAdminUsecase)(nil).ListRoles), ctx)
	return &MockAdminUsecaseListRolesCall{Call: call}
}

// MockAdminUsecaseListRolesCall wrap *gomock.Call
type MockAdminUsecaseListRolesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseListRolesCall) Return(arg0 []domain.Role, arg1 error) *MockAdminUsecaseListRolesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseListRolesCall) Do(f func(context.Context) ([]domain.Role, error)) *MockAdminUsecaseListRolesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseListRolesCall) DoAndReturn(f func(context.Context) ([]domain.Role, error)) *MockAdminUsecaseListRolesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListUsers mocks base method.
func (m *MockAdminUsecase) ListUsers(ctx context.Context, page, limit int) ([]domain.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, page, limit)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAdminUsecaseMockRecorder) ListUsers(ctx, page, limit any) *MockAdminUsecaseListUsersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAdminUsecase)(nil).ListUsers), ctx, page, limit)
	return &MockAdminUsecaseListUsersCall{Call: call}
}

// MockAdminUsecaseListUsersCall wrap *gomock.Call
type MockAdminUsecaseListUsersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseListUsersCall) Return(arg0 []domain.User, arg1 int, arg2 error) *MockAdminUsecaseListUsersCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseListUsersCall) Do(f func(context.Context, int, int) ([]domain.User, int, error)) *MockAdminUsecaseListUsersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseListUsersCall) DoAndReturn(f func(context.Context, int, int) ([]domain.User, int, error)) *MockAdminUsecaseListUsersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokePermissionFromRole mocks base method.
func (m *MockAdminUsecase) RevokePermissionFromRole(ctx context.Context, roleID, permissionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokePermissionFromRole", ctx, roleID, permissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokePermissionFromRole indicates an expected call of RevokePermissionFromRole.
func (mr *MockAdminUsecaseMockRecorder) RevokePermissionFromRole(ctx, roleID, permissionID any) *MockAdminUsecaseRevokePermissionFromRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokePermissionFromRole", reflect.TypeOf((*MockAdminUsecase)(nil).RevokePermissionFromRole), ctx, roleID, permissionID)
	return &MockAdminUsecaseRevokePermissionFromRoleCall{Call: call}
}

// MockAdminUsecaseRevokePermissionFromRoleCall wrap *gomock.Call
type MockAdminUsecaseRevokePermissionFromRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseRevokePermissionFromRoleCall) Return(arg0 error) *MockAdminUsecaseRevokePermissionFromRoleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseRevokePermissionFromRoleCall) Do(f func(context.Context, string, string) error) *MockAdminUsecaseRevokePermissionFromRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseRevokePermissionFromRoleCall) DoAndReturn(f func(context.Context, string, string) error) *MockAdminUsecaseRevokePermissionFromRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeRoleFromUser mocks base method.
func (m *MockAdminUsecase) RevokeRoleFromUser(ctx context.Context, userID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRoleFromUser", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRoleFromUser indicates an expected call of RevokeRoleFromUser.
func (mr *MockAdminUsecaseMockRecorder) RevokeRoleFromUser(ctx, userID, roleID any) *MockAdminUsecaseRevokeRoleFromUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRoleFromUser", reflect.TypeOf((*MockAdminUsecase)(nil).RevokeRoleFromUser), ctx, userID, roleID)
	return &MockAdminUsecaseRevokeRoleFromUserCall{Call: call}
}

// MockAdminUsecaseRevokeRoleFromUserCall wrap *gomock.Call
type MockAdminUsecaseRevokeRoleFromUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseRevokeRoleFromUserCall) Return(arg0 error) *MockAdminUsecaseRevokeRoleFromUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseRevokeRoleFromUserCall) Do(f func(context.Context, string, string) error) *MockAdminUsecaseRevokeRoleFromUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseRevokeRoleFromUserCall) DoAndReturn(f func(context.Context, string, string) error) *MockAdminUsecaseRevokeRoleFromUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetExpiry mocks base method.
func (m *MockAdminUsecase) SetExpiry(ctx context.Context, id string, expiresAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExpiry", ctx, id, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetExpiry indicates an expected call of SetExpiry.
func (mr *MockAdminUsecaseMockRecorder) SetExpiry(ctx, id, expiresAt any) *MockAdminUsecaseSetExpiryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExpiry", reflect.TypeOf((*MockAdminUsecase)(nil).SetExpiry), ctx, id, expiresAt)
	return &MockAdminUsecaseSetExpiryCall{Call: call}
}

// MockAdminUsecaseSetExpiryCall wrap *gomock.Call
type MockAdminUsecaseSetExpiryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseSetExpiryCall) Return(arg0 error) *MockAdminUsecaseSetExpiryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseSetExpiryCall) Do(f func(context.Context, string, *time.Time) error) *MockAdminUsecaseSetExpiryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseSetExpiryCall) DoAndReturn(f func(context.Context, string, *time.Time) error) *MockAdminUsecaseSetExpiryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SuspendUser mocks base method.
func (m *MockAdminUsecase) SuspendUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuspendUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SuspendUser indicates an expected call of SuspendUser.
func (mr *MockAdminUsecaseMockRecorder) SuspendUser(ctx, id any) *MockAdminUsecaseSuspendUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuspendUser", reflect.TypeOf((*MockAdminUsecase)(nil).SuspendUser), ctx, id)
	return &MockAdminUsecaseSuspendUserCall{Call: call}
}

// MockAdminUsecaseSuspendUserCall wrap *gomock.Call
type MockAdminUsecaseSuspendUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminUsecaseSuspendUserCall) Return(arg0 error) *MockAdminUsecaseSuspendUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminUsecaseSuspendUserCall) Do(f func(context.Context, string) error) *MockAdminUsecaseSuspendUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminUsecaseSuspendUserCall) DoAndReturn(f func(context.Context, string) error) *MockAdminUsecaseSuspendUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
