// Code generated by MockGen. DO NOT EDIT.
// Source: rbac.go
//
// Generated by this command:
//
//	mockgen -source=rbac.go -destination=../mocks/mock_rbac_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRBACRepository is a mock of RBACRepository interface.
type MockRBACRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRBACRepositoryMockRecorder
	isgomock struct{}
}

// MockRBACRepositoryMockRecorder is the mock recorder for MockRBACRepository.
type MockRBACRepositoryMockRecorder struct {
	mock *MockRBACRepository
}

// NewMockRBACRepository creates a new mock instance.
func NewMockRBACRepository(ctrl *gomock.Controller) *MockRBACRepository {
	mock := &MockRBACRepository{ctrl: ctrl}
	mock.recorder = &MockRBACRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRBACRepository) EXPECT() *MockRBACRepositoryMockRecorder {
	return m.recorder
}

// AssignPermissionToRole mocks base method.
func (m *MockRBACRepository) AssignPermissionToRole(ctx context.Context, roleID, permissionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignPermissionToRole", ctx, roleID, permissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignPermissionToRole indicates an expected call of AssignPermissionToRole.
func (mr *MockRBACRepositoryMockRecorder) AssignPermissionToRole(ctx, roleID, permissionID any) *MockRBACRepositoryAssignPermissionToRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignPermissionToRole", reflect.TypeOf((*MockRBACRepository)(nil).AssignPermissionToRole), ctx, roleID, permissionID)
	return &MockRBACRepositoryAssignPermissionToRoleCall{Call: call}
}

// MockRBACRepositoryAssignPermissionToRoleCall wrap *gomock.Call
type MockRBACRepositoryAssignPermissionToRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRBACRepositoryAssignPermissionToRoleCall) Return(arg0 error) *MockRBACRepositoryAssignPermissionToRoleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRBACRepositoryAssignPermissionToRoleCall) Do(f func(context.Context, string, string) error) *MockRBACRepositoryAssignPermissionToRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRBACRepositoryAssignPermissionToRoleCall) DoAndReturn(f func(context.Context, string, string) error) *MockRBACRepositoryAssignPermissionToRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AssignRoleToUser mocks base method.
func (m *MockRBACRepository) AssignRoleToUser(ctx context.Context, userID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoleToUser", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRoleToUser indicates an expected call of AssignRoleToUser.
func (mr *MockRBACRepositoryMockRecorder) AssignRoleToUser(ctx, userID, roleID any) *MockRBACRepositoryAssignRoleToUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoleToUser", reflect.TypeOf((*MockRBACRepository)(nil).AssignRoleToUser), ctx, userID, roleID)
	return &MockRBACRepositoryAssignRoleToUserCall{Call: call}
}

// MockRBACRepositoryAssignRoleToUserCall wrap *gomock.Call
type MockRBACRepositoryAssignRoleToUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRBACRepositoryAssignRoleToUserCall) Return(arg0 error) *MockRBACRepositoryAssignRoleToUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRBACRepositoryAssignRoleToUserCall) Do(f func(context.Context, string, string) error) *MockRBACRepositoryAssignRoleToUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRBACRepositoryAssignRoleToUserCall) DoAndReturn(f func(context.Context, string, string) error) *MockRBACRepositoryAssignRoleToUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateRole mocks base method.
func (m *MockRBACRepository) CreateRole(ctx context.Context, role domain.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockRBACRepositoryMockRecorder) CreateRole(ctx, role any) *MockRBACRepositoryCreateRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockRBACRepository)(nil).CreateRole), ctx, role)
	return &MockRBACRepositoryCreateRoleCall{Call: call}
}

// MockRBACRepositoryCreateRoleCall wrap *gomock.Call
type MockRBACRepositoryCreateRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRBACRepositoryCreateRoleCall) Return(arg0 error) *MockRBACRepositoryCreateRoleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRBACRepositoryCreateRoleCall) Do(f func(context.Context, domain.Role) error) *MockRBACRepositoryCreateRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRBACRepositoryCreateRoleCall) DoAndReturn(f func(context.Context, domain.Role) error) *MockRBACRepositoryCreateRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteRole mocks base method.
func (m *MockRBACRepository) DeleteRole(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockRBACRepositoryMockRecorder) DeleteRole(ctx, id any) *MockRBACRepositoryDeleteRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockRBACRepository)(nil).DeleteRole), ctx, id)
	return &MockRBACRepositoryDeleteRoleCall{Call: call}
}

// MockRBACRepositoryDeleteRoleCall wrap *gomock.Call
type MockRBACRepositoryDeleteRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRBACRepositoryDeleteRoleCall) Return(arg0 error) *MockRBACRepositoryDeleteRoleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRBACRepositoryDeleteRoleCall) Do(f func(context.Context, string) error) *MockRBACRepositoryDeleteRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRBACRepositoryDeleteRoleCall) DoAndReturn(f func(context.Context, string) error) *MockRBACRepositoryDeleteRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRole mocks base method.
func (m *MockRBACRepository) GetRole(ctx context.Context, id string) (domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, id)
	ret0, _ := ret[0].(domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockRBACRepositoryMockRecorder) GetRole(ctx, id any) *MockRBACRepositoryGetRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockRBACRepository)(nil).GetRole), ctx, id)
	return &MockRBACRepositoryGetRoleCall{Call: call}
}

// MockRBACRepositoryGetRoleCall wrap *gomock.Call
type MockRBACRepositoryGetRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRBACRepositoryGetRoleCall) Return(arg0 domain.Role, arg1 error) *MockRBACRepositoryGetRoleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRBACRepositoryGetRoleCall) Do(f func(context.Context, string) (domain.Role, error)) *MockRBACRepositoryGetRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRBACRepositoryGetRoleCall) DoAndReturn(f func(context.Context, string) (domain.Role, error)) *MockRBACRepositoryGetRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListRoles mocks base method.
func (m *MockRBACRepository) ListRoles(ctx context.Context) ([]domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockRBACRepositoryMockRecorder) ListRoles(ctx any) *MockRBACRepositoryListRolesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockRBACRepository)(nil).ListRoles), ctx)
	return &MockRBACRepositoryListRolesCall{Call: call}
}

// MockRBACRepositoryListRolesCall wrap *gomock.Call
type MockRBACRepositoryListRolesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRBACRepositoryListRolesCall) Return(arg0 []domain.Role, arg1 error) *MockRBACRepositoryListRolesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRBACRepositoryListRolesCall) Do(f func(context.Context) ([]domain.Role, error)) *MockRBACRepositoryListRolesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRBACRepositoryListRolesCall) DoAndReturn(f func(context.Context) ([]domain.Role, error)) *MockRBACRepositoryListRolesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListUserIDsByRole mocks base method.
func (m *MockRBACRepository) ListUserIDsByRole(ctx context.Context, roleID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserIDsByRole", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserIDsByRole indicates an expected call of ListUserIDsByRole.
func (mr *MockRBACRepositoryMockRecorder) ListUserIDsByRole(ctx, roleID any) *MockRBACRepositoryListUserIDsByRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserIDsByRole", reflect.TypeOf((*MockRBACRepository)(nil).ListUserIDsByRole), ctx, roleID)
	return &MockRBACRepositoryListUserIDsByRoleCall{Call: call}
}

// MockRBACRepositoryListUserIDsByRoleCall wrap *gomock.Call
type MockRBACRepositoryListUserIDsByRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRBACRepositoryListUserIDsByRoleCall) Return(arg0 []string, arg1 error) *MockRBACRepositoryListUserIDsByRoleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRBACRepositoryListUserIDsByRoleCall) Do(f func(context.Context, string) ([]string, error)) *MockRBACRepositoryListUserIDsByRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRBACRepositoryListUserIDsByRoleCall) DoAndReturn(f func(context.Context, string) ([]string, error)) *MockRBACRepositoryListUserIDsByRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListUserPermissions mocks base method.
func (m *MockRBACRepository) ListUserPermissions(ctx context.Context, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserPermissions", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserPermissions indicates an expected call of ListUserPermissions.
func (mr *MockRBACRepositoryMockRecorder) ListUserPermissions(ctx, userID any) *MockRBACRepositoryListUserPermissionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserPermissions", reflect.TypeOf((*MockRBACRepository)(nil).ListUserPermissions), ctx, userID)
	return &MockRBACRepositoryListUserPermissionsCall{Call: call}
}

// MockRBACRepositoryListUserPermissionsCall wrap *gomock.Call
type MockRBACRepositoryListUserPermissionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRBACRepositoryListUserPermissionsCall) Return(arg0 []string, arg1 error) *MockRBACRepositoryListUserPermissionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRBACRepositoryListUserPermissionsCall) Do(f func(context.Context, string) ([]string, error)) *MockRBACRepositoryListUserPermissionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRBACRepositoryListUserPermissionsCall) DoAndReturn(f func(context.Context, string) ([]string, error)) *MockRBACRepositoryListUserPermissionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokePermissionFromRole mocks base method.
func (m *MockRBACRepository) RevokePermissionFromRole(ctx context.Context, roleID, permissionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokePermissionFromRole", ctx, roleID, permissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokePermissionFromRole indicates an expected call of RevokePermissionFromRole.
func (mr *MockRBACRepositoryMockRecorder) RevokePermissionFromRole(ctx, roleID, permissionID any) *MockRBACRepositoryRevokePermissionFromRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokePermissionFromRole", reflect.TypeOf((*MockRBACRepository)(nil).RevokePermissionFromRole), ctx, roleID, permissionID)
	return &MockRBACRepositoryRevokePermissionFromRoleCall{Call: call}
}

// MockRBACRepositoryRevokePermissionFromRoleCall wrap *gomock.Call
type MockRBACRepositoryRevokePermissionFromRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRBACRepositoryRevokePermissionFromRoleCall) Return(arg0 error) *MockRBACRepositoryRevokePermissionFromRoleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRBACRepositoryRevokePermissionFromRoleCall) Do(f func(context.Context, string, string) error) *MockRBACRepositoryRevokePermissionFromRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRBACRepositoryRevokePermissionFromRoleCall) DoAndReturn(f func(context.Context, string, string) error) *MockRBACRepositoryRevokePermissionFromRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeRoleFromUser mocks base method.
func (m *MockRBACRepository) RevokeRoleFromUser(ctx context.Context, userID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRoleFromUser", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRoleFromUser indicates an expected call of RevokeRoleFromUser.
func (mr *MockRBACRepositoryMockRecorder) RevokeRoleFromUser(ctx, userID, roleID any) *MockRBACRepositoryRevokeRoleFromUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRoleFromUser", reflect.TypeOf((*MockRBACRepository)(nil).RevokeRoleFromUser), ctx, userID, roleID)
	return &MockRBACRepositoryRevokeRoleFromUserCall{Call: call}
}

// MockRBACRepositoryRevokeRoleFromUserCall wrap *gomock.Call
type MockRBACRepositoryRevokeRoleFromUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRBACRepositoryRevokeRoleFromUserCall) Return(arg0 error) *MockRBACRepositoryRevokeRoleFromUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRBACRepositoryRevokeRoleFromUserCall) Do(f func(context.Context, string, string) error) *MockRBACRepositoryRevokeRoleFromUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRBACRepositoryRevokeRoleFromUserCall) DoAndReturn(f func(context.Context, string, string) error) *MockRBACRepositoryRevokeRoleFromUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
