// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=../mocks/mock_user_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/nofendian17/sbterm/apps/core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AssignDefaultRole mocks base method.
func (m *MockUserRepository) AssignDefaultRole(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDefaultRole", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignDefaultRole indicates an expected call of AssignDefaultRole.
func (mr *MockUserRepositoryMockRecorder) AssignDefaultRole(ctx, userID any) *MockUserRepositoryAssignDefaultRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDefaultRole", reflect.TypeOf((*MockUserRepository)(nil).AssignDefaultRole), ctx, userID)
	return &MockUserRepositoryAssignDefaultRoleCall{Call: call}
}

// MockUserRepositoryAssignDefaultRoleCall wrap *gomock.Call
type MockUserRepositoryAssignDefaultRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryAssignDefaultRoleCall) Return(arg0 error) *MockUserRepositoryAssignDefaultRoleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryAssignDefaultRoleCall) Do(f func(context.Context, string) error) *MockUserRepositoryAssignDefaultRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryAssignDefaultRoleCall) DoAndReturn(f func(context.Context, string) error) *MockUserRepositoryAssignDefaultRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *MockUserRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
	return &MockUserRepositoryCreateCall{Call: call}
}

// MockUserRepositoryCreateCall wrap *gomock.Call
type MockUserRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryCreateCall) Return(arg0 error) *MockUserRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryCreateCall) Do(f func(context.Context, domain.User) error) *MockUserRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.User) error) *MockUserRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *MockUserRepositoryGetByEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
	return &MockUserRepositoryGetByEmailCall{Call: call}
}

// MockUserRepositoryGetByEmailCall wrap *gomock.Call
type MockUserRepositoryGetByEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryGetByEmailCall) Return(arg0 domain.User, arg1 error) *MockUserRepositoryGetByEmailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryGetByEmailCall) Do(f func(context.Context, string) (domain.User, error)) *MockUserRepositoryGetByEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryGetByEmailCall) DoAndReturn(f func(context.Context, string) (domain.User, error)) *MockUserRepositoryGetByEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *MockUserRepositoryGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
	return &MockUserRepositoryGetByIDCall{Call: call}
}

// MockUserRepositoryGetByIDCall wrap *gomock.Call
type MockUserRepositoryGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryGetByIDCall) Return(arg0 domain.User, arg1 error) *MockUserRepositoryGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryGetByIDCall) Do(f func(context.Context, string) (domain.User, error)) *MockUserRepositoryGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryGetByIDCall) DoAndReturn(f func(context.Context, string) (domain.User, error)) *MockUserRepositoryGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAll mocks base method.
func (m *MockUserRepository) ListAll(ctx context.Context) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockUserRepositoryMockRecorder) ListAll(ctx any) *MockUserRepositoryListAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockUserRepository)(nil).ListAll), ctx)
	return &MockUserRepositoryListAllCall{Call: call}
}

// MockUserRepositoryListAllCall wrap *gomock.Call
type MockUserRepositoryListAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryListAllCall) Return(arg0 []domain.User, arg1 error) *MockUserRepositoryListAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryListAllCall) Do(f func(context.Context) ([]domain.User, error)) *MockUserRepositoryListAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryListAllCall) DoAndReturn(f func(context.Context) ([]domain.User, error)) *MockUserRepositoryListAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetExpiry mocks base method.
func (m *MockUserRepository) SetExpiry(ctx context.Context, id string, expiresAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExpiry", ctx, id, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetExpiry indicates an expected call of SetExpiry.
func (mr *MockUserRepositoryMockRecorder) SetExpiry(ctx, id, expiresAt any) *MockUserRepositorySetExpiryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExpiry", reflect.TypeOf((*MockUserRepository)(nil).SetExpiry), ctx, id, expiresAt)
	return &MockUserRepositorySetExpiryCall{Call: call}
}

// MockUserRepositorySetExpiryCall wrap *gomock.Call
type MockUserRepositorySetExpiryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositorySetExpiryCall) Return(arg0 error) *MockUserRepositorySetExpiryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositorySetExpiryCall) Do(f func(context.Context, string, *time.Time) error) *MockUserRepositorySetExpiryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositorySetExpiryCall) DoAndReturn(f func(context.Context, string, *time.Time) error) *MockUserRepositorySetExpiryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoftDelete mocks base method.
func (m *MockUserRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUserRepositoryMockRecorder) SoftDelete(ctx, id any) *MockUserRepositorySoftDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUserRepository)(nil).SoftDelete), ctx, id)
	return &MockUserRepositorySoftDeleteCall{Call: call}
}

// MockUserRepositorySoftDeleteCall wrap *gomock.Call
type MockUserRepositorySoftDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositorySoftDeleteCall) Return(arg0 error) *MockUserRepositorySoftDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositorySoftDeleteCall) Do(f func(context.Context, string) error) *MockUserRepositorySoftDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositorySoftDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockUserRepositorySoftDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, id, displayName string, expiresAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, displayName, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, id, displayName, expiresAt any) *MockUserRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, id, displayName, expiresAt)
	return &MockUserRepositoryUpdateCall{Call: call}
}

// MockUserRepositoryUpdateCall wrap *gomock.Call
type MockUserRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryUpdateCall) Return(arg0 error) *MockUserRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryUpdateCall) Do(f func(context.Context, string, string, *time.Time) error) *MockUserRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryUpdateCall) DoAndReturn(f func(context.Context, string, string, *time.Time) error) *MockUserRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
