// Code generated by MockGen. DO NOT EDIT.
// Source: company_profile.go
//
// Generated by this command:
//
//	mockgen -source=company_profile.go -destination=../mocks/mock_company_profile_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCompanyProfileUsecase is a mock of CompanyProfileUsecase interface.
type MockCompanyProfileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyProfileUsecaseMockRecorder
	isgomock struct{}
}

// MockCompanyProfileUsecaseMockRecorder is the mock recorder for MockCompanyProfileUsecase.
type MockCompanyProfileUsecaseMockRecorder struct {
	mock *MockCompanyProfileUsecase
}

// NewMockCompanyProfileUsecase creates a new mock instance.
func NewMockCompanyProfileUsecase(ctrl *gomock.Controller) *MockCompanyProfileUsecase {
	mock := &MockCompanyProfileUsecase{ctrl: ctrl}
	mock.recorder = &MockCompanyProfileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyProfileUsecase) EXPECT() *MockCompanyProfileUsecaseMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCompanyProfileUsecase) Get(ctx context.Context, symbol string) (domain.CompanyProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, symbol)
	ret0, _ := ret[0].(domain.CompanyProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCompanyProfileUsecaseMockRecorder) Get(ctx, symbol any) *MockCompanyProfileUsecaseGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompanyProfileUsecase)(nil).Get), ctx, symbol)
	return &MockCompanyProfileUsecaseGetCall{Call: call}
}

// MockCompanyProfileUsecaseGetCall wrap *gomock.Call
type MockCompanyProfileUsecaseGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCompanyProfileUsecaseGetCall) Return(arg0 domain.CompanyProfile, arg1 error) *MockCompanyProfileUsecaseGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCompanyProfileUsecaseGetCall) Do(f func(context.Context, string) (domain.CompanyProfile, error)) *MockCompanyProfileUsecaseGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCompanyProfileUsecaseGetCall) DoAndReturn(f func(context.Context, string) (domain.CompanyProfile, error)) *MockCompanyProfileUsecaseGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockCompanyProfileUsecase) Save(ctx context.Context, profile domain.CompanyProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCompanyProfileUsecaseMockRecorder) Save(ctx, profile any) *MockCompanyProfileUsecaseSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCompanyProfileUsecase)(nil).Save), ctx, profile)
	return &MockCompanyProfileUsecaseSaveCall{Call: call}
}

// MockCompanyProfileUsecaseSaveCall wrap *gomock.Call
type MockCompanyProfileUsecaseSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCompanyProfileUsecaseSaveCall) Return(arg0 error) *MockCompanyProfileUsecaseSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCompanyProfileUsecaseSaveCall) Do(f func(context.Context, domain.CompanyProfile) error) *MockCompanyProfileUsecaseSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCompanyProfileUsecaseSaveCall) DoAndReturn(f func(context.Context, domain.CompanyProfile) error) *MockCompanyProfileUsecaseSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SyncProfile mocks base method.
func (m *MockCompanyProfileUsecase) SyncProfile(ctx context.Context, symbol string) (domain.CompanyProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncProfile", ctx, symbol)
	ret0, _ := ret[0].(domain.CompanyProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncProfile indicates an expected call of SyncProfile.
func (mr *MockCompanyProfileUsecaseMockRecorder) SyncProfile(ctx, symbol any) *MockCompanyProfileUsecaseSyncProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncProfile", reflect.TypeOf((*MockCompanyProfileUsecase)(nil).SyncProfile), ctx, symbol)
	return &MockCompanyProfileUsecaseSyncProfileCall{Call: call}
}

// MockCompanyProfileUsecaseSyncProfileCall wrap *gomock.Call
type MockCompanyProfileUsecaseSyncProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCompanyProfileUsecaseSyncProfileCall) Return(arg0 domain.CompanyProfile, arg1 error) *MockCompanyProfileUsecaseSyncProfileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCompanyProfileUsecaseSyncProfileCall) Do(f func(context.Context, string) (domain.CompanyProfile, error)) *MockCompanyProfileUsecaseSyncProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCompanyProfileUsecaseSyncProfileCall) DoAndReturn(f func(context.Context, string) (domain.CompanyProfile, error)) *MockCompanyProfileUsecaseSyncProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
