// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: securities/trm/core/smart_order/entity/v1/smart_order.proto

// Reconstructed from stockbit.com webpack bundle (chunk 84882.8ffce90ef15dd07c.js,
// modules 23997, 61414) — protobuf-es message definitions. NOT an official schema.
// Enum smart order — dipakai oleh securities.trm.core.portfolio.entity.v2.Order.

package smartorderv1

import (
	_ "github.com/nofendian17/sbterm/libs/proto/securities/trm/core/smart_order/trailing_stop/order/entity/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetType int32

const (
	AssetType_ASSET_TYPE_UNSPECIFIED   AssetType = 0
	AssetType_ASSET_TYPE_STOCK_REGULAR AssetType = 1
	AssetType_ASSET_TYPE_STOCK_RIGHT   AssetType = 2
	AssetType_ASSET_TYPE_STOCK_WARRANT AssetType = 3
	AssetType_ASSET_TYPE_FR_BOND       AssetType = 4
	AssetType_ASSET_TYPE_MUTUAL_FUND   AssetType = 5
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_UNSPECIFIED",
		1: "ASSET_TYPE_STOCK_REGULAR",
		2: "ASSET_TYPE_STOCK_RIGHT",
		3: "ASSET_TYPE_STOCK_WARRANT",
		4: "ASSET_TYPE_FR_BOND",
		5: "ASSET_TYPE_MUTUAL_FUND",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_UNSPECIFIED":   0,
		"ASSET_TYPE_STOCK_REGULAR": 1,
		"ASSET_TYPE_STOCK_RIGHT":   2,
		"ASSET_TYPE_STOCK_WARRANT": 3,
		"ASSET_TYPE_FR_BOND":       4,
		"ASSET_TYPE_MUTUAL_FUND":   5,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[0].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[0]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescGZIP(), []int{0}
}

type MarketBoard int32

const (
	MarketBoard_MARKET_BOARD_UNSPECIFIED MarketBoard = 0
	MarketBoard_MARKET_BOARD_REGULER     MarketBoard = 1
	MarketBoard_MARKET_BOARD_TUNAI       MarketBoard = 2
)

// Enum value maps for MarketBoard.
var (
	MarketBoard_name = map[int32]string{
		0: "MARKET_BOARD_UNSPECIFIED",
		1: "MARKET_BOARD_REGULER",
		2: "MARKET_BOARD_TUNAI",
	}
	MarketBoard_value = map[string]int32{
		"MARKET_BOARD_UNSPECIFIED": 0,
		"MARKET_BOARD_REGULER":     1,
		"MARKET_BOARD_TUNAI":       2,
	}
)

func (x MarketBoard) Enum() *MarketBoard {
	p := new(MarketBoard)
	*p = x
	return p
}

func (x MarketBoard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketBoard) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[1].Descriptor()
}

func (MarketBoard) Type() protoreflect.EnumType {
	return &file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[1]
}

func (x MarketBoard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketBoard.Descriptor instead.
func (MarketBoard) EnumDescriptor() ([]byte, []int) {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescGZIP(), []int{1}
}

type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[2].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[2]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescGZIP(), []int{2}
}

type OrderExpiryType int32

const (
	OrderExpiryType_ORDER_EXPIRY_TYPE_UNSPECIFIED OrderExpiryType = 0
	OrderExpiryType_ORDER_EXPIRY_TYPE_GTC         OrderExpiryType = 1
	OrderExpiryType_ORDER_EXPIRY_TYPE_GFD         OrderExpiryType = 2
	OrderExpiryType_ORDER_EXPIRY_TYPE_FAK         OrderExpiryType = 3
)

// Enum value maps for OrderExpiryType.
var (
	OrderExpiryType_name = map[int32]string{
		0: "ORDER_EXPIRY_TYPE_UNSPECIFIED",
		1: "ORDER_EXPIRY_TYPE_GTC",
		2: "ORDER_EXPIRY_TYPE_GFD",
		3: "ORDER_EXPIRY_TYPE_FAK",
	}
	OrderExpiryType_value = map[string]int32{
		"ORDER_EXPIRY_TYPE_UNSPECIFIED": 0,
		"ORDER_EXPIRY_TYPE_GTC":         1,
		"ORDER_EXPIRY_TYPE_GFD":         2,
		"ORDER_EXPIRY_TYPE_FAK":         3,
	}
)

func (x OrderExpiryType) Enum() *OrderExpiryType {
	p := new(OrderExpiryType)
	*p = x
	return p
}

func (x OrderExpiryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderExpiryType) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[3].Descriptor()
}

func (OrderExpiryType) Type() protoreflect.EnumType {
	return &file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[3]
}

func (x OrderExpiryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderExpiryType.Descriptor instead.
func (OrderExpiryType) EnumDescriptor() ([]byte, []int) {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescGZIP(), []int{3}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_LIMIT",
		2: "ORDER_TYPE_MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_LIMIT":       1,
		"ORDER_TYPE_MARKET":      2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[4].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[4]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescGZIP(), []int{4}
}

type OrderTriggerType int32

const (
	OrderTriggerType_ORDER_TRIGGER_TYPE_UNSPECIFIED OrderTriggerType = 0
	OrderTriggerType_ORDER_TRIGGER_TYPE_LTE         OrderTriggerType = 1
	OrderTriggerType_ORDER_TRIGGER_TYPE_GTE         OrderTriggerType = 2
)

// Enum value maps for OrderTriggerType.
var (
	OrderTriggerType_name = map[int32]string{
		0: "ORDER_TRIGGER_TYPE_UNSPECIFIED",
		1: "ORDER_TRIGGER_TYPE_LTE",
		2: "ORDER_TRIGGER_TYPE_GTE",
	}
	OrderTriggerType_value = map[string]int32{
		"ORDER_TRIGGER_TYPE_UNSPECIFIED": 0,
		"ORDER_TRIGGER_TYPE_LTE":         1,
		"ORDER_TRIGGER_TYPE_GTE":         2,
	}
)

func (x OrderTriggerType) Enum() *OrderTriggerType {
	p := new(OrderTriggerType)
	*p = x
	return p
}

func (x OrderTriggerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderTriggerType) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[5].Descriptor()
}

func (OrderTriggerType) Type() protoreflect.EnumType {
	return &file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[5]
}

func (x OrderTriggerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderTriggerType.Descriptor instead.
func (OrderTriggerType) EnumDescriptor() ([]byte, []int) {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescGZIP(), []int{5}
}

type OrderBookSide int32

const (
	OrderBookSide_ORDER_BOOK_SIDE_UNSPECIFIED OrderBookSide = 0
	OrderBookSide_ORDER_BOOK_SIDE_BID         OrderBookSide = 1
	OrderBookSide_ORDER_BOOK_SIDE_ASK         OrderBookSide = 2
)

// Enum value maps for OrderBookSide.
var (
	OrderBookSide_name = map[int32]string{
		0: "ORDER_BOOK_SIDE_UNSPECIFIED",
		1: "ORDER_BOOK_SIDE_BID",
		2: "ORDER_BOOK_SIDE_ASK",
	}
	OrderBookSide_value = map[string]int32{
		"ORDER_BOOK_SIDE_UNSPECIFIED": 0,
		"ORDER_BOOK_SIDE_BID":         1,
		"ORDER_BOOK_SIDE_ASK":         2,
	}
)

func (x OrderBookSide) Enum() *OrderBookSide {
	p := new(OrderBookSide)
	*p = x
	return p
}

func (x OrderBookSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderBookSide) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[6].Descriptor()
}

func (OrderBookSide) Type() protoreflect.EnumType {
	return &file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[6]
}

func (x OrderBookSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderBookSide.Descriptor instead.
func (OrderBookSide) EnumDescriptor() ([]byte, []int) {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescGZIP(), []int{6}
}

// Dipakai sebagai enum status Order (module 23997, exports {i}).
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_READY            OrderStatus = 1
	OrderStatus_ORDER_STATUS_AMENDED          OrderStatus = 2
	OrderStatus_ORDER_STATUS_EXECUTED         OrderStatus = 3
	OrderStatus_ORDER_STATUS_WITHDRAWN        OrderStatus = 4
	OrderStatus_ORDER_STATUS_FORCE_DELETED    OrderStatus = 5
	OrderStatus_ORDER_STATUS_CORP_ACT_DELETED OrderStatus = 6
	OrderStatus_ORDER_STATUS_EXPIRED          OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_READY",
		2: "ORDER_STATUS_AMENDED",
		3: "ORDER_STATUS_EXECUTED",
		4: "ORDER_STATUS_WITHDRAWN",
		5: "ORDER_STATUS_FORCE_DELETED",
		6: "ORDER_STATUS_CORP_ACT_DELETED",
		7: "ORDER_STATUS_EXPIRED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_READY":            1,
		"ORDER_STATUS_AMENDED":          2,
		"ORDER_STATUS_EXECUTED":         3,
		"ORDER_STATUS_WITHDRAWN":        4,
		"ORDER_STATUS_FORCE_DELETED":    5,
		"ORDER_STATUS_CORP_ACT_DELETED": 6,
		"ORDER_STATUS_EXPIRED":          7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[7].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes[7]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescGZIP(), []int{7}
}

var File_securities_trm_core_smart_order_entity_v1_smart_order_proto protoreflect.FileDescriptor

const file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDesc = "" +
	"\n" +
	";securities/trm/core/smart_order/entity/v1/smart_order.proto\x12)securities.trm.core.smart_order.entity.v1\x1aQsecurities/trm/core/smart_order/trailing_stop/order/entity/v1/trailing_stop.proto*\xb3\x01\n" +
	"\tAssetType\x12\x1a\n" +
	"\x16ASSET_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ASSET_TYPE_STOCK_REGULAR\x10\x01\x12\x1a\n" +
	"\x16ASSET_TYPE_STOCK_RIGHT\x10\x02\x12\x1c\n" +
	"\x18ASSET_TYPE_STOCK_WARRANT\x10\x03\x12\x16\n" +
	"\x12ASSET_TYPE_FR_BOND\x10\x04\x12\x1a\n" +
	"\x16ASSET_TYPE_MUTUAL_FUND\x10\x05*]\n" +
	"\vMarketBoard\x12\x1c\n" +
	"\x18MARKET_BOARD_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MARKET_BOARD_REGULER\x10\x01\x12\x16\n" +
	"\x12MARKET_BOARD_TUNAI\x10\x02*P\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x02*\x85\x01\n" +
	"\x0fOrderExpiryType\x12!\n" +
	"\x1dORDER_EXPIRY_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ORDER_EXPIRY_TYPE_GTC\x10\x01\x12\x19\n" +
	"\x15ORDER_EXPIRY_TYPE_GFD\x10\x02\x12\x19\n" +
	"\x15ORDER_EXPIRY_TYPE_FAK\x10\x03*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x02*n\n" +
	"\x10OrderTriggerType\x12\"\n" +
	"\x1eORDER_TRIGGER_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ORDER_TRIGGER_TYPE_LTE\x10\x01\x12\x1a\n" +
	"\x16ORDER_TRIGGER_TYPE_GTE\x10\x02*b\n" +
	"\rOrderBookSide\x12\x1f\n" +
	"\x1bORDER_BOOK_SIDE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ORDER_BOOK_SIDE_BID\x10\x01\x12\x17\n" +
	"\x13ORDER_BOOK_SIDE_ASK\x10\x02*\xf1\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ORDER_STATUS_READY\x10\x01\x12\x18\n" +
	"\x14ORDER_STATUS_AMENDED\x10\x02\x12\x19\n" +
	"\x15ORDER_STATUS_EXECUTED\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_WITHDRAWN\x10\x04\x12\x1e\n" +
	"\x1aORDER_STATUS_FORCE_DELETED\x10\x05\x12!\n" +
	"\x1dORDER_STATUS_CORP_ACT_DELETED\x10\x06\x12\x18\n" +
	"\x14ORDER_STATUS_EXPIRED\x10\aB\x85\x01Z\x82\x01github.com/nofendian17/sbterm-server/internal/infrastructure/stockbit/proto/securities/trm/core/smart_order/entity/v1;smartorderv1b\x06proto3"

var (
	file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescOnce sync.Once
	file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescData []byte
)

func file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescGZIP() []byte {
	file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescOnce.Do(func() {
		file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDesc), len(file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDesc)))
	})
	return file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDescData
}

var file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_securities_trm_core_smart_order_entity_v1_smart_order_proto_goTypes = []any{
	(AssetType)(0),        // 0: securities.trm.core.smart_order.entity.v1.AssetType
	(MarketBoard)(0),      // 1: securities.trm.core.smart_order.entity.v1.MarketBoard
	(OrderSide)(0),        // 2: securities.trm.core.smart_order.entity.v1.OrderSide
	(OrderExpiryType)(0),  // 3: securities.trm.core.smart_order.entity.v1.OrderExpiryType
	(OrderType)(0),        // 4: securities.trm.core.smart_order.entity.v1.OrderType
	(OrderTriggerType)(0), // 5: securities.trm.core.smart_order.entity.v1.OrderTriggerType
	(OrderBookSide)(0),    // 6: securities.trm.core.smart_order.entity.v1.OrderBookSide
	(OrderStatus)(0),      // 7: securities.trm.core.smart_order.entity.v1.OrderStatus
}
var file_securities_trm_core_smart_order_entity_v1_smart_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_securities_trm_core_smart_order_entity_v1_smart_order_proto_init() }
func file_securities_trm_core_smart_order_entity_v1_smart_order_proto_init() {
	if File_securities_trm_core_smart_order_entity_v1_smart_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDesc), len(file_securities_trm_core_smart_order_entity_v1_smart_order_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_securities_trm_core_smart_order_entity_v1_smart_order_proto_goTypes,
		DependencyIndexes: file_securities_trm_core_smart_order_entity_v1_smart_order_proto_depIdxs,
		EnumInfos:         file_securities_trm_core_smart_order_entity_v1_smart_order_proto_enumTypes,
	}.Build()
	File_securities_trm_core_smart_order_entity_v1_smart_order_proto = out.File
	file_securities_trm_core_smart_order_entity_v1_smart_order_proto_goTypes = nil
	file_securities_trm_core_smart_order_entity_v1_smart_order_proto_depIdxs = nil
}
