// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: social/stream/data/v1/stream_data_v1.proto

// Reconstructed from stockbit.com webpack bundle (chunk 56256....js,
// module 45621) — protobuf-es message definitions. NOT an official schema.
// Data bersama stream social — koneksi wss://wssocial.stockbit.com/?wskey=<key>.

package streamdatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameType int32

const (
	FrameType_FRAME_TYPE_UNSPECIFIED FrameType = 0
	FrameType_FRAME_TYPE_SQUARE      FrameType = 1
	FrameType_FRAME_TYPE_PORTRAIT    FrameType = 2
	FrameType_FRAME_TYPE_LANDSCAPE   FrameType = 3
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "FRAME_TYPE_UNSPECIFIED",
		1: "FRAME_TYPE_SQUARE",
		2: "FRAME_TYPE_PORTRAIT",
		3: "FRAME_TYPE_LANDSCAPE",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_UNSPECIFIED": 0,
		"FRAME_TYPE_SQUARE":      1,
		"FRAME_TYPE_PORTRAIT":    2,
		"FRAME_TYPE_LANDSCAPE":   3,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_social_stream_data_v1_stream_data_v1_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_social_stream_data_v1_stream_data_v1_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_social_stream_data_v1_stream_data_v1_proto_rawDescGZIP(), []int{0}
}

// protobuf-es di bundle tidak wajib punya nilai 0; protoc mewajibkannya —
// COMMENTER_TYPE_EVERYONE = 0 memenuhi syarat sekaligus tetap sesuai bundle.
type CommenterType int32

const (
	CommenterType_COMMENTER_TYPE_EVERYONE  CommenterType = 0
	CommenterType_COMMENTER_TYPE_FOLLOWING CommenterType = 1
	CommenterType_COMMENTER_TYPE_MENTION   CommenterType = 2
	CommenterType_COMMENTER_TYPE_ONLY_YOU  CommenterType = 3
)

// Enum value maps for CommenterType.
var (
	CommenterType_name = map[int32]string{
		0: "COMMENTER_TYPE_EVERYONE",
		1: "COMMENTER_TYPE_FOLLOWING",
		2: "COMMENTER_TYPE_MENTION",
		3: "COMMENTER_TYPE_ONLY_YOU",
	}
	CommenterType_value = map[string]int32{
		"COMMENTER_TYPE_EVERYONE":  0,
		"COMMENTER_TYPE_FOLLOWING": 1,
		"COMMENTER_TYPE_MENTION":   2,
		"COMMENTER_TYPE_ONLY_YOU":  3,
	}
)

func (x CommenterType) Enum() *CommenterType {
	p := new(CommenterType)
	*p = x
	return p
}

func (x CommenterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommenterType) Descriptor() protoreflect.EnumDescriptor {
	return file_social_stream_data_v1_stream_data_v1_proto_enumTypes[1].Descriptor()
}

func (CommenterType) Type() protoreflect.EnumType {
	return &file_social_stream_data_v1_stream_data_v1_proto_enumTypes[1]
}

func (x CommenterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommenterType.Descriptor instead.
func (CommenterType) EnumDescriptor() ([]byte, []int) {
	return file_social_stream_data_v1_stream_data_v1_proto_rawDescGZIP(), []int{1}
}

type SpamStatus int32

const (
	SpamStatus_SPAM_STATUS_UNSPECIFIED SpamStatus = 0
	SpamStatus_SPAM_STATUS_DETECTED    SpamStatus = 1
	SpamStatus_SPAM_STATUS_DELETED     SpamStatus = 2
	SpamStatus_SPAM_STATUS_NOT_SPAM    SpamStatus = 3
)

// Enum value maps for SpamStatus.
var (
	SpamStatus_name = map[int32]string{
		0: "SPAM_STATUS_UNSPECIFIED",
		1: "SPAM_STATUS_DETECTED",
		2: "SPAM_STATUS_DELETED",
		3: "SPAM_STATUS_NOT_SPAM",
	}
	SpamStatus_value = map[string]int32{
		"SPAM_STATUS_UNSPECIFIED": 0,
		"SPAM_STATUS_DETECTED":    1,
		"SPAM_STATUS_DELETED":     2,
		"SPAM_STATUS_NOT_SPAM":    3,
	}
)

func (x SpamStatus) Enum() *SpamStatus {
	p := new(SpamStatus)
	*p = x
	return p
}

func (x SpamStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpamStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_social_stream_data_v1_stream_data_v1_proto_enumTypes[2].Descriptor()
}

func (SpamStatus) Type() protoreflect.EnumType {
	return &file_social_stream_data_v1_stream_data_v1_proto_enumTypes[2]
}

func (x SpamStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpamStatus.Descriptor instead.
func (SpamStatus) EnumDescriptor() ([]byte, []int) {
	return file_social_stream_data_v1_stream_data_v1_proto_rawDescGZIP(), []int{2}
}

var File_social_stream_data_v1_stream_data_v1_proto protoreflect.FileDescriptor

const file_social_stream_data_v1_stream_data_v1_proto_rawDesc = "" +
	"\n" +
	"*social/stream/data/v1/stream_data_v1.proto\x12\x15social.stream.data.v1*q\n" +
	"\tFrameType\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FRAME_TYPE_SQUARE\x10\x01\x12\x17\n" +
	"\x13FRAME_TYPE_PORTRAIT\x10\x02\x12\x18\n" +
	"\x14FRAME_TYPE_LANDSCAPE\x10\x03*\x83\x01\n" +
	"\rCommenterType\x12\x1b\n" +
	"\x17COMMENTER_TYPE_EVERYONE\x10\x00\x12\x1c\n" +
	"\x18COMMENTER_TYPE_FOLLOWING\x10\x01\x12\x1a\n" +
	"\x16COMMENTER_TYPE_MENTION\x10\x02\x12\x1b\n" +
	"\x17COMMENTER_TYPE_ONLY_YOU\x10\x03*v\n" +
	"\n" +
	"SpamStatus\x12\x1b\n" +
	"\x17SPAM_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SPAM_STATUS_DETECTED\x10\x01\x12\x17\n" +
	"\x13SPAM_STATUS_DELETED\x10\x02\x12\x18\n" +
	"\x14SPAM_STATUS_NOT_SPAM\x10\x03BpZngithub.com/nofendian17/sbterm-server/internal/infrastructure/stockbit/proto/social/stream/data/v1;streamdatav1b\x06proto3"

var (
	file_social_stream_data_v1_stream_data_v1_proto_rawDescOnce sync.Once
	file_social_stream_data_v1_stream_data_v1_proto_rawDescData []byte
)

func file_social_stream_data_v1_stream_data_v1_proto_rawDescGZIP() []byte {
	file_social_stream_data_v1_stream_data_v1_proto_rawDescOnce.Do(func() {
		file_social_stream_data_v1_stream_data_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_stream_data_v1_stream_data_v1_proto_rawDesc), len(file_social_stream_data_v1_stream_data_v1_proto_rawDesc)))
	})
	return file_social_stream_data_v1_stream_data_v1_proto_rawDescData
}

var file_social_stream_data_v1_stream_data_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_social_stream_data_v1_stream_data_v1_proto_goTypes = []any{
	(FrameType)(0),     // 0: social.stream.data.v1.FrameType
	(CommenterType)(0), // 1: social.stream.data.v1.CommenterType
	(SpamStatus)(0),    // 2: social.stream.data.v1.SpamStatus
}
var file_social_stream_data_v1_stream_data_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_social_stream_data_v1_stream_data_v1_proto_init() }
func file_social_stream_data_v1_stream_data_v1_proto_init() {
	if File_social_stream_data_v1_stream_data_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_stream_data_v1_stream_data_v1_proto_rawDesc), len(file_social_stream_data_v1_stream_data_v1_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_social_stream_data_v1_stream_data_v1_proto_goTypes,
		DependencyIndexes: file_social_stream_data_v1_stream_data_v1_proto_depIdxs,
		EnumInfos:         file_social_stream_data_v1_stream_data_v1_proto_enumTypes,
	}.Build()
	File_social_stream_data_v1_stream_data_v1_proto = out.File
	file_social_stream_data_v1_stream_data_v1_proto_goTypes = nil
	file_social_stream_data_v1_stream_data_v1_proto_depIdxs = nil
}
