// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: social/wssocial/entity/wsevent/stream/v1/stream.proto

// Reconstructed from stockbit.com webpack bundle (chunk 56256....js,
// module 45621) — protobuf-es message definitions. NOT an official schema.
// Event stream social — koneksi wss://wssocial.stockbit.com/?wskey=<key>.

package streamws1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceivedPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V1            *ReceivedPostV1        `protobuf:"bytes,1,opt,name=v1,proto3" json:"v1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceivedPost) Reset() {
	*x = ReceivedPost{}
	mi := &file_social_wssocial_entity_wsevent_stream_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedPost) ProtoMessage() {}

func (x *ReceivedPost) ProtoReflect() protoreflect.Message {
	mi := &file_social_wssocial_entity_wsevent_stream_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedPost.ProtoReflect.Descriptor instead.
func (*ReceivedPost) Descriptor() ([]byte, []int) {
	return file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *ReceivedPost) GetV1() *ReceivedPostV1 {
	if x != nil {
		return x.V1
	}
	return nil
}

type ReceivedPostV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      int64                  `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"` // T:3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceivedPostV1) Reset() {
	*x = ReceivedPostV1{}
	mi := &file_social_wssocial_entity_wsevent_stream_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedPostV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedPostV1) ProtoMessage() {}

func (x *ReceivedPostV1) ProtoReflect() protoreflect.Message {
	mi := &file_social_wssocial_entity_wsevent_stream_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedPostV1.ProtoReflect.Descriptor instead.
func (*ReceivedPostV1) Descriptor() ([]byte, []int) {
	return file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *ReceivedPostV1) GetStreamId() int64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

var File_social_wssocial_entity_wsevent_stream_v1_stream_proto protoreflect.FileDescriptor

const file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDesc = "" +
	"\n" +
	"5social/wssocial/entity/wsevent/stream/v1/stream.proto\x12(social.wssocial.entity.wsevent.stream.v1\"X\n" +
	"\fReceivedPost\x12H\n" +
	"\x02v1\x18\x01 \x01(\v28.social.wssocial.entity.wsevent.stream.v1.ReceivedPostV1R\x02v1\"-\n" +
	"\x0eReceivedPostV1\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x03R\bstreamIdB\x80\x01Z~github.com/nofendian17/sbterm-server/internal/infrastructure/stockbit/proto/social/wssocial/entity/wsevent/stream/v1;streamws1b\x06proto3"

var (
	file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDescOnce sync.Once
	file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDescData []byte
)

func file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDescGZIP() []byte {
	file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDescOnce.Do(func() {
		file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDesc), len(file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDesc)))
	})
	return file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDescData
}

var file_social_wssocial_entity_wsevent_stream_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_social_wssocial_entity_wsevent_stream_v1_stream_proto_goTypes = []any{
	(*ReceivedPost)(nil),   // 0: social.wssocial.entity.wsevent.stream.v1.ReceivedPost
	(*ReceivedPostV1)(nil), // 1: social.wssocial.entity.wsevent.stream.v1.ReceivedPostV1
}
var file_social_wssocial_entity_wsevent_stream_v1_stream_proto_depIdxs = []int32{
	1, // 0: social.wssocial.entity.wsevent.stream.v1.ReceivedPost.v1:type_name -> social.wssocial.entity.wsevent.stream.v1.ReceivedPostV1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_social_wssocial_entity_wsevent_stream_v1_stream_proto_init() }
func file_social_wssocial_entity_wsevent_stream_v1_stream_proto_init() {
	if File_social_wssocial_entity_wsevent_stream_v1_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDesc), len(file_social_wssocial_entity_wsevent_stream_v1_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_social_wssocial_entity_wsevent_stream_v1_stream_proto_goTypes,
		DependencyIndexes: file_social_wssocial_entity_wsevent_stream_v1_stream_proto_depIdxs,
		MessageInfos:      file_social_wssocial_entity_wsevent_stream_v1_stream_proto_msgTypes,
	}.Build()
	File_social_wssocial_entity_wsevent_stream_v1_stream_proto = out.File
	file_social_wssocial_entity_wsevent_stream_v1_stream_proto_goTypes = nil
	file_social_wssocial_entity_wsevent_stream_v1_stream_proto_depIdxs = nil
}
