// Code generated by MockGen. DO NOT EDIT.
// Source: company_profile.go
//
// Generated by this command:
//
//	mockgen -source=company_profile.go -destination=../mocks/mock_company_profile_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCompanyProfileRepository is a mock of CompanyProfileRepository interface.
type MockCompanyProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockCompanyProfileRepositoryMockRecorder is the mock recorder for MockCompanyProfileRepository.
type MockCompanyProfileRepositoryMockRecorder struct {
	mock *MockCompanyProfileRepository
}

// NewMockCompanyProfileRepository creates a new mock instance.
func NewMockCompanyProfileRepository(ctrl *gomock.Controller) *MockCompanyProfileRepository {
	mock := &MockCompanyProfileRepository{ctrl: ctrl}
	mock.recorder = &MockCompanyProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyProfileRepository) EXPECT() *MockCompanyProfileRepositoryMockRecorder {
	return m.recorder
}

// GetProfile mocks base method.
func (m *MockCompanyProfileRepository) GetProfile(ctx context.Context, symbol string) (*domain.CompanyProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, symbol)
	ret0, _ := ret[0].(*domain.CompanyProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockCompanyProfileRepositoryMockRecorder) GetProfile(ctx, symbol any) *MockCompanyProfileRepositoryGetProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockCompanyProfileRepository)(nil).GetProfile), ctx, symbol)
	return &MockCompanyProfileRepositoryGetProfileCall{Call: call}
}

// MockCompanyProfileRepositoryGetProfileCall wrap *gomock.Call
type MockCompanyProfileRepositoryGetProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCompanyProfileRepositoryGetProfileCall) Return(arg0 *domain.CompanyProfile, arg1 error) *MockCompanyProfileRepositoryGetProfileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCompanyProfileRepositoryGetProfileCall) Do(f func(context.Context, string) (*domain.CompanyProfile, error)) *MockCompanyProfileRepositoryGetProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCompanyProfileRepositoryGetProfileCall) DoAndReturn(f func(context.Context, string) (*domain.CompanyProfile, error)) *MockCompanyProfileRepositoryGetProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
