// Code generated by MockGen. DO NOT EDIT.
// Source: activity.go
//
// Generated by this command:
//
//	mockgen -source=activity.go -destination=../mocks/mock_activity_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityUsecase is a mock of ActivityUsecase interface.
type MockActivityUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockActivityUsecaseMockRecorder
	isgomock struct{}
}

// MockActivityUsecaseMockRecorder is the mock recorder for MockActivityUsecase.
type MockActivityUsecaseMockRecorder struct {
	mock *MockActivityUsecase
}

// NewMockActivityUsecase creates a new mock instance.
func NewMockActivityUsecase(ctrl *gomock.Controller) *MockActivityUsecase {
	mock := &MockActivityUsecase{ctrl: ctrl}
	mock.recorder = &MockActivityUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityUsecase) EXPECT() *MockActivityUsecaseMockRecorder {
	return m.recorder
}

// GetActivity mocks base method.
func (m *MockActivityUsecase) GetActivity(ctx context.Context, brokerCode []string, transactionType, investorType, marketBoard string, limit, page int, from, to, netValPeriod string) (*domain.ActivityData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivity", ctx, brokerCode, transactionType, investorType, marketBoard, limit, page, from, to, netValPeriod)
	ret0, _ := ret[0].(*domain.ActivityData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivity indicates an expected call of GetActivity.
func (mr *MockActivityUsecaseMockRecorder) GetActivity(ctx, brokerCode, transactionType, investorType, marketBoard, limit, page, from, to, netValPeriod any) *MockActivityUsecaseGetActivityCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivity", reflect.TypeOf((*MockActivityUsecase)(nil).GetActivity), ctx, brokerCode, transactionType, investorType, marketBoard, limit, page, from, to, netValPeriod)
	return &MockActivityUsecaseGetActivityCall{Call: call}
}

// MockActivityUsecaseGetActivityCall wrap *gomock.Call
type MockActivityUsecaseGetActivityCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockActivityUsecaseGetActivityCall) Return(arg0 *domain.ActivityData, arg1 error) *MockActivityUsecaseGetActivityCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockActivityUsecaseGetActivityCall) Do(f func(context.Context, []string, string, string, string, int, int, string, string, string) (*domain.ActivityData, error)) *MockActivityUsecaseGetActivityCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockActivityUsecaseGetActivityCall) DoAndReturn(f func(context.Context, []string, string, string, string, int, int, string, string, string) (*domain.ActivityData, error)) *MockActivityUsecaseGetActivityCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetActivityChart mocks base method.
func (m *MockActivityUsecase) GetActivityChart(ctx context.Context, symbols, brokersCode []string, from, to, period, investorType, marketBoard string) (*domain.ActivityChartData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityChart", ctx, symbols, brokersCode, from, to, period, investorType, marketBoard)
	ret0, _ := ret[0].(*domain.ActivityChartData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityChart indicates an expected call of GetActivityChart.
func (mr *MockActivityUsecaseMockRecorder) GetActivityChart(ctx, symbols, brokersCode, from, to, period, investorType, marketBoard any) *MockActivityUsecaseGetActivityChartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityChart", reflect.TypeOf((*MockActivityUsecase)(nil).GetActivityChart), ctx, symbols, brokersCode, from, to, period, investorType, marketBoard)
	return &MockActivityUsecaseGetActivityChartCall{Call: call}
}

// MockActivityUsecaseGetActivityChartCall wrap *gomock.Call
type MockActivityUsecaseGetActivityChartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockActivityUsecaseGetActivityChartCall) Return(arg0 *domain.ActivityChartData, arg1 error) *MockActivityUsecaseGetActivityChartCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockActivityUsecaseGetActivityChartCall) Do(f func(context.Context, []string, []string, string, string, string, string, string) (*domain.ActivityChartData, error)) *MockActivityUsecaseGetActivityChartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockActivityUsecaseGetActivityChartCall) DoAndReturn(f func(context.Context, []string, []string, string, string, string, string, string) (*domain.ActivityChartData, error)) *MockActivityUsecaseGetActivityChartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetActivityHistorical mocks base method.
func (m *MockActivityUsecase) GetActivityHistorical(ctx context.Context, interval, dateFrom, dateTo string, brokerCodes, symbols []string, marketBoard, investorType, netInterval string) (*domain.ActivityHistoricalData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityHistorical", ctx, interval, dateFrom, dateTo, brokerCodes, symbols, marketBoard, investorType, netInterval)
	ret0, _ := ret[0].(*domain.ActivityHistoricalData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityHistorical indicates an expected call of GetActivityHistorical.
func (mr *MockActivityUsecaseMockRecorder) GetActivityHistorical(ctx, interval, dateFrom, dateTo, brokerCodes, symbols, marketBoard, investorType, netInterval any) *MockActivityUsecaseGetActivityHistoricalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityHistorical", reflect.TypeOf((*MockActivityUsecase)(nil).GetActivityHistorical), ctx, interval, dateFrom, dateTo, brokerCodes, symbols, marketBoard, investorType, netInterval)
	return &MockActivityUsecaseGetActivityHistoricalCall{Call: call}
}

// MockActivityUsecaseGetActivityHistoricalCall wrap *gomock.Call
type MockActivityUsecaseGetActivityHistoricalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockActivityUsecaseGetActivityHistoricalCall) Return(arg0 *domain.ActivityHistoricalData, arg1 error) *MockActivityUsecaseGetActivityHistoricalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockActivityUsecaseGetActivityHistoricalCall) Do(f func(context.Context, string, string, string, []string, []string, string, string, string) (*domain.ActivityHistoricalData, error)) *MockActivityUsecaseGetActivityHistoricalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockActivityUsecaseGetActivityHistoricalCall) DoAndReturn(f func(context.Context, string, string, string, []string, []string, string, string, string) (*domain.ActivityHistoricalData, error)) *MockActivityUsecaseGetActivityHistoricalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetBrokerDistribution mocks base method.
func (m *MockActivityUsecase) GetBrokerDistribution(ctx context.Context, symbol, investorType, marketBoard, dataType, date, from, to string) (*domain.BrokerDistributionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrokerDistribution", ctx, symbol, investorType, marketBoard, dataType, date, from, to)
	ret0, _ := ret[0].(*domain.BrokerDistributionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBrokerDistribution indicates an expected call of GetBrokerDistribution.
func (mr *MockActivityUsecaseMockRecorder) GetBrokerDistribution(ctx, symbol, investorType, marketBoard, dataType, date, from, to any) *MockActivityUsecaseGetBrokerDistributionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrokerDistribution", reflect.TypeOf((*MockActivityUsecase)(nil).GetBrokerDistribution), ctx, symbol, investorType, marketBoard, dataType, date, from, to)
	return &MockActivityUsecaseGetBrokerDistributionCall{Call: call}
}

// MockActivityUsecaseGetBrokerDistributionCall wrap *gomock.Call
type MockActivityUsecaseGetBrokerDistributionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockActivityUsecaseGetBrokerDistributionCall) Return(arg0 *domain.BrokerDistributionData, arg1 error) *MockActivityUsecaseGetBrokerDistributionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockActivityUsecaseGetBrokerDistributionCall) Do(f func(context.Context, string, string, string, string, string, string, string) (*domain.BrokerDistributionData, error)) *MockActivityUsecaseGetBrokerDistributionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockActivityUsecaseGetBrokerDistributionCall) DoAndReturn(f func(context.Context, string, string, string, string, string, string, string) (*domain.BrokerDistributionData, error)) *MockActivityUsecaseGetBrokerDistributionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
