// Code generated by MockGen. DO NOT EDIT.
// Source: priceperformance.go
//
// Generated by this command:
//
//	mockgen -source=priceperformance.go -destination=../mocks/mock_priceperformance_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPricePerformanceUsecase is a mock of PricePerformanceUsecase interface.
type MockPricePerformanceUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPricePerformanceUsecaseMockRecorder
	isgomock struct{}
}

// MockPricePerformanceUsecaseMockRecorder is the mock recorder for MockPricePerformanceUsecase.
type MockPricePerformanceUsecaseMockRecorder struct {
	mock *MockPricePerformanceUsecase
}

// NewMockPricePerformanceUsecase creates a new mock instance.
func NewMockPricePerformanceUsecase(ctrl *gomock.Controller) *MockPricePerformanceUsecase {
	mock := &MockPricePerformanceUsecase{ctrl: ctrl}
	mock.recorder = &MockPricePerformanceUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPricePerformanceUsecase) EXPECT() *MockPricePerformanceUsecaseMockRecorder {
	return m.recorder
}

// GetPricePerformance mocks base method.
func (m *MockPricePerformanceUsecase) GetPricePerformance(ctx context.Context, symbol string) (*domain.PricePerformanceData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPricePerformance", ctx, symbol)
	ret0, _ := ret[0].(*domain.PricePerformanceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPricePerformance indicates an expected call of GetPricePerformance.
func (mr *MockPricePerformanceUsecaseMockRecorder) GetPricePerformance(ctx, symbol any) *MockPricePerformanceUsecaseGetPricePerformanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPricePerformance", reflect.TypeOf((*MockPricePerformanceUsecase)(nil).GetPricePerformance), ctx, symbol)
	return &MockPricePerformanceUsecaseGetPricePerformanceCall{Call: call}
}

// MockPricePerformanceUsecaseGetPricePerformanceCall wrap *gomock.Call
type MockPricePerformanceUsecaseGetPricePerformanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPricePerformanceUsecaseGetPricePerformanceCall) Return(arg0 *domain.PricePerformanceData, arg1 error) *MockPricePerformanceUsecaseGetPricePerformanceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPricePerformanceUsecaseGetPricePerformanceCall) Do(f func(context.Context, string) (*domain.PricePerformanceData, error)) *MockPricePerformanceUsecaseGetPricePerformanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPricePerformanceUsecaseGetPricePerformanceCall) DoAndReturn(f func(context.Context, string) (*domain.PricePerformanceData, error)) *MockPricePerformanceUsecaseGetPricePerformanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
