// Code generated by MockGen. DO NOT EDIT.
// Source: stocks.go
//
// Generated by this command:
//
//	mockgen -source=stocks.go -destination=../mocks/mock_stocks_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStocksRepository is a mock of StocksRepository interface.
type MockStocksRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStocksRepositoryMockRecorder
	isgomock struct{}
}

// MockStocksRepositoryMockRecorder is the mock recorder for MockStocksRepository.
type MockStocksRepositoryMockRecorder struct {
	mock *MockStocksRepository
}

// NewMockStocksRepository creates a new mock instance.
func NewMockStocksRepository(ctrl *gomock.Controller) *MockStocksRepository {
	mock := &MockStocksRepository{ctrl: ctrl}
	mock.recorder = &MockStocksRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStocksRepository) EXPECT() *MockStocksRepositoryMockRecorder {
	return m.recorder
}

// GetStocks mocks base method.
func (m *MockStocksRepository) GetStocks(ctx context.Context) ([]domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStocks", ctx)
	ret0, _ := ret[0].([]domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStocks indicates an expected call of GetStocks.
func (mr *MockStocksRepositoryMockRecorder) GetStocks(ctx any) *MockStocksRepositoryGetStocksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStocks", reflect.TypeOf((*MockStocksRepository)(nil).GetStocks), ctx)
	return &MockStocksRepositoryGetStocksCall{Call: call}
}

// MockStocksRepositoryGetStocksCall wrap *gomock.Call
type MockStocksRepositoryGetStocksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStocksRepositoryGetStocksCall) Return(arg0 []domain.Stock, arg1 error) *MockStocksRepositoryGetStocksCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStocksRepositoryGetStocksCall) Do(f func(context.Context) ([]domain.Stock, error)) *MockStocksRepositoryGetStocksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStocksRepositoryGetStocksCall) DoAndReturn(f func(context.Context) ([]domain.Stock, error)) *MockStocksRepositoryGetStocksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
