// Code generated by MockGen. DO NOT EDIT.
// Source: notification.go
//
// Generated by this command:
//
//	mockgen -source=notification.go -destination=../mocks/mock_notification_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationUsecase is a mock of NotificationUsecase interface.
type MockNotificationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationUsecaseMockRecorder
	isgomock struct{}
}

// MockNotificationUsecaseMockRecorder is the mock recorder for MockNotificationUsecase.
type MockNotificationUsecaseMockRecorder struct {
	mock *MockNotificationUsecase
}

// NewMockNotificationUsecase creates a new mock instance.
func NewMockNotificationUsecase(ctrl *gomock.Controller) *MockNotificationUsecase {
	mock := &MockNotificationUsecase{ctrl: ctrl}
	mock.recorder = &MockNotificationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationUsecase) EXPECT() *MockNotificationUsecaseMockRecorder {
	return m.recorder
}

// GetNotifications mocks base method.
func (m *MockNotificationUsecase) GetNotifications(ctx context.Context, lastID int64, limit int, types []string) (*domain.NotificationList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotifications", ctx, lastID, limit, types)
	ret0, _ := ret[0].(*domain.NotificationList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotifications indicates an expected call of GetNotifications.
func (mr *MockNotificationUsecaseMockRecorder) GetNotifications(ctx, lastID, limit, types any) *MockNotificationUsecaseGetNotificationsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotifications", reflect.TypeOf((*MockNotificationUsecase)(nil).GetNotifications), ctx, lastID, limit, types)
	return &MockNotificationUsecaseGetNotificationsCall{Call: call}
}

// MockNotificationUsecaseGetNotificationsCall wrap *gomock.Call
type MockNotificationUsecaseGetNotificationsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNotificationUsecaseGetNotificationsCall) Return(arg0 *domain.NotificationList, arg1 error) *MockNotificationUsecaseGetNotificationsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNotificationUsecaseGetNotificationsCall) Do(f func(context.Context, int64, int, []string) (*domain.NotificationList, error)) *MockNotificationUsecaseGetNotificationsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNotificationUsecaseGetNotificationsCall) DoAndReturn(f func(context.Context, int64, int, []string) (*domain.NotificationList, error)) *MockNotificationUsecaseGetNotificationsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
