// Code generated by MockGen. DO NOT EDIT.
// Source: brokertop.go
//
// Generated by this command:
//
//	mockgen -source=brokertop.go -destination=../mocks/mock_brokertop_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBrokerTopUsecase is a mock of BrokerTopUsecase interface.
type MockBrokerTopUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerTopUsecaseMockRecorder
	isgomock struct{}
}

// MockBrokerTopUsecaseMockRecorder is the mock recorder for MockBrokerTopUsecase.
type MockBrokerTopUsecaseMockRecorder struct {
	mock *MockBrokerTopUsecase
}

// NewMockBrokerTopUsecase creates a new mock instance.
func NewMockBrokerTopUsecase(ctrl *gomock.Controller) *MockBrokerTopUsecase {
	mock := &MockBrokerTopUsecase{ctrl: ctrl}
	mock.recorder = &MockBrokerTopUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerTopUsecase) EXPECT() *MockBrokerTopUsecaseMockRecorder {
	return m.recorder
}

// GetBrokerTop mocks base method.
func (m *MockBrokerTopUsecase) GetBrokerTop(ctx context.Context, sort, order, period, marketType string, eodOnly bool) (*domain.BrokerTopData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrokerTop", ctx, sort, order, period, marketType, eodOnly)
	ret0, _ := ret[0].(*domain.BrokerTopData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBrokerTop indicates an expected call of GetBrokerTop.
func (mr *MockBrokerTopUsecaseMockRecorder) GetBrokerTop(ctx, sort, order, period, marketType, eodOnly any) *MockBrokerTopUsecaseGetBrokerTopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrokerTop", reflect.TypeOf((*MockBrokerTopUsecase)(nil).GetBrokerTop), ctx, sort, order, period, marketType, eodOnly)
	return &MockBrokerTopUsecaseGetBrokerTopCall{Call: call}
}

// MockBrokerTopUsecaseGetBrokerTopCall wrap *gomock.Call
type MockBrokerTopUsecaseGetBrokerTopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBrokerTopUsecaseGetBrokerTopCall) Return(arg0 *domain.BrokerTopData, arg1 error) *MockBrokerTopUsecaseGetBrokerTopCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBrokerTopUsecaseGetBrokerTopCall) Do(f func(context.Context, string, string, string, string, bool) (*domain.BrokerTopData, error)) *MockBrokerTopUsecaseGetBrokerTopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBrokerTopUsecaseGetBrokerTopCall) DoAndReturn(f func(context.Context, string, string, string, string, bool) (*domain.BrokerTopData, error)) *MockBrokerTopUsecaseGetBrokerTopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
