// Code generated by MockGen. DO NOT EDIT.
// Source: subsidiary.go
//
// Generated by this command:
//
//	mockgen -source=subsidiary.go -destination=../mocks/mock_subsidiary_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSubsidiaryUsecase is a mock of SubsidiaryUsecase interface.
type MockSubsidiaryUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSubsidiaryUsecaseMockRecorder
	isgomock struct{}
}

// MockSubsidiaryUsecaseMockRecorder is the mock recorder for MockSubsidiaryUsecase.
type MockSubsidiaryUsecaseMockRecorder struct {
	mock *MockSubsidiaryUsecase
}

// NewMockSubsidiaryUsecase creates a new mock instance.
func NewMockSubsidiaryUsecase(ctrl *gomock.Controller) *MockSubsidiaryUsecase {
	mock := &MockSubsidiaryUsecase{ctrl: ctrl}
	mock.recorder = &MockSubsidiaryUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubsidiaryUsecase) EXPECT() *MockSubsidiaryUsecaseMockRecorder {
	return m.recorder
}

// GetSubsidiaries mocks base method.
func (m *MockSubsidiaryUsecase) GetSubsidiaries(ctx context.Context, symbol string) (*domain.SubsidiaryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubsidiaries", ctx, symbol)
	ret0, _ := ret[0].(*domain.SubsidiaryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubsidiaries indicates an expected call of GetSubsidiaries.
func (mr *MockSubsidiaryUsecaseMockRecorder) GetSubsidiaries(ctx, symbol any) *MockSubsidiaryUsecaseGetSubsidiariesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubsidiaries", reflect.TypeOf((*MockSubsidiaryUsecase)(nil).GetSubsidiaries), ctx, symbol)
	return &MockSubsidiaryUsecaseGetSubsidiariesCall{Call: call}
}

// MockSubsidiaryUsecaseGetSubsidiariesCall wrap *gomock.Call
type MockSubsidiaryUsecaseGetSubsidiariesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubsidiaryUsecaseGetSubsidiariesCall) Return(arg0 *domain.SubsidiaryData, arg1 error) *MockSubsidiaryUsecaseGetSubsidiariesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubsidiaryUsecaseGetSubsidiariesCall) Do(f func(context.Context, string) (*domain.SubsidiaryData, error)) *MockSubsidiaryUsecaseGetSubsidiariesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubsidiaryUsecaseGetSubsidiariesCall) DoAndReturn(f func(context.Context, string) (*domain.SubsidiaryData, error)) *MockSubsidiaryUsecaseGetSubsidiariesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
