// Code generated by MockGen. DO NOT EDIT.
// Source: index.go
//
// Generated by this command:
//
//	mockgen -source=index.go -destination=../mocks/mock_index_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIndexRepository is a mock of IndexRepository interface.
type MockIndexRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIndexRepositoryMockRecorder
	isgomock struct{}
}

// MockIndexRepositoryMockRecorder is the mock recorder for MockIndexRepository.
type MockIndexRepositoryMockRecorder struct {
	mock *MockIndexRepository
}

// NewMockIndexRepository creates a new mock instance.
func NewMockIndexRepository(ctrl *gomock.Controller) *MockIndexRepository {
	mock := &MockIndexRepository{ctrl: ctrl}
	mock.recorder = &MockIndexRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexRepository) EXPECT() *MockIndexRepositoryMockRecorder {
	return m.recorder
}

// GetIndexes mocks base method.
func (m *MockIndexRepository) GetIndexes(ctx context.Context) (*domain.Indexes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexes", ctx)
	ret0, _ := ret[0].(*domain.Indexes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexes indicates an expected call of GetIndexes.
func (mr *MockIndexRepositoryMockRecorder) GetIndexes(ctx any) *MockIndexRepositoryGetIndexesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexes", reflect.TypeOf((*MockIndexRepository)(nil).GetIndexes), ctx)
	return &MockIndexRepositoryGetIndexesCall{Call: call}
}

// MockIndexRepositoryGetIndexesCall wrap *gomock.Call
type MockIndexRepositoryGetIndexesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexRepositoryGetIndexesCall) Return(arg0 *domain.Indexes, arg1 error) *MockIndexRepositoryGetIndexesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexRepositoryGetIndexesCall) Do(f func(context.Context) (*domain.Indexes, error)) *MockIndexRepositoryGetIndexesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexRepositoryGetIndexesCall) DoAndReturn(f func(context.Context) (*domain.Indexes, error)) *MockIndexRepositoryGetIndexesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
