// Code generated by MockGen. DO NOT EDIT.
// Source: chartbit.go
//
// Generated by this command:
//
//	mockgen -source=chartbit.go -destination=../mocks/mock_chartbit_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockChartbitRepository is a mock of ChartbitRepository interface.
type MockChartbitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChartbitRepositoryMockRecorder
	isgomock struct{}
}

// MockChartbitRepositoryMockRecorder is the mock recorder for MockChartbitRepository.
type MockChartbitRepositoryMockRecorder struct {
	mock *MockChartbitRepository
}

// NewMockChartbitRepository creates a new mock instance.
func NewMockChartbitRepository(ctrl *gomock.Controller) *MockChartbitRepository {
	mock := &MockChartbitRepository{ctrl: ctrl}
	mock.recorder = &MockChartbitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChartbitRepository) EXPECT() *MockChartbitRepositoryMockRecorder {
	return m.recorder
}

// GetChartPrice mocks base method.
func (m *MockChartbitRepository) GetChartPrice(ctx context.Context, symbol, timeframe, from, to string, limit int) (*domain.ChartPriceData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChartPrice", ctx, symbol, timeframe, from, to, limit)
	ret0, _ := ret[0].(*domain.ChartPriceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChartPrice indicates an expected call of GetChartPrice.
func (mr *MockChartbitRepositoryMockRecorder) GetChartPrice(ctx, symbol, timeframe, from, to, limit any) *MockChartbitRepositoryGetChartPriceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChartPrice", reflect.TypeOf((*MockChartbitRepository)(nil).GetChartPrice), ctx, symbol, timeframe, from, to, limit)
	return &MockChartbitRepositoryGetChartPriceCall{Call: call}
}

// MockChartbitRepositoryGetChartPriceCall wrap *gomock.Call
type MockChartbitRepositoryGetChartPriceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChartbitRepositoryGetChartPriceCall) Return(arg0 *domain.ChartPriceData, arg1 error) *MockChartbitRepositoryGetChartPriceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChartbitRepositoryGetChartPriceCall) Do(f func(context.Context, string, string, string, string, int) (*domain.ChartPriceData, error)) *MockChartbitRepositoryGetChartPriceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChartbitRepositoryGetChartPriceCall) DoAndReturn(f func(context.Context, string, string, string, string, int) (*domain.ChartPriceData, error)) *MockChartbitRepositoryGetChartPriceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
