// Code generated by MockGen. DO NOT EDIT.
// Source: sectors.go
//
// Generated by this command:
//
//	mockgen -source=sectors.go -destination=../mocks/mock_sectors_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSectorsUsecase is a mock of SectorsUsecase interface.
type MockSectorsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSectorsUsecaseMockRecorder
	isgomock struct{}
}

// MockSectorsUsecaseMockRecorder is the mock recorder for MockSectorsUsecase.
type MockSectorsUsecaseMockRecorder struct {
	mock *MockSectorsUsecase
}

// NewMockSectorsUsecase creates a new mock instance.
func NewMockSectorsUsecase(ctrl *gomock.Controller) *MockSectorsUsecase {
	mock := &MockSectorsUsecase{ctrl: ctrl}
	mock.recorder = &MockSectorsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSectorsUsecase) EXPECT() *MockSectorsUsecaseMockRecorder {
	return m.recorder
}

// GetSectors mocks base method.
func (m *MockSectorsUsecase) GetSectors(ctx context.Context) ([]domain.Sector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSectors", ctx)
	ret0, _ := ret[0].([]domain.Sector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSectors indicates an expected call of GetSectors.
func (mr *MockSectorsUsecaseMockRecorder) GetSectors(ctx any) *MockSectorsUsecaseGetSectorsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSectors", reflect.TypeOf((*MockSectorsUsecase)(nil).GetSectors), ctx)
	return &MockSectorsUsecaseGetSectorsCall{Call: call}
}

// MockSectorsUsecaseGetSectorsCall wrap *gomock.Call
type MockSectorsUsecaseGetSectorsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSectorsUsecaseGetSectorsCall) Return(arg0 []domain.Sector, arg1 error) *MockSectorsUsecaseGetSectorsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSectorsUsecaseGetSectorsCall) Do(f func(context.Context) ([]domain.Sector, error)) *MockSectorsUsecaseGetSectorsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSectorsUsecaseGetSectorsCall) DoAndReturn(f func(context.Context) ([]domain.Sector, error)) *MockSectorsUsecaseGetSectorsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
