// Code generated by MockGen. DO NOT EDIT.
// Source: orderqueue.go
//
// Generated by this command:
//
//	mockgen -source=orderqueue.go -destination=../mocks/mock_orderqueue_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderQueueRepository is a mock of OrderQueueRepository interface.
type MockOrderQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderQueueRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderQueueRepositoryMockRecorder is the mock recorder for MockOrderQueueRepository.
type MockOrderQueueRepositoryMockRecorder struct {
	mock *MockOrderQueueRepository
}

// NewMockOrderQueueRepository creates a new mock instance.
func NewMockOrderQueueRepository(ctrl *gomock.Controller) *MockOrderQueueRepository {
	mock := &MockOrderQueueRepository{ctrl: ctrl}
	mock.recorder = &MockOrderQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderQueueRepository) EXPECT() *MockOrderQueueRepositoryMockRecorder {
	return m.recorder
}

// GetOrderQueue mocks base method.
func (m *MockOrderQueueRepository) GetOrderQueue(ctx context.Context, stockCode, actionType, boardType, orderStatus, sortBy, sortDirection string, limit int, price int64) (*domain.OrderQueueData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderQueue", ctx, stockCode, actionType, boardType, orderStatus, sortBy, sortDirection, limit, price)
	ret0, _ := ret[0].(*domain.OrderQueueData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderQueue indicates an expected call of GetOrderQueue.
func (mr *MockOrderQueueRepositoryMockRecorder) GetOrderQueue(ctx, stockCode, actionType, boardType, orderStatus, sortBy, sortDirection, limit, price any) *MockOrderQueueRepositoryGetOrderQueueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderQueue", reflect.TypeOf((*MockOrderQueueRepository)(nil).GetOrderQueue), ctx, stockCode, actionType, boardType, orderStatus, sortBy, sortDirection, limit, price)
	return &MockOrderQueueRepositoryGetOrderQueueCall{Call: call}
}

// MockOrderQueueRepositoryGetOrderQueueCall wrap *gomock.Call
type MockOrderQueueRepositoryGetOrderQueueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderQueueRepositoryGetOrderQueueCall) Return(arg0 *domain.OrderQueueData, arg1 error) *MockOrderQueueRepositoryGetOrderQueueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderQueueRepositoryGetOrderQueueCall) Do(f func(context.Context, string, string, string, string, string, string, int, int64) (*domain.OrderQueueData, error)) *MockOrderQueueRepositoryGetOrderQueueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderQueueRepositoryGetOrderQueueCall) DoAndReturn(f func(context.Context, string, string, string, string, string, string, int, int64) (*domain.OrderQueueData, error)) *MockOrderQueueRepositoryGetOrderQueueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
