// Code generated by MockGen. DO NOT EDIT.
// Source: fundachart_metrics.go
//
// Generated by this command:
//
//	mockgen -source=fundachart_metrics.go -destination=../mocks/mock_fundachart_metrics_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFundaChartMetricsUsecase is a mock of FundaChartMetricsUsecase interface.
type MockFundaChartMetricsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFundaChartMetricsUsecaseMockRecorder
	isgomock struct{}
}

// MockFundaChartMetricsUsecaseMockRecorder is the mock recorder for MockFundaChartMetricsUsecase.
type MockFundaChartMetricsUsecaseMockRecorder struct {
	mock *MockFundaChartMetricsUsecase
}

// NewMockFundaChartMetricsUsecase creates a new mock instance.
func NewMockFundaChartMetricsUsecase(ctrl *gomock.Controller) *MockFundaChartMetricsUsecase {
	mock := &MockFundaChartMetricsUsecase{ctrl: ctrl}
	mock.recorder = &MockFundaChartMetricsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFundaChartMetricsUsecase) EXPECT() *MockFundaChartMetricsUsecaseMockRecorder {
	return m.recorder
}

// GetFundaChartMetrics mocks base method.
func (m *MockFundaChartMetricsUsecase) GetFundaChartMetrics(ctx context.Context, metricName string) ([]domain.FundaChartMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFundaChartMetrics", ctx, metricName)
	ret0, _ := ret[0].([]domain.FundaChartMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFundaChartMetrics indicates an expected call of GetFundaChartMetrics.
func (mr *MockFundaChartMetricsUsecaseMockRecorder) GetFundaChartMetrics(ctx, metricName any) *MockFundaChartMetricsUsecaseGetFundaChartMetricsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFundaChartMetrics", reflect.TypeOf((*MockFundaChartMetricsUsecase)(nil).GetFundaChartMetrics), ctx, metricName)
	return &MockFundaChartMetricsUsecaseGetFundaChartMetricsCall{Call: call}
}

// MockFundaChartMetricsUsecaseGetFundaChartMetricsCall wrap *gomock.Call
type MockFundaChartMetricsUsecaseGetFundaChartMetricsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFundaChartMetricsUsecaseGetFundaChartMetricsCall) Return(arg0 []domain.FundaChartMetric, arg1 error) *MockFundaChartMetricsUsecaseGetFundaChartMetricsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFundaChartMetricsUsecaseGetFundaChartMetricsCall) Do(f func(context.Context, string) ([]domain.FundaChartMetric, error)) *MockFundaChartMetricsUsecaseGetFundaChartMetricsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFundaChartMetricsUsecaseGetFundaChartMetricsCall) DoAndReturn(f func(context.Context, string) ([]domain.FundaChartMetric, error)) *MockFundaChartMetricsUsecaseGetFundaChartMetricsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
