// Code generated by MockGen. DO NOT EDIT.
// Source: orderbook.go
//
// Generated by this command:
//
//	mockgen -source=orderbook.go -destination=../mocks/mock_orderbook_usecase.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderBookUsecase is a mock of OrderBookUsecase interface.
type MockOrderBookUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockOrderBookUsecaseMockRecorder
	isgomock struct{}
}

// MockOrderBookUsecaseMockRecorder is the mock recorder for MockOrderBookUsecase.
type MockOrderBookUsecaseMockRecorder struct {
	mock *MockOrderBookUsecase
}

// NewMockOrderBookUsecase creates a new mock instance.
func NewMockOrderBookUsecase(ctrl *gomock.Controller) *MockOrderBookUsecase {
	mock := &MockOrderBookUsecase{ctrl: ctrl}
	mock.recorder = &MockOrderBookUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderBookUsecase) EXPECT() *MockOrderBookUsecaseMockRecorder {
	return m.recorder
}

// GetOrderBook mocks base method.
func (m *MockOrderBookUsecase) GetOrderBook(ctx context.Context, symbol string) (*domain.OrderBookData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderBook", ctx, symbol)
	ret0, _ := ret[0].(*domain.OrderBookData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderBook indicates an expected call of GetOrderBook.
func (mr *MockOrderBookUsecaseMockRecorder) GetOrderBook(ctx, symbol any) *MockOrderBookUsecaseGetOrderBookCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderBook", reflect.TypeOf((*MockOrderBookUsecase)(nil).GetOrderBook), ctx, symbol)
	return &MockOrderBookUsecaseGetOrderBookCall{Call: call}
}

// MockOrderBookUsecaseGetOrderBookCall wrap *gomock.Call
type MockOrderBookUsecaseGetOrderBookCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderBookUsecaseGetOrderBookCall) Return(arg0 *domain.OrderBookData, arg1 error) *MockOrderBookUsecaseGetOrderBookCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderBookUsecaseGetOrderBookCall) Do(f func(context.Context, string) (*domain.OrderBookData, error)) *MockOrderBookUsecaseGetOrderBookCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderBookUsecaseGetOrderBookCall) DoAndReturn(f func(context.Context, string) (*domain.OrderBookData, error)) *MockOrderBookUsecaseGetOrderBookCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
