// Code generated by MockGen. DO NOT EDIT.
// Source: shareholding_composition.go
//
// Generated by this command:
//
//	mockgen -source=shareholding_composition.go -destination=../mocks/mock_shareholding_composition_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nofendian17/sbterm/apps/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockShareholdingCompositionRepository is a mock of ShareholdingCompositionRepository interface.
type MockShareholdingCompositionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShareholdingCompositionRepositoryMockRecorder
	isgomock struct{}
}

// MockShareholdingCompositionRepositoryMockRecorder is the mock recorder for MockShareholdingCompositionRepository.
type MockShareholdingCompositionRepositoryMockRecorder struct {
	mock *MockShareholdingCompositionRepository
}

// NewMockShareholdingCompositionRepository creates a new mock instance.
func NewMockShareholdingCompositionRepository(ctrl *gomock.Controller) *MockShareholdingCompositionRepository {
	mock := &MockShareholdingCompositionRepository{ctrl: ctrl}
	mock.recorder = &MockShareholdingCompositionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShareholdingCompositionRepository) EXPECT() *MockShareholdingCompositionRepositoryMockRecorder {
	return m.recorder
}

// GetShareholdingComposition mocks base method.
func (m *MockShareholdingCompositionRepository) GetShareholdingComposition(ctx context.Context, symbol, periodStart, periodEnd string) ([]domain.ShareholdingCompositionPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShareholdingComposition", ctx, symbol, periodStart, periodEnd)
	ret0, _ := ret[0].([]domain.ShareholdingCompositionPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShareholdingComposition indicates an expected call of GetShareholdingComposition.
func (mr *MockShareholdingCompositionRepositoryMockRecorder) GetShareholdingComposition(ctx, symbol, periodStart, periodEnd any) *MockShareholdingCompositionRepositoryGetShareholdingCompositionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShareholdingComposition", reflect.TypeOf((*MockShareholdingCompositionRepository)(nil).GetShareholdingComposition), ctx, symbol, periodStart, periodEnd)
	return &MockShareholdingCompositionRepositoryGetShareholdingCompositionCall{Call: call}
}

// MockShareholdingCompositionRepositoryGetShareholdingCompositionCall wrap *gomock.Call
type MockShareholdingCompositionRepositoryGetShareholdingCompositionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockShareholdingCompositionRepositoryGetShareholdingCompositionCall) Return(arg0 []domain.ShareholdingCompositionPeriod, arg1 error) *MockShareholdingCompositionRepositoryGetShareholdingCompositionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockShareholdingCompositionRepositoryGetShareholdingCompositionCall) Do(f func(context.Context, string, string, string) ([]domain.ShareholdingCompositionPeriod, error)) *MockShareholdingCompositionRepositoryGetShareholdingCompositionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockShareholdingCompositionRepositoryGetShareholdingCompositionCall) DoAndReturn(f func(context.Context, string, string, string) ([]domain.ShareholdingCompositionPeriod, error)) *MockShareholdingCompositionRepositoryGetShareholdingCompositionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
