// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: financial/order_trade/entity/v1/order_trade_entity_v1.proto

// Reconstructed from stockbit.com webpack bundle (chunk 51232-5d0c93927d38e370.js,
// module 228) — protobuf-es message definitions. NOT an official schema.
// Datafeed websocket — koneksi wss://wssfeed.stockbit.com/?wskey=<key>.

package ordertradev1

import (
	v1 "github.com/nofendian17/sbterm-server/internal/infrastructure/stockbit/proto/financial/emitten/entity/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoverType int32

const (
	MoverType_MOVER_TYPE_UNSPECIFIED                MoverType = 0
	MoverType_MOVER_TYPE_TOP_VALUE                  MoverType = 1
	MoverType_MOVER_TYPE_TOP_VOLUME                 MoverType = 2
	MoverType_MOVER_TYPE_TOP_FREQUENCY              MoverType = 3
	MoverType_MOVER_TYPE_TOP_GAINER                 MoverType = 4
	MoverType_MOVER_TYPE_TOP_LOSER                  MoverType = 5
	MoverType_MOVER_TYPE_NET_FOREIGN_BUY            MoverType = 6
	MoverType_MOVER_TYPE_NET_FOREIGN_SELL           MoverType = 7
	MoverType_MOVER_TYPE_IEP_CURRENT_TOP_GAINER     MoverType = 8
	MoverType_MOVER_TYPE_IEP_CURRENT_TOP_LOSER      MoverType = 9
	MoverType_MOVER_TYPE_IEV_TOP_GAINER             MoverType = 10
	MoverType_MOVER_TYPE_IEV_TOP_LOSER              MoverType = 11
	MoverType_MOVER_TYPE_IEVAL_TOP_GAINER           MoverType = 12
	MoverType_MOVER_TYPE_IEVAL_TOP_LOSER            MoverType = 13
	MoverType_MOVER_TYPE_IEP_PREV_TOP_GAINER        MoverType = 14
	MoverType_MOVER_TYPE_IEP_PREV_TOP_LOSER         MoverType = 15
	MoverType_MOVER_TYPE_BIG_MONEY_NET_VALUE        MoverType = 16
	MoverType_MOVER_TYPE_CATALOG                    MoverType = 17
	MoverType_MOVER_TYPE_BIG_MONEY_NET_SELL         MoverType = 18
	MoverType_MOVER_TYPE_CATALOG_KONGLO_MCAP_CHANGE MoverType = 19
)

// Enum value maps for MoverType.
var (
	MoverType_name = map[int32]string{
		0:  "MOVER_TYPE_UNSPECIFIED",
		1:  "MOVER_TYPE_TOP_VALUE",
		2:  "MOVER_TYPE_TOP_VOLUME",
		3:  "MOVER_TYPE_TOP_FREQUENCY",
		4:  "MOVER_TYPE_TOP_GAINER",
		5:  "MOVER_TYPE_TOP_LOSER",
		6:  "MOVER_TYPE_NET_FOREIGN_BUY",
		7:  "MOVER_TYPE_NET_FOREIGN_SELL",
		8:  "MOVER_TYPE_IEP_CURRENT_TOP_GAINER",
		9:  "MOVER_TYPE_IEP_CURRENT_TOP_LOSER",
		10: "MOVER_TYPE_IEV_TOP_GAINER",
		11: "MOVER_TYPE_IEV_TOP_LOSER",
		12: "MOVER_TYPE_IEVAL_TOP_GAINER",
		13: "MOVER_TYPE_IEVAL_TOP_LOSER",
		14: "MOVER_TYPE_IEP_PREV_TOP_GAINER",
		15: "MOVER_TYPE_IEP_PREV_TOP_LOSER",
		16: "MOVER_TYPE_BIG_MONEY_NET_VALUE",
		17: "MOVER_TYPE_CATALOG",
		18: "MOVER_TYPE_BIG_MONEY_NET_SELL",
		19: "MOVER_TYPE_CATALOG_KONGLO_MCAP_CHANGE",
	}
	MoverType_value = map[string]int32{
		"MOVER_TYPE_UNSPECIFIED":                0,
		"MOVER_TYPE_TOP_VALUE":                  1,
		"MOVER_TYPE_TOP_VOLUME":                 2,
		"MOVER_TYPE_TOP_FREQUENCY":              3,
		"MOVER_TYPE_TOP_GAINER":                 4,
		"MOVER_TYPE_TOP_LOSER":                  5,
		"MOVER_TYPE_NET_FOREIGN_BUY":            6,
		"MOVER_TYPE_NET_FOREIGN_SELL":           7,
		"MOVER_TYPE_IEP_CURRENT_TOP_GAINER":     8,
		"MOVER_TYPE_IEP_CURRENT_TOP_LOSER":      9,
		"MOVER_TYPE_IEV_TOP_GAINER":             10,
		"MOVER_TYPE_IEV_TOP_LOSER":              11,
		"MOVER_TYPE_IEVAL_TOP_GAINER":           12,
		"MOVER_TYPE_IEVAL_TOP_LOSER":            13,
		"MOVER_TYPE_IEP_PREV_TOP_GAINER":        14,
		"MOVER_TYPE_IEP_PREV_TOP_LOSER":         15,
		"MOVER_TYPE_BIG_MONEY_NET_VALUE":        16,
		"MOVER_TYPE_CATALOG":                    17,
		"MOVER_TYPE_BIG_MONEY_NET_SELL":         18,
		"MOVER_TYPE_CATALOG_KONGLO_MCAP_CHANGE": 19,
	}
)

func (x MoverType) Enum() *MoverType {
	p := new(MoverType)
	*p = x
	return p
}

func (x MoverType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoverType) Descriptor() protoreflect.EnumDescriptor {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes[0].Descriptor()
}

func (MoverType) Type() protoreflect.EnumType {
	return &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes[0]
}

func (x MoverType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoverType.Descriptor instead.
func (MoverType) EnumDescriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{0}
}

type FilterStocksType int32

const (
	FilterStocksType_FILTER_STOCKS_TYPE_UNSPECIFIED              FilterStocksType = 0
	FilterStocksType_FILTER_STOCKS_TYPE_MAIN_BOARD               FilterStocksType = 1
	FilterStocksType_FILTER_STOCKS_TYPE_DEVELOPMENT_BOARD        FilterStocksType = 2
	FilterStocksType_FILTER_STOCKS_TYPE_ACCELERATION_BOARD       FilterStocksType = 3
	FilterStocksType_FILTER_STOCKS_TYPE_NEW_ECONOMY_BOARD        FilterStocksType = 4
	FilterStocksType_FILTER_STOCKS_TYPE_SPECIAL_MONITORING_BOARD FilterStocksType = 5
	FilterStocksType_FILTER_STOCKS_TYPE_WARRANT_AND_RIGHT        FilterStocksType = 6
	FilterStocksType_FILTER_STOCKS_TYPE_SHARIA                   FilterStocksType = 7
)

// Enum value maps for FilterStocksType.
var (
	FilterStocksType_name = map[int32]string{
		0: "FILTER_STOCKS_TYPE_UNSPECIFIED",
		1: "FILTER_STOCKS_TYPE_MAIN_BOARD",
		2: "FILTER_STOCKS_TYPE_DEVELOPMENT_BOARD",
		3: "FILTER_STOCKS_TYPE_ACCELERATION_BOARD",
		4: "FILTER_STOCKS_TYPE_NEW_ECONOMY_BOARD",
		5: "FILTER_STOCKS_TYPE_SPECIAL_MONITORING_BOARD",
		6: "FILTER_STOCKS_TYPE_WARRANT_AND_RIGHT",
		7: "FILTER_STOCKS_TYPE_SHARIA",
	}
	FilterStocksType_value = map[string]int32{
		"FILTER_STOCKS_TYPE_UNSPECIFIED":              0,
		"FILTER_STOCKS_TYPE_MAIN_BOARD":               1,
		"FILTER_STOCKS_TYPE_DEVELOPMENT_BOARD":        2,
		"FILTER_STOCKS_TYPE_ACCELERATION_BOARD":       3,
		"FILTER_STOCKS_TYPE_NEW_ECONOMY_BOARD":        4,
		"FILTER_STOCKS_TYPE_SPECIAL_MONITORING_BOARD": 5,
		"FILTER_STOCKS_TYPE_WARRANT_AND_RIGHT":        6,
		"FILTER_STOCKS_TYPE_SHARIA":                   7,
	}
)

func (x FilterStocksType) Enum() *FilterStocksType {
	p := new(FilterStocksType)
	*p = x
	return p
}

func (x FilterStocksType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterStocksType) Descriptor() protoreflect.EnumDescriptor {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes[1].Descriptor()
}

func (FilterStocksType) Type() protoreflect.EnumType {
	return &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes[1]
}

func (x FilterStocksType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterStocksType.Descriptor instead.
func (FilterStocksType) EnumDescriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{1}
}

type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_ACTION_TYPE_BUY         ActionType = 1
	ActionType_ACTION_TYPE_SELL        ActionType = 2
	ActionType_ACTION_TYPE_ALL         ActionType = 3
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_BUY",
		2: "ACTION_TYPE_SELL",
		3: "ACTION_TYPE_ALL",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"ACTION_TYPE_BUY":         1,
		"ACTION_TYPE_SELL":        2,
		"ACTION_TYPE_ALL":         3,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes[2].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes[2]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{2}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED   OrderStatus = 0
	OrderStatus_ORDER_STATUS_OPEN          OrderStatus = 1
	OrderStatus_ORDER_STATUS_FULL_MATCH    OrderStatus = 2
	OrderStatus_ORDER_STATUS_WITHDRAWN     OrderStatus = 3
	OrderStatus_ORDER_STATUS_PARTIAL_MATCH OrderStatus = 4
	OrderStatus_ORDER_STATUS_AMEND         OrderStatus = 5
	OrderStatus_ORDER_STATUS_ALL           OrderStatus = 6
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_OPEN",
		2: "ORDER_STATUS_FULL_MATCH",
		3: "ORDER_STATUS_WITHDRAWN",
		4: "ORDER_STATUS_PARTIAL_MATCH",
		5: "ORDER_STATUS_AMEND",
		6: "ORDER_STATUS_ALL",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":   0,
		"ORDER_STATUS_OPEN":          1,
		"ORDER_STATUS_FULL_MATCH":    2,
		"ORDER_STATUS_WITHDRAWN":     3,
		"ORDER_STATUS_PARTIAL_MATCH": 4,
		"ORDER_STATUS_AMEND":         5,
		"ORDER_STATUS_ALL":           6,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes[3].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes[3]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{3}
}

type BoardType int32

const (
	BoardType_BOARD_TYPE_UNSPECIFIED BoardType = 0
	BoardType_BOARD_TYPE_REGULAR     BoardType = 1
	BoardType_BOARD_TYPE_NEGOTIATION BoardType = 2
	BoardType_BOARD_TYPE_CASH        BoardType = 3
	BoardType_BOARD_TYPE_ALL         BoardType = 4
)

// Enum value maps for BoardType.
var (
	BoardType_name = map[int32]string{
		0: "BOARD_TYPE_UNSPECIFIED",
		1: "BOARD_TYPE_REGULAR",
		2: "BOARD_TYPE_NEGOTIATION",
		3: "BOARD_TYPE_CASH",
		4: "BOARD_TYPE_ALL",
	}
	BoardType_value = map[string]int32{
		"BOARD_TYPE_UNSPECIFIED": 0,
		"BOARD_TYPE_REGULAR":     1,
		"BOARD_TYPE_NEGOTIATION": 2,
		"BOARD_TYPE_CASH":        3,
		"BOARD_TYPE_ALL":         4,
	}
)

func (x BoardType) Enum() *BoardType {
	p := new(BoardType)
	*p = x
	return p
}

func (x BoardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoardType) Descriptor() protoreflect.EnumDescriptor {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes[4].Descriptor()
}

func (BoardType) Type() protoreflect.EnumType {
	return &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes[4]
}

func (x BoardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoardType.Descriptor instead.
func (BoardType) EnumDescriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{4}
}

type MarketMover struct {
	state                       protoimpl.MessageState     `protogen:"open.v1"`
	StockDetail                 *MarketMover_StockDetail   `protobuf:"bytes,1,opt,name=stock_detail,json=stockDetail,proto3" json:"stock_detail,omitempty"`
	Price                       float64                    `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"` // T:1
	Change                      *Change                    `protobuf:"bytes,3,opt,name=change,proto3" json:"change,omitempty"`
	Value                       *MoverValue                `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Volume                      *MoverValue                `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Frequency                   *MoverValue                `protobuf:"bytes,6,opt,name=frequency,proto3" json:"frequency,omitempty"`
	NetForeignBuy               *MoverValue                `protobuf:"bytes,7,opt,name=net_foreign_buy,json=netForeignBuy,proto3" json:"net_foreign_buy,omitempty"`
	NetForeignSell              *MoverValue                `protobuf:"bytes,8,opt,name=net_foreign_sell,json=netForeignSell,proto3" json:"net_foreign_sell,omitempty"`
	NetBuy                      *MoverValue                `protobuf:"bytes,9,opt,name=net_buy,json=netBuy,proto3" json:"net_buy,omitempty"`
	NetSell                     *MoverValue                `protobuf:"bytes,10,opt,name=net_sell,json=netSell,proto3" json:"net_sell,omitempty"`
	IepievDetail                *MarketMover_IEPIEVDetail  `protobuf:"bytes,11,opt,name=iepiev_detail,json=iepievDetail,proto3" json:"iepiev_detail,omitempty"`
	BigMoneyNetValue            *MoverValue                `protobuf:"bytes,12,opt,name=big_money_net_value,json=bigMoneyNetValue,proto3" json:"big_money_net_value,omitempty"`
	BuyValuePercentage          float64                    `protobuf:"fixed64,13,opt,name=buy_value_percentage,json=buyValuePercentage,proto3" json:"buy_value_percentage,omitempty"`                                // T:1
	SellValuePercentage         float64                    `protobuf:"fixed64,14,opt,name=sell_value_percentage,json=sellValuePercentage,proto3" json:"sell_value_percentage,omitempty"`                             // T:1
	BigMoneyBuyValuePercentage  float64                    `protobuf:"fixed64,15,opt,name=big_money_buy_value_percentage,json=bigMoneyBuyValuePercentage,proto3" json:"big_money_buy_value_percentage,omitempty"`    // T:1
	BigMoneySellValuePercentage float64                    `protobuf:"fixed64,16,opt,name=big_money_sell_value_percentage,json=bigMoneySellValuePercentage,proto3" json:"big_money_sell_value_percentage,omitempty"` // T:1
	BidPercent                  float64                    `protobuf:"fixed64,17,opt,name=bid_percent,json=bidPercent,proto3" json:"bid_percent,omitempty"`                                                          // T:1
	CatalogDetail               *MarketMover_CatalogDetail `protobuf:"bytes,18,opt,name=catalog_detail,json=catalogDetail,proto3" json:"catalog_detail,omitempty"`
	MarketCap                   *MarketCapInfo             `protobuf:"bytes,19,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *MarketMover) Reset() {
	*x = MarketMover{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketMover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketMover) ProtoMessage() {}

func (x *MarketMover) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketMover.ProtoReflect.Descriptor instead.
func (*MarketMover) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{0}
}

func (x *MarketMover) GetStockDetail() *MarketMover_StockDetail {
	if x != nil {
		return x.StockDetail
	}
	return nil
}

func (x *MarketMover) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketMover) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *MarketMover) GetValue() *MoverValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MarketMover) GetVolume() *MoverValue {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *MarketMover) GetFrequency() *MoverValue {
	if x != nil {
		return x.Frequency
	}
	return nil
}

func (x *MarketMover) GetNetForeignBuy() *MoverValue {
	if x != nil {
		return x.NetForeignBuy
	}
	return nil
}

func (x *MarketMover) GetNetForeignSell() *MoverValue {
	if x != nil {
		return x.NetForeignSell
	}
	return nil
}

func (x *MarketMover) GetNetBuy() *MoverValue {
	if x != nil {
		return x.NetBuy
	}
	return nil
}

func (x *MarketMover) GetNetSell() *MoverValue {
	if x != nil {
		return x.NetSell
	}
	return nil
}

func (x *MarketMover) GetIepievDetail() *MarketMover_IEPIEVDetail {
	if x != nil {
		return x.IepievDetail
	}
	return nil
}

func (x *MarketMover) GetBigMoneyNetValue() *MoverValue {
	if x != nil {
		return x.BigMoneyNetValue
	}
	return nil
}

func (x *MarketMover) GetBuyValuePercentage() float64 {
	if x != nil {
		return x.BuyValuePercentage
	}
	return 0
}

func (x *MarketMover) GetSellValuePercentage() float64 {
	if x != nil {
		return x.SellValuePercentage
	}
	return 0
}

func (x *MarketMover) GetBigMoneyBuyValuePercentage() float64 {
	if x != nil {
		return x.BigMoneyBuyValuePercentage
	}
	return 0
}

func (x *MarketMover) GetBigMoneySellValuePercentage() float64 {
	if x != nil {
		return x.BigMoneySellValuePercentage
	}
	return 0
}

func (x *MarketMover) GetBidPercent() float64 {
	if x != nil {
		return x.BidPercent
	}
	return 0
}

func (x *MarketMover) GetCatalogDetail() *MarketMover_CatalogDetail {
	if x != nil {
		return x.CatalogDetail
	}
	return nil
}

func (x *MarketMover) GetMarketCap() *MarketCapInfo {
	if x != nil {
		return x.MarketCap
	}
	return nil
}

type MarketMoverBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         []*MarketMover         `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
	MoverType     MoverType              `protobuf:"varint,2,opt,name=mover_type,json=moverType,proto3,enum=financial.order_trade.entity.v1.MoverType" json:"mover_type,omitempty"`
	FilterStocks  []FilterStocksType     `protobuf:"varint,3,rep,packed,name=filter_stocks,json=filterStocks,proto3,enum=financial.order_trade.entity.v1.FilterStocksType" json:"filter_stocks,omitempty"`
	CatalogType   v1.CatalogType         `protobuf:"varint,4,opt,name=catalog_type,json=catalogType,proto3,enum=financial.emitten.entity.v1.CatalogType" json:"catalog_type,omitempty"`
	CatalogId     int64                  `protobuf:"varint,5,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"` // T:3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketMoverBatch) Reset() {
	*x = MarketMoverBatch{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketMoverBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketMoverBatch) ProtoMessage() {}

func (x *MarketMoverBatch) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketMoverBatch.ProtoReflect.Descriptor instead.
func (*MarketMoverBatch) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{1}
}

func (x *MarketMoverBatch) GetBatch() []*MarketMover {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *MarketMoverBatch) GetMoverType() MoverType {
	if x != nil {
		return x.MoverType
	}
	return MoverType_MOVER_TYPE_UNSPECIFIED
}

func (x *MarketMoverBatch) GetFilterStocks() []FilterStocksType {
	if x != nil {
		return x.FilterStocks
	}
	return nil
}

func (x *MarketMoverBatch) GetCatalogType() v1.CatalogType {
	if x != nil {
		return x.CatalogType
	}
	return v1.CatalogType(0)
}

func (x *MarketMoverBatch) GetCatalogId() int64 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`           // T:1
	Percentage    float64                `protobuf:"fixed64,2,opt,name=percentage,proto3" json:"percentage,omitempty"` // T:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Change) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Change) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type MoverValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           float64                `protobuf:"fixed64,1,opt,name=raw,proto3" json:"raw,omitempty"`           // T:1
	Formatted     string                 `protobuf:"bytes,2,opt,name=formatted,proto3" json:"formatted,omitempty"` // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoverValue) Reset() {
	*x = MoverValue{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoverValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverValue) ProtoMessage() {}

func (x *MoverValue) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverValue.ProtoReflect.Descriptor instead.
func (*MoverValue) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{3}
}

func (x *MoverValue) GetRaw() float64 {
	if x != nil {
		return x.Raw
	}
	return 0
}

func (x *MoverValue) GetFormatted() string {
	if x != nil {
		return x.Formatted
	}
	return ""
}

type MarketMoverWebsocketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MoverType     MoverType              `protobuf:"varint,1,opt,name=mover_type,json=moverType,proto3,enum=financial.order_trade.entity.v1.MoverType" json:"mover_type,omitempty"`
	FilterStocks  []FilterStocksType     `protobuf:"varint,2,rep,packed,name=filter_stocks,json=filterStocks,proto3,enum=financial.order_trade.entity.v1.FilterStocksType" json:"filter_stocks,omitempty"`
	CatalogType   v1.CatalogType         `protobuf:"varint,3,opt,name=catalog_type,json=catalogType,proto3,enum=financial.emitten.entity.v1.CatalogType" json:"catalog_type,omitempty"`
	CatalogId     int64                  `protobuf:"varint,4,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"` // T:3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketMoverWebsocketRequest) Reset() {
	*x = MarketMoverWebsocketRequest{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketMoverWebsocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketMoverWebsocketRequest) ProtoMessage() {}

func (x *MarketMoverWebsocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketMoverWebsocketRequest.ProtoReflect.Descriptor instead.
func (*MarketMoverWebsocketRequest) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{4}
}

func (x *MarketMoverWebsocketRequest) GetMoverType() MoverType {
	if x != nil {
		return x.MoverType
	}
	return MoverType_MOVER_TYPE_UNSPECIFIED
}

func (x *MarketMoverWebsocketRequest) GetFilterStocks() []FilterStocksType {
	if x != nil {
		return x.FilterStocks
	}
	return nil
}

func (x *MarketMoverWebsocketRequest) GetCatalogType() v1.CatalogType {
	if x != nil {
		return x.CatalogType
	}
	return v1.CatalogType(0)
}

func (x *MarketMoverWebsocketRequest) GetCatalogId() int64 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

type MarketCapInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       *MoverValue            `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	Previous      *MoverValue            `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"`
	Change        *MoverValue            `protobuf:"bytes,3,opt,name=change,proto3" json:"change,omitempty"`
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"` // T:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketCapInfo) Reset() {
	*x = MarketCapInfo{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketCapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketCapInfo) ProtoMessage() {}

func (x *MarketCapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketCapInfo.ProtoReflect.Descriptor instead.
func (*MarketCapInfo) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{5}
}

func (x *MarketCapInfo) GetCurrent() *MoverValue {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *MarketCapInfo) GetPrevious() *MoverValue {
	if x != nil {
		return x.Previous
	}
	return nil
}

func (x *MarketCapInfo) GetChange() *MoverValue {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *MarketCapInfo) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type TradebookWSMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`       // T:9
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // T:9
	BigMoney      *MarketMover           `protobuf:"bytes,3,opt,name=big_money,json=bigMoney,proto3" json:"big_money,omitempty"`
	Board         string                 `protobuf:"bytes,4,opt,name=board,proto3" json:"board,omitempty"`                               // T:9
	BidPercent    float64                `protobuf:"fixed64,5,opt,name=bid_percent,json=bidPercent,proto3" json:"bid_percent,omitempty"` // T:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradebookWSMessage) Reset() {
	*x = TradebookWSMessage{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradebookWSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradebookWSMessage) ProtoMessage() {}

func (x *TradebookWSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradebookWSMessage.ProtoReflect.Descriptor instead.
func (*TradebookWSMessage) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{6}
}

func (x *TradebookWSMessage) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TradebookWSMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TradebookWSMessage) GetBigMoney() *MarketMover {
	if x != nil {
		return x.BigMoney
	}
	return nil
}

func (x *TradebookWSMessage) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *TradebookWSMessage) GetBidPercent() float64 {
	if x != nil {
		return x.BidPercent
	}
	return 0
}

type TradebookWebsocketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // T:9 // jsonName: stock_code
	Board         string                 `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`   // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradebookWebsocketRequest) Reset() {
	*x = TradebookWebsocketRequest{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradebookWebsocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradebookWebsocketRequest) ProtoMessage() {}

func (x *TradebookWebsocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradebookWebsocketRequest.ProtoReflect.Descriptor instead.
func (*TradebookWebsocketRequest) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{7}
}

func (x *TradebookWebsocketRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TradebookWebsocketRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Full          int64                  `protobuf:"varint,1,opt,name=full,proto3" json:"full,omitempty"`          // T:3
	Formatted     string                 `protobuf:"bytes,2,opt,name=formatted,proto3" json:"formatted,omitempty"` // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{8}
}

func (x *Order) GetFull() int64 {
	if x != nil {
		return x.Full
	}
	return 0
}

func (x *Order) GetFormatted() string {
	if x != nil {
		return x.Formatted
	}
	return ""
}

type OrderQueueWebsocketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockCode     string                 `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"` // T:9
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`                        // T:2
	BoardType     BoardType              `protobuf:"varint,3,opt,name=board_type,json=boardType,proto3,enum=financial.order_trade.entity.v1.BoardType" json:"board_type,omitempty"`
	ActionType    ActionType             `protobuf:"varint,4,opt,name=action_type,json=actionType,proto3,enum=financial.order_trade.entity.v1.ActionType" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderQueueWebsocketRequest) Reset() {
	*x = OrderQueueWebsocketRequest{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQueueWebsocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQueueWebsocketRequest) ProtoMessage() {}

func (x *OrderQueueWebsocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQueueWebsocketRequest.ProtoReflect.Descriptor instead.
func (*OrderQueueWebsocketRequest) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{9}
}

func (x *OrderQueueWebsocketRequest) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *OrderQueueWebsocketRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderQueueWebsocketRequest) GetBoardType() BoardType {
	if x != nil {
		return x.BoardType
	}
	return BoardType_BOARD_TYPE_UNSPECIFIED
}

func (x *OrderQueueWebsocketRequest) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

type OrderQueueWebsocket struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*OrderQueueWebsocketData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderQueueWebsocket) Reset() {
	*x = OrderQueueWebsocket{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQueueWebsocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQueueWebsocket) ProtoMessage() {}

func (x *OrderQueueWebsocket) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQueueWebsocket.ProtoReflect.Descriptor instead.
func (*OrderQueueWebsocket) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{10}
}

func (x *OrderQueueWebsocket) GetData() []*OrderQueueWebsocketData {
	if x != nil {
		return x.Data
	}
	return nil
}

type OrderQueueWebsocketData struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	StockCode           string                     `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"` // T:9
	Time                string                     `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`                            // T:9
	ActionType          ActionType                 `protobuf:"varint,3,opt,name=action_type,json=actionType,proto3,enum=financial.order_trade.entity.v1.ActionType" json:"action_type,omitempty"`
	Price               float32                    `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"` // T:2
	Status              OrderStatus                `protobuf:"varint,5,opt,name=status,proto3,enum=financial.order_trade.entity.v1.OrderStatus" json:"status,omitempty"`
	Open                float32                    `protobuf:"fixed32,6,opt,name=open,proto3" json:"open,omitempty"` // T:2
	Lot                 float32                    `protobuf:"fixed32,7,opt,name=lot,proto3" json:"lot,omitempty"`   // T:2
	BoardType           BoardType                  `protobuf:"varint,8,opt,name=board_type,json=boardType,proto3,enum=financial.order_trade.entity.v1.BoardType" json:"board_type,omitempty"`
	ExchangeOrderNumber *Order_ExchangeOrderNumber `protobuf:"bytes,9,opt,name=exchange_order_number,json=exchangeOrderNumber,proto3" json:"exchange_order_number,omitempty"`
	OrderNumber         int64                      `protobuf:"varint,10,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`                         // T:3
	OpenChangeQuantity  float32                    `protobuf:"fixed32,11,opt,name=open_change_quantity,json=openChangeQuantity,proto3" json:"open_change_quantity,omitempty"` // T:2
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrderQueueWebsocketData) Reset() {
	*x = OrderQueueWebsocketData{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQueueWebsocketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQueueWebsocketData) ProtoMessage() {}

func (x *OrderQueueWebsocketData) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQueueWebsocketData.ProtoReflect.Descriptor instead.
func (*OrderQueueWebsocketData) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{11}
}

func (x *OrderQueueWebsocketData) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *OrderQueueWebsocketData) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *OrderQueueWebsocketData) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *OrderQueueWebsocketData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderQueueWebsocketData) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderQueueWebsocketData) GetOpen() float32 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *OrderQueueWebsocketData) GetLot() float32 {
	if x != nil {
		return x.Lot
	}
	return 0
}

func (x *OrderQueueWebsocketData) GetBoardType() BoardType {
	if x != nil {
		return x.BoardType
	}
	return BoardType_BOARD_TYPE_UNSPECIFIED
}

func (x *OrderQueueWebsocketData) GetExchangeOrderNumber() *Order_ExchangeOrderNumber {
	if x != nil {
		return x.ExchangeOrderNumber
	}
	return nil
}

func (x *OrderQueueWebsocketData) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *OrderQueueWebsocketData) GetOpenChangeQuantity() float32 {
	if x != nil {
		return x.OpenChangeQuantity
	}
	return 0
}

type MarketMover_NotationDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`               // T:9
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketMover_NotationDetail) Reset() {
	*x = MarketMover_NotationDetail{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketMover_NotationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketMover_NotationDetail) ProtoMessage() {}

func (x *MarketMover_NotationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketMover_NotationDetail.ProtoReflect.Descriptor instead.
func (*MarketMover_NotationDetail) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MarketMover_NotationDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MarketMover_NotationDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type MarketMover_CorpactionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`                 // T:8
	IconUrl       string                 `protobuf:"bytes,2,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"` // T:9
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`                      // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketMover_CorpactionDetail) Reset() {
	*x = MarketMover_CorpactionDetail{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketMover_CorpactionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketMover_CorpactionDetail) ProtoMessage() {}

func (x *MarketMover_CorpactionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketMover_CorpactionDetail.ProtoReflect.Descriptor instead.
func (*MarketMover_CorpactionDetail) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MarketMover_CorpactionDetail) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *MarketMover_CorpactionDetail) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *MarketMover_CorpactionDetail) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MarketMover_StockDetail struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Code          string                        `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                      // T:9
	Name          string                        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                      // T:9
	IconUrl       string                        `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"` // T:9
	HasUma        bool                          `protobuf:"varint,4,opt,name=has_uma,json=hasUma,proto3" json:"has_uma,omitempty"`   // T:8
	Notations     []*MarketMover_NotationDetail `protobuf:"bytes,5,rep,name=notations,proto3" json:"notations,omitempty"`
	Corpaction    *MarketMover_CorpactionDetail `protobuf:"bytes,6,opt,name=corpaction,proto3" json:"corpaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketMover_StockDetail) Reset() {
	*x = MarketMover_StockDetail{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketMover_StockDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketMover_StockDetail) ProtoMessage() {}

func (x *MarketMover_StockDetail) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketMover_StockDetail.ProtoReflect.Descriptor instead.
func (*MarketMover_StockDetail) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{0, 2}
}

func (x *MarketMover_StockDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MarketMover_StockDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketMover_StockDetail) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *MarketMover_StockDetail) GetHasUma() bool {
	if x != nil {
		return x.HasUma
	}
	return false
}

func (x *MarketMover_StockDetail) GetNotations() []*MarketMover_NotationDetail {
	if x != nil {
		return x.Notations
	}
	return nil
}

func (x *MarketMover_StockDetail) GetCorpaction() *MarketMover_CorpactionDetail {
	if x != nil {
		return x.Corpaction
	}
	return nil
}

type MarketMover_IEPIEVDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Iep              *MoverValue            `protobuf:"bytes,1,opt,name=iep,proto3" json:"iep,omitempty"`
	Iev              *MoverValue            `protobuf:"bytes,2,opt,name=iev,proto3" json:"iev,omitempty"`
	Ieval            *MoverValue            `protobuf:"bytes,3,opt,name=ieval,proto3" json:"ieval,omitempty"`
	IepChange        *MoverValue            `protobuf:"bytes,4,opt,name=iep_change,json=iepChange,proto3" json:"iep_change,omitempty"`
	IepChangePrev    *MoverValue            `protobuf:"bytes,5,opt,name=iep_change_prev,json=iepChangePrev,proto3" json:"iep_change_prev,omitempty"`
	IepPriceDiff     *MoverValue            `protobuf:"bytes,6,opt,name=iep_price_diff,json=iepPriceDiff,proto3" json:"iep_price_diff,omitempty"`
	IepPrevPriceDiff *MoverValue            `protobuf:"bytes,7,opt,name=iep_prev_price_diff,json=iepPrevPriceDiff,proto3" json:"iep_prev_price_diff,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MarketMover_IEPIEVDetail) Reset() {
	*x = MarketMover_IEPIEVDetail{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketMover_IEPIEVDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketMover_IEPIEVDetail) ProtoMessage() {}

func (x *MarketMover_IEPIEVDetail) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketMover_IEPIEVDetail.ProtoReflect.Descriptor instead.
func (*MarketMover_IEPIEVDetail) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{0, 3}
}

func (x *MarketMover_IEPIEVDetail) GetIep() *MoverValue {
	if x != nil {
		return x.Iep
	}
	return nil
}

func (x *MarketMover_IEPIEVDetail) GetIev() *MoverValue {
	if x != nil {
		return x.Iev
	}
	return nil
}

func (x *MarketMover_IEPIEVDetail) GetIeval() *MoverValue {
	if x != nil {
		return x.Ieval
	}
	return nil
}

func (x *MarketMover_IEPIEVDetail) GetIepChange() *MoverValue {
	if x != nil {
		return x.IepChange
	}
	return nil
}

func (x *MarketMover_IEPIEVDetail) GetIepChangePrev() *MoverValue {
	if x != nil {
		return x.IepChangePrev
	}
	return nil
}

func (x *MarketMover_IEPIEVDetail) GetIepPriceDiff() *MoverValue {
	if x != nil {
		return x.IepPriceDiff
	}
	return nil
}

func (x *MarketMover_IEPIEVDetail) GetIepPrevPriceDiff() *MoverValue {
	if x != nil {
		return x.IepPrevPriceDiff
	}
	return nil
}

type MarketMover_CatalogDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                            // T:9
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                            // T:9
	IconUrl        string                 `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`                       // T:9
	UpCount        int32                  `protobuf:"varint,4,opt,name=up_count,json=upCount,proto3" json:"up_count,omitempty"`                      // T:5
	DownCount      int32                  `protobuf:"varint,5,opt,name=down_count,json=downCount,proto3" json:"down_count,omitempty"`                // T:5
	UnchangedCount int32                  `protobuf:"varint,6,opt,name=unchanged_count,json=unchangedCount,proto3" json:"unchanged_count,omitempty"` // T:5
	StockCount     int32                  `protobuf:"varint,7,opt,name=stock_count,json=stockCount,proto3" json:"stock_count,omitempty"`             // T:5
	CatalogId      int64                  `protobuf:"varint,8,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`                // T:3
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarketMover_CatalogDetail) Reset() {
	*x = MarketMover_CatalogDetail{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketMover_CatalogDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketMover_CatalogDetail) ProtoMessage() {}

func (x *MarketMover_CatalogDetail) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketMover_CatalogDetail.ProtoReflect.Descriptor instead.
func (*MarketMover_CatalogDetail) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{0, 4}
}

func (x *MarketMover_CatalogDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MarketMover_CatalogDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketMover_CatalogDetail) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *MarketMover_CatalogDetail) GetUpCount() int32 {
	if x != nil {
		return x.UpCount
	}
	return 0
}

func (x *MarketMover_CatalogDetail) GetDownCount() int32 {
	if x != nil {
		return x.DownCount
	}
	return 0
}

func (x *MarketMover_CatalogDetail) GetUnchangedCount() int32 {
	if x != nil {
		return x.UnchangedCount
	}
	return 0
}

func (x *MarketMover_CatalogDetail) GetStockCount() int32 {
	if x != nil {
		return x.StockCount
	}
	return 0
}

func (x *MarketMover_CatalogDetail) GetCatalogId() int64 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

type Order_ExchangeOrderNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Full          int64                  `protobuf:"varint,1,opt,name=full,proto3" json:"full,omitempty"`          // T:3
	Formatted     string                 `protobuf:"bytes,2,opt,name=formatted,proto3" json:"formatted,omitempty"` // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order_ExchangeOrderNumber) Reset() {
	*x = Order_ExchangeOrderNumber{}
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order_ExchangeOrderNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_ExchangeOrderNumber) ProtoMessage() {}

func (x *Order_ExchangeOrderNumber) ProtoReflect() protoreflect.Message {
	mi := &file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_ExchangeOrderNumber.ProtoReflect.Descriptor instead.
func (*Order_ExchangeOrderNumber) Descriptor() ([]byte, []int) {
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Order_ExchangeOrderNumber) GetFull() int64 {
	if x != nil {
		return x.Full
	}
	return 0
}

func (x *Order_ExchangeOrderNumber) GetFormatted() string {
	if x != nil {
		return x.Formatted
	}
	return ""
}

var File_financial_order_trade_entity_v1_order_trade_entity_v1_proto protoreflect.FileDescriptor

const file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDesc = "" +
	"\n" +
	";financial/order_trade/entity/v1/order_trade_entity_v1.proto\x12\x1ffinancial.order_trade.entity.v1\x1a3financial/emitten/entity/v1/emitten_entity_v1.proto\"\xb0\x14\n" +
	"\vMarketMover\x12[\n" +
	"\fstock_detail\x18\x01 \x01(\v28.financial.order_trade.entity.v1.MarketMover.StockDetailR\vstockDetail\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12?\n" +
	"\x06change\x18\x03 \x01(\v2'.financial.order_trade.entity.v1.ChangeR\x06change\x12A\n" +
	"\x05value\x18\x04 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\x05value\x12C\n" +
	"\x06volume\x18\x05 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\x06volume\x12I\n" +
	"\tfrequency\x18\x06 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\tfrequency\x12S\n" +
	"\x0fnet_foreign_buy\x18\a \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\rnetForeignBuy\x12U\n" +
	"\x10net_foreign_sell\x18\b \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\x0enetForeignSell\x12D\n" +
	"\anet_buy\x18\t \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\x06netBuy\x12F\n" +
	"\bnet_sell\x18\n" +
	" \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\anetSell\x12^\n" +
	"\riepiev_detail\x18\v \x01(\v29.financial.order_trade.entity.v1.MarketMover.IEPIEVDetailR\fiepievDetail\x12Z\n" +
	"\x13big_money_net_value\x18\f \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\x10bigMoneyNetValue\x120\n" +
	"\x14buy_value_percentage\x18\r \x01(\x01R\x12buyValuePercentage\x122\n" +
	"\x15sell_value_percentage\x18\x0e \x01(\x01R\x13sellValuePercentage\x12B\n" +
	"\x1ebig_money_buy_value_percentage\x18\x0f \x01(\x01R\x1abigMoneyBuyValuePercentage\x12D\n" +
	"\x1fbig_money_sell_value_percentage\x18\x10 \x01(\x01R\x1bbigMoneySellValuePercentage\x12\x1f\n" +
	"\vbid_percent\x18\x11 \x01(\x01R\n" +
	"bidPercent\x12a\n" +
	"\x0ecatalog_detail\x18\x12 \x01(\v2:.financial.order_trade.entity.v1.MarketMover.CatalogDetailR\rcatalogDetail\x12M\n" +
	"\n" +
	"market_cap\x18\x13 \x01(\v2..financial.order_trade.entity.v1.MarketCapInfoR\tmarketCap\x1aF\n" +
	"\x0eNotationDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x1aY\n" +
	"\x10CorpactionDetail\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x19\n" +
	"\bicon_url\x18\x02 \x01(\tR\aiconUrl\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x1a\xa3\x02\n" +
	"\vStockDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12\x17\n" +
	"\ahas_uma\x18\x04 \x01(\bR\x06hasUma\x12Y\n" +
	"\tnotations\x18\x05 \x03(\v2;.financial.order_trade.entity.v1.MarketMover.NotationDetailR\tnotations\x12]\n" +
	"\n" +
	"corpaction\x18\x06 \x01(\v2=.financial.order_trade.entity.v1.MarketMover.CorpactionDetailR\n" +
	"corpaction\x1a\x9f\x04\n" +
	"\fIEPIEVDetail\x12=\n" +
	"\x03iep\x18\x01 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\x03iep\x12=\n" +
	"\x03iev\x18\x02 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\x03iev\x12A\n" +
	"\x05ieval\x18\x03 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\x05ieval\x12J\n" +
	"\n" +
	"iep_change\x18\x04 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\tiepChange\x12S\n" +
	"\x0fiep_change_prev\x18\x05 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\riepChangePrev\x12Q\n" +
	"\x0eiep_price_diff\x18\x06 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\fiepPriceDiff\x12Z\n" +
	"\x13iep_prev_price_diff\x18\a \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\x10iepPrevPriceDiff\x1a\xf5\x01\n" +
	"\rCatalogDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12\x19\n" +
	"\bup_count\x18\x04 \x01(\x05R\aupCount\x12\x1d\n" +
	"\n" +
	"down_count\x18\x05 \x01(\x05R\tdownCount\x12'\n" +
	"\x0funchanged_count\x18\x06 \x01(\x05R\x0eunchangedCount\x12\x1f\n" +
	"\vstock_count\x18\a \x01(\x05R\n" +
	"stockCount\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\b \x01(\x03R\tcatalogId\"\xe5\x02\n" +
	"\x10MarketMoverBatch\x12B\n" +
	"\x05batch\x18\x01 \x03(\v2,.financial.order_trade.entity.v1.MarketMoverR\x05batch\x12I\n" +
	"\n" +
	"mover_type\x18\x02 \x01(\x0e2*.financial.order_trade.entity.v1.MoverTypeR\tmoverType\x12V\n" +
	"\rfilter_stocks\x18\x03 \x03(\x0e21.financial.order_trade.entity.v1.FilterStocksTypeR\ffilterStocks\x12K\n" +
	"\fcatalog_type\x18\x04 \x01(\x0e2(.financial.emitten.entity.v1.CatalogTypeR\vcatalogType\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\x05 \x01(\x03R\tcatalogId\">\n" +
	"\x06Change\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x01R\n" +
	"percentage\"<\n" +
	"\n" +
	"MoverValue\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\x01R\x03raw\x12\x1c\n" +
	"\tformatted\x18\x02 \x01(\tR\tformatted\"\xac\x02\n" +
	"\x1bMarketMoverWebsocketRequest\x12I\n" +
	"\n" +
	"mover_type\x18\x01 \x01(\x0e2*.financial.order_trade.entity.v1.MoverTypeR\tmoverType\x12V\n" +
	"\rfilter_stocks\x18\x02 \x03(\x0e21.financial.order_trade.entity.v1.FilterStocksTypeR\ffilterStocks\x12K\n" +
	"\fcatalog_type\x18\x03 \x01(\x0e2(.financial.emitten.entity.v1.CatalogTypeR\vcatalogType\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\x04 \x01(\x03R\tcatalogId\"\x84\x02\n" +
	"\rMarketCapInfo\x12E\n" +
	"\acurrent\x18\x01 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\acurrent\x12G\n" +
	"\bprevious\x18\x02 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\bprevious\x12C\n" +
	"\x06change\x18\x03 \x01(\v2+.financial.order_trade.entity.v1.MoverValueR\x06change\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\"\xcc\x01\n" +
	"\x12TradebookWSMessage\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12I\n" +
	"\tbig_money\x18\x03 \x01(\v2,.financial.order_trade.entity.v1.MarketMoverR\bbigMoney\x12\x14\n" +
	"\x05board\x18\x04 \x01(\tR\x05board\x12\x1f\n" +
	"\vbid_percent\x18\x05 \x01(\x01R\n" +
	"bidPercent\"I\n" +
	"\x19TradebookWebsocketRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05board\x18\x02 \x01(\tR\x05board\"\x82\x01\n" +
	"\x05Order\x12\x12\n" +
	"\x04full\x18\x01 \x01(\x03R\x04full\x12\x1c\n" +
	"\tformatted\x18\x02 \x01(\tR\tformatted\x1aG\n" +
	"\x13ExchangeOrderNumber\x12\x12\n" +
	"\x04full\x18\x01 \x01(\x03R\x04full\x12\x1c\n" +
	"\tformatted\x18\x02 \x01(\tR\tformatted\"\xea\x01\n" +
	"\x1aOrderQueueWebsocketRequest\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12I\n" +
	"\n" +
	"board_type\x18\x03 \x01(\x0e2*.financial.order_trade.entity.v1.BoardTypeR\tboardType\x12L\n" +
	"\vaction_type\x18\x04 \x01(\x0e2+.financial.order_trade.entity.v1.ActionTypeR\n" +
	"actionType\"c\n" +
	"\x13OrderQueueWebsocket\x12L\n" +
	"\x04data\x18\x01 \x03(\v28.financial.order_trade.entity.v1.OrderQueueWebsocketDataR\x04data\"\xac\x04\n" +
	"\x17OrderQueueWebsocketData\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x12L\n" +
	"\vaction_type\x18\x03 \x01(\x0e2+.financial.order_trade.entity.v1.ActionTypeR\n" +
	"actionType\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12D\n" +
	"\x06status\x18\x05 \x01(\x0e2,.financial.order_trade.entity.v1.OrderStatusR\x06status\x12\x12\n" +
	"\x04open\x18\x06 \x01(\x02R\x04open\x12\x10\n" +
	"\x03lot\x18\a \x01(\x02R\x03lot\x12I\n" +
	"\n" +
	"board_type\x18\b \x01(\x0e2*.financial.order_trade.entity.v1.BoardTypeR\tboardType\x12n\n" +
	"\x15exchange_order_number\x18\t \x01(\v2:.financial.order_trade.entity.v1.Order.ExchangeOrderNumberR\x13exchangeOrderNumber\x12!\n" +
	"\forder_number\x18\n" +
	" \x01(\x03R\vorderNumber\x120\n" +
	"\x14open_change_quantity\x18\v \x01(\x02R\x12openChangeQuantity*\x8c\x05\n" +
	"\tMoverType\x12\x1a\n" +
	"\x16MOVER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MOVER_TYPE_TOP_VALUE\x10\x01\x12\x19\n" +
	"\x15MOVER_TYPE_TOP_VOLUME\x10\x02\x12\x1c\n" +
	"\x18MOVER_TYPE_TOP_FREQUENCY\x10\x03\x12\x19\n" +
	"\x15MOVER_TYPE_TOP_GAINER\x10\x04\x12\x18\n" +
	"\x14MOVER_TYPE_TOP_LOSER\x10\x05\x12\x1e\n" +
	"\x1aMOVER_TYPE_NET_FOREIGN_BUY\x10\x06\x12\x1f\n" +
	"\x1bMOVER_TYPE_NET_FOREIGN_SELL\x10\a\x12%\n" +
	"!MOVER_TYPE_IEP_CURRENT_TOP_GAINER\x10\b\x12$\n" +
	" MOVER_TYPE_IEP_CURRENT_TOP_LOSER\x10\t\x12\x1d\n" +
	"\x19MOVER_TYPE_IEV_TOP_GAINER\x10\n" +
	"\x12\x1c\n" +
	"\x18MOVER_TYPE_IEV_TOP_LOSER\x10\v\x12\x1f\n" +
	"\x1bMOVER_TYPE_IEVAL_TOP_GAINER\x10\f\x12\x1e\n" +
	"\x1aMOVER_TYPE_IEVAL_TOP_LOSER\x10\r\x12\"\n" +
	"\x1eMOVER_TYPE_IEP_PREV_TOP_GAINER\x10\x0e\x12!\n" +
	"\x1dMOVER_TYPE_IEP_PREV_TOP_LOSER\x10\x0f\x12\"\n" +
	"\x1eMOVER_TYPE_BIG_MONEY_NET_VALUE\x10\x10\x12\x16\n" +
	"\x12MOVER_TYPE_CATALOG\x10\x11\x12!\n" +
	"\x1dMOVER_TYPE_BIG_MONEY_NET_SELL\x10\x12\x12)\n" +
	"%MOVER_TYPE_CATALOG_KONGLO_MCAP_CHANGE\x10\x13*\xd2\x02\n" +
	"\x10FilterStocksType\x12\"\n" +
	"\x1eFILTER_STOCKS_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dFILTER_STOCKS_TYPE_MAIN_BOARD\x10\x01\x12(\n" +
	"$FILTER_STOCKS_TYPE_DEVELOPMENT_BOARD\x10\x02\x12)\n" +
	"%FILTER_STOCKS_TYPE_ACCELERATION_BOARD\x10\x03\x12(\n" +
	"$FILTER_STOCKS_TYPE_NEW_ECONOMY_BOARD\x10\x04\x12/\n" +
	"+FILTER_STOCKS_TYPE_SPECIAL_MONITORING_BOARD\x10\x05\x12(\n" +
	"$FILTER_STOCKS_TYPE_WARRANT_AND_RIGHT\x10\x06\x12\x1d\n" +
	"\x19FILTER_STOCKS_TYPE_SHARIA\x10\a*i\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fACTION_TYPE_BUY\x10\x01\x12\x14\n" +
	"\x10ACTION_TYPE_SELL\x10\x02\x12\x13\n" +
	"\x0fACTION_TYPE_ALL\x10\x03*\xc9\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_STATUS_OPEN\x10\x01\x12\x1b\n" +
	"\x17ORDER_STATUS_FULL_MATCH\x10\x02\x12\x1a\n" +
	"\x16ORDER_STATUS_WITHDRAWN\x10\x03\x12\x1e\n" +
	"\x1aORDER_STATUS_PARTIAL_MATCH\x10\x04\x12\x16\n" +
	"\x12ORDER_STATUS_AMEND\x10\x05\x12\x14\n" +
	"\x10ORDER_STATUS_ALL\x10\x06*\x84\x01\n" +
	"\tBoardType\x12\x1a\n" +
	"\x16BOARD_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12BOARD_TYPE_REGULAR\x10\x01\x12\x1a\n" +
	"\x16BOARD_TYPE_NEGOTIATION\x10\x02\x12\x13\n" +
	"\x0fBOARD_TYPE_CASH\x10\x03\x12\x12\n" +
	"\x0eBOARD_TYPE_ALL\x10\x04BzZxgithub.com/nofendian17/sbterm-server/internal/infrastructure/stockbit/proto/financial/order_trade/entity/v1;ordertradev1b\x06proto3"

var (
	file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescOnce sync.Once
	file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescData []byte
)

func file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescGZIP() []byte {
	file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescOnce.Do(func() {
		file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDesc), len(file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDesc)))
	})
	return file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDescData
}

var file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_goTypes = []any{
	(MoverType)(0),                       // 0: financial.order_trade.entity.v1.MoverType
	(FilterStocksType)(0),                // 1: financial.order_trade.entity.v1.FilterStocksType
	(ActionType)(0),                      // 2: financial.order_trade.entity.v1.ActionType
	(OrderStatus)(0),                     // 3: financial.order_trade.entity.v1.OrderStatus
	(BoardType)(0),                       // 4: financial.order_trade.entity.v1.BoardType
	(*MarketMover)(nil),                  // 5: financial.order_trade.entity.v1.MarketMover
	(*MarketMoverBatch)(nil),             // 6: financial.order_trade.entity.v1.MarketMoverBatch
	(*Change)(nil),                       // 7: financial.order_trade.entity.v1.Change
	(*MoverValue)(nil),                   // 8: financial.order_trade.entity.v1.MoverValue
	(*MarketMoverWebsocketRequest)(nil),  // 9: financial.order_trade.entity.v1.MarketMoverWebsocketRequest
	(*MarketCapInfo)(nil),                // 10: financial.order_trade.entity.v1.MarketCapInfo
	(*TradebookWSMessage)(nil),           // 11: financial.order_trade.entity.v1.TradebookWSMessage
	(*TradebookWebsocketRequest)(nil),    // 12: financial.order_trade.entity.v1.TradebookWebsocketRequest
	(*Order)(nil),                        // 13: financial.order_trade.entity.v1.Order
	(*OrderQueueWebsocketRequest)(nil),   // 14: financial.order_trade.entity.v1.OrderQueueWebsocketRequest
	(*OrderQueueWebsocket)(nil),          // 15: financial.order_trade.entity.v1.OrderQueueWebsocket
	(*OrderQueueWebsocketData)(nil),      // 16: financial.order_trade.entity.v1.OrderQueueWebsocketData
	(*MarketMover_NotationDetail)(nil),   // 17: financial.order_trade.entity.v1.MarketMover.NotationDetail
	(*MarketMover_CorpactionDetail)(nil), // 18: financial.order_trade.entity.v1.MarketMover.CorpactionDetail
	(*MarketMover_StockDetail)(nil),      // 19: financial.order_trade.entity.v1.MarketMover.StockDetail
	(*MarketMover_IEPIEVDetail)(nil),     // 20: financial.order_trade.entity.v1.MarketMover.IEPIEVDetail
	(*MarketMover_CatalogDetail)(nil),    // 21: financial.order_trade.entity.v1.MarketMover.CatalogDetail
	(*Order_ExchangeOrderNumber)(nil),    // 22: financial.order_trade.entity.v1.Order.ExchangeOrderNumber
	(v1.CatalogType)(0),                  // 23: financial.emitten.entity.v1.CatalogType
}
var file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_depIdxs = []int32{
	19, // 0: financial.order_trade.entity.v1.MarketMover.stock_detail:type_name -> financial.order_trade.entity.v1.MarketMover.StockDetail
	7,  // 1: financial.order_trade.entity.v1.MarketMover.change:type_name -> financial.order_trade.entity.v1.Change
	8,  // 2: financial.order_trade.entity.v1.MarketMover.value:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 3: financial.order_trade.entity.v1.MarketMover.volume:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 4: financial.order_trade.entity.v1.MarketMover.frequency:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 5: financial.order_trade.entity.v1.MarketMover.net_foreign_buy:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 6: financial.order_trade.entity.v1.MarketMover.net_foreign_sell:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 7: financial.order_trade.entity.v1.MarketMover.net_buy:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 8: financial.order_trade.entity.v1.MarketMover.net_sell:type_name -> financial.order_trade.entity.v1.MoverValue
	20, // 9: financial.order_trade.entity.v1.MarketMover.iepiev_detail:type_name -> financial.order_trade.entity.v1.MarketMover.IEPIEVDetail
	8,  // 10: financial.order_trade.entity.v1.MarketMover.big_money_net_value:type_name -> financial.order_trade.entity.v1.MoverValue
	21, // 11: financial.order_trade.entity.v1.MarketMover.catalog_detail:type_name -> financial.order_trade.entity.v1.MarketMover.CatalogDetail
	10, // 12: financial.order_trade.entity.v1.MarketMover.market_cap:type_name -> financial.order_trade.entity.v1.MarketCapInfo
	5,  // 13: financial.order_trade.entity.v1.MarketMoverBatch.batch:type_name -> financial.order_trade.entity.v1.MarketMover
	0,  // 14: financial.order_trade.entity.v1.MarketMoverBatch.mover_type:type_name -> financial.order_trade.entity.v1.MoverType
	1,  // 15: financial.order_trade.entity.v1.MarketMoverBatch.filter_stocks:type_name -> financial.order_trade.entity.v1.FilterStocksType
	23, // 16: financial.order_trade.entity.v1.MarketMoverBatch.catalog_type:type_name -> financial.emitten.entity.v1.CatalogType
	0,  // 17: financial.order_trade.entity.v1.MarketMoverWebsocketRequest.mover_type:type_name -> financial.order_trade.entity.v1.MoverType
	1,  // 18: financial.order_trade.entity.v1.MarketMoverWebsocketRequest.filter_stocks:type_name -> financial.order_trade.entity.v1.FilterStocksType
	23, // 19: financial.order_trade.entity.v1.MarketMoverWebsocketRequest.catalog_type:type_name -> financial.emitten.entity.v1.CatalogType
	8,  // 20: financial.order_trade.entity.v1.MarketCapInfo.current:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 21: financial.order_trade.entity.v1.MarketCapInfo.previous:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 22: financial.order_trade.entity.v1.MarketCapInfo.change:type_name -> financial.order_trade.entity.v1.MoverValue
	5,  // 23: financial.order_trade.entity.v1.TradebookWSMessage.big_money:type_name -> financial.order_trade.entity.v1.MarketMover
	4,  // 24: financial.order_trade.entity.v1.OrderQueueWebsocketRequest.board_type:type_name -> financial.order_trade.entity.v1.BoardType
	2,  // 25: financial.order_trade.entity.v1.OrderQueueWebsocketRequest.action_type:type_name -> financial.order_trade.entity.v1.ActionType
	16, // 26: financial.order_trade.entity.v1.OrderQueueWebsocket.data:type_name -> financial.order_trade.entity.v1.OrderQueueWebsocketData
	2,  // 27: financial.order_trade.entity.v1.OrderQueueWebsocketData.action_type:type_name -> financial.order_trade.entity.v1.ActionType
	3,  // 28: financial.order_trade.entity.v1.OrderQueueWebsocketData.status:type_name -> financial.order_trade.entity.v1.OrderStatus
	4,  // 29: financial.order_trade.entity.v1.OrderQueueWebsocketData.board_type:type_name -> financial.order_trade.entity.v1.BoardType
	22, // 30: financial.order_trade.entity.v1.OrderQueueWebsocketData.exchange_order_number:type_name -> financial.order_trade.entity.v1.Order.ExchangeOrderNumber
	17, // 31: financial.order_trade.entity.v1.MarketMover.StockDetail.notations:type_name -> financial.order_trade.entity.v1.MarketMover.NotationDetail
	18, // 32: financial.order_trade.entity.v1.MarketMover.StockDetail.corpaction:type_name -> financial.order_trade.entity.v1.MarketMover.CorpactionDetail
	8,  // 33: financial.order_trade.entity.v1.MarketMover.IEPIEVDetail.iep:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 34: financial.order_trade.entity.v1.MarketMover.IEPIEVDetail.iev:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 35: financial.order_trade.entity.v1.MarketMover.IEPIEVDetail.ieval:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 36: financial.order_trade.entity.v1.MarketMover.IEPIEVDetail.iep_change:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 37: financial.order_trade.entity.v1.MarketMover.IEPIEVDetail.iep_change_prev:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 38: financial.order_trade.entity.v1.MarketMover.IEPIEVDetail.iep_price_diff:type_name -> financial.order_trade.entity.v1.MoverValue
	8,  // 39: financial.order_trade.entity.v1.MarketMover.IEPIEVDetail.iep_prev_price_diff:type_name -> financial.order_trade.entity.v1.MoverValue
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_init() }
func file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_init() {
	if File_financial_order_trade_entity_v1_order_trade_entity_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDesc), len(file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_goTypes,
		DependencyIndexes: file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_depIdxs,
		EnumInfos:         file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_enumTypes,
		MessageInfos:      file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_msgTypes,
	}.Build()
	File_financial_order_trade_entity_v1_order_trade_entity_v1_proto = out.File
	file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_goTypes = nil
	file_financial_order_trade_entity_v1_order_trade_entity_v1_proto_depIdxs = nil
}
