// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: securities/transactional/datafeed/consumer/entity/v1/consumer_entity_v1.proto

// Reconstructed from stockbit.com webpack bundle (chunk 51232-5d0c93927d38e370.js,
// module 228) — protobuf-es message definitions. NOT an official schema.
// Datafeed websocket — koneksi wss://wssfeed.stockbit.com/?wskey=<key>.

package dataconsumerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoardType int32

const (
	BoardType_BOARD_TYPE_UNSPECIFIED BoardType = 0
	BoardType_BOARD_TYPE_RG          BoardType = 1
	BoardType_BOARD_TYPE_TN          BoardType = 2
	BoardType_BOARD_TYPE_NG          BoardType = 3
)

// Enum value maps for BoardType.
var (
	BoardType_name = map[int32]string{
		0: "BOARD_TYPE_UNSPECIFIED",
		1: "BOARD_TYPE_RG",
		2: "BOARD_TYPE_TN",
		3: "BOARD_TYPE_NG",
	}
	BoardType_value = map[string]int32{
		"BOARD_TYPE_UNSPECIFIED": 0,
		"BOARD_TYPE_RG":          1,
		"BOARD_TYPE_TN":          2,
		"BOARD_TYPE_NG":          3,
	}
)

func (x BoardType) Enum() *BoardType {
	p := new(BoardType)
	*p = x
	return p
}

func (x BoardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoardType) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_enumTypes[0].Descriptor()
}

func (BoardType) Type() protoreflect.EnumType {
	return &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_enumTypes[0]
}

func (x BoardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoardType.Descriptor instead.
func (BoardType) EnumDescriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescGZIP(), []int{0}
}

type Source int32

const (
	Source_SOURCE_UNSPECIFIED Source = 0
	Source_SOURCE_ITCH        Source = 1
	Source_SOURCE_IMQ         Source = 2
	Source_SOURCE_CRYPTO      Source = 3
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "SOURCE_ITCH",
		2: "SOURCE_IMQ",
		3: "SOURCE_CRYPTO",
	}
	Source_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"SOURCE_ITCH":        1,
		"SOURCE_IMQ":         2,
		"SOURCE_CRYPTO":      3,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_enumTypes[1].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_enumTypes[1]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescGZIP(), []int{1}
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`           // T:1
	Percentage    float64                `protobuf:"fixed64,2,opt,name=percentage,proto3" json:"percentage,omitempty"` // T:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Change) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Change) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type Intraday struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockCode     string                 `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"` // T:9
	Datetime      string                 `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`                    // T:9
	Open          float64                `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`                          // T:1
	High          float64                `protobuf:"fixed64,4,opt,name=high,proto3" json:"high,omitempty"`                          // T:1
	Low           float64                `protobuf:"fixed64,5,opt,name=low,proto3" json:"low,omitempty"`                            // T:1
	Close         float64                `protobuf:"fixed64,6,opt,name=close,proto3" json:"close,omitempty"`                        // T:1
	Volume        float64                `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume,omitempty"`                      // T:1
	Change        *Change                `protobuf:"bytes,8,opt,name=change,proto3" json:"change,omitempty"`
	Lot           int64                  `protobuf:"varint,9,opt,name=lot,proto3" json:"lot,omitempty"` // T:3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intraday) Reset() {
	*x = Intraday{}
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intraday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intraday) ProtoMessage() {}

func (x *Intraday) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intraday.ProtoReflect.Descriptor instead.
func (*Intraday) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescGZIP(), []int{1}
}

func (x *Intraday) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *Intraday) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *Intraday) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Intraday) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Intraday) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Intraday) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Intraday) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Intraday) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *Intraday) GetLot() int64 {
	if x != nil {
		return x.Lot
	}
	return 0
}

type LivePrice struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StockCode        string                 `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"` // T:9
	Lastprice        float64                `protobuf:"fixed64,2,opt,name=lastprice,proto3" json:"lastprice,omitempty"`                // T:1
	Volume           float64                `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`                      // T:1
	High             float64                `protobuf:"fixed64,4,opt,name=high,proto3" json:"high,omitempty"`                          // T:1
	Low              float64                `protobuf:"fixed64,5,opt,name=low,proto3" json:"low,omitempty"`                            // T:1
	Open             float64                `protobuf:"fixed64,6,opt,name=open,proto3" json:"open,omitempty"`                          // T:1
	Frequency        float64                `protobuf:"fixed64,7,opt,name=frequency,proto3" json:"frequency,omitempty"`                // T:1
	FrgBuy           float64                `protobuf:"fixed64,8,opt,name=frg_buy,json=frgBuy,proto3" json:"frg_buy,omitempty"`        // T:1
	FrgSell          float64                `protobuf:"fixed64,9,opt,name=frg_sell,json=frgSell,proto3" json:"frg_sell,omitempty"`     // T:1
	Average          float64                `protobuf:"fixed64,10,opt,name=average,proto3" json:"average,omitempty"`                   // T:1
	Date             string                 `protobuf:"bytes,11,opt,name=date,proto3" json:"date,omitempty"`                           // T:9
	Close            float64                `protobuf:"fixed64,12,opt,name=close,proto3" json:"close,omitempty"`                       // T:1
	Prev             float64                `protobuf:"fixed64,13,opt,name=prev,proto3" json:"prev,omitempty"`                         // T:1
	Value            float64                `protobuf:"fixed64,14,opt,name=value,proto3" json:"value,omitempty"`                       // T:1
	Change           *Change                `protobuf:"bytes,15,opt,name=change,proto3" json:"change,omitempty"`
	OrderVerb        string                 `protobuf:"bytes,16,opt,name=order_verb,json=orderVerb,proto3" json:"order_verb,omitempty"`                 // T:9
	Quantity         int64                  `protobuf:"varint,17,opt,name=quantity,proto3" json:"quantity,omitempty"`                                   // T:3
	IsIndex          bool                   `protobuf:"varint,18,opt,name=is_index,json=isIndex,proto3" json:"is_index,omitempty"`                      // T:8
	SequenceNumber   int64                  `protobuf:"varint,19,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // T:3
	OrderBookId      int64                  `protobuf:"varint,20,opt,name=order_book_id,json=orderBookId,proto3" json:"order_book_id,omitempty"`        // T:3
	OrderNumber      int64                  `protobuf:"varint,21,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`          // T:3
	MatchNumber      int64                  `protobuf:"varint,22,opt,name=match_number,json=matchNumber,proto3" json:"match_number,omitempty"`          // T:3
	Board            BoardType              `protobuf:"varint,23,opt,name=board,proto3,enum=securities.transactional.datafeed.consumer.entity.v1.BoardType" json:"board,omitempty"`
	Source           Source                 `protobuf:"varint,24,opt,name=source,proto3,enum=securities.transactional.datafeed.consumer.entity.v1.Source" json:"source,omitempty"`
	SwitchReset      *SwitchReset           `protobuf:"bytes,25,opt,name=switch_reset,json=switchReset,proto3" json:"switch_reset,omitempty"`
	ItchIncomingTime string                 `protobuf:"bytes,26,opt,name=itch_incoming_time,json=itchIncomingTime,proto3" json:"itch_incoming_time,omitempty"` // T:9
	TradeTrigger     *TradeTrigger          `protobuf:"bytes,27,opt,name=trade_trigger,json=tradeTrigger,proto3" json:"trade_trigger,omitempty"`
	Lot              float64                `protobuf:"fixed64,28,opt,name=lot,proto3" json:"lot,omitempty"` // T:1
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LivePrice) Reset() {
	*x = LivePrice{}
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivePrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivePrice) ProtoMessage() {}

func (x *LivePrice) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivePrice.ProtoReflect.Descriptor instead.
func (*LivePrice) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescGZIP(), []int{2}
}

func (x *LivePrice) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *LivePrice) GetLastprice() float64 {
	if x != nil {
		return x.Lastprice
	}
	return 0
}

func (x *LivePrice) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *LivePrice) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *LivePrice) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *LivePrice) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *LivePrice) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *LivePrice) GetFrgBuy() float64 {
	if x != nil {
		return x.FrgBuy
	}
	return 0
}

func (x *LivePrice) GetFrgSell() float64 {
	if x != nil {
		return x.FrgSell
	}
	return 0
}

func (x *LivePrice) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *LivePrice) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *LivePrice) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *LivePrice) GetPrev() float64 {
	if x != nil {
		return x.Prev
	}
	return 0
}

func (x *LivePrice) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *LivePrice) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *LivePrice) GetOrderVerb() string {
	if x != nil {
		return x.OrderVerb
	}
	return ""
}

func (x *LivePrice) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *LivePrice) GetIsIndex() bool {
	if x != nil {
		return x.IsIndex
	}
	return false
}

func (x *LivePrice) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *LivePrice) GetOrderBookId() int64 {
	if x != nil {
		return x.OrderBookId
	}
	return 0
}

func (x *LivePrice) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *LivePrice) GetMatchNumber() int64 {
	if x != nil {
		return x.MatchNumber
	}
	return 0
}

func (x *LivePrice) GetBoard() BoardType {
	if x != nil {
		return x.Board
	}
	return BoardType_BOARD_TYPE_UNSPECIFIED
}

func (x *LivePrice) GetSource() Source {
	if x != nil {
		return x.Source
	}
	return Source_SOURCE_UNSPECIFIED
}

func (x *LivePrice) GetSwitchReset() *SwitchReset {
	if x != nil {
		return x.SwitchReset
	}
	return nil
}

func (x *LivePrice) GetItchIncomingTime() string {
	if x != nil {
		return x.ItchIncomingTime
	}
	return ""
}

func (x *LivePrice) GetTradeTrigger() *TradeTrigger {
	if x != nil {
		return x.TradeTrigger
	}
	return nil
}

func (x *LivePrice) GetLot() float64 {
	if x != nil {
		return x.Lot
	}
	return 0
}

type TradeTrigger struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StockCode      string                 `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`                  // T:9
	Quantity       int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`                                    // T:3
	ExecutionPrice float64                `protobuf:"fixed64,3,opt,name=execution_price,json=executionPrice,proto3" json:"execution_price,omitempty"` // T:1
	Value          float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`                                         // T:1
	Volume         float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`                                       // T:1
	Timestamp      string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                   // T:9
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradeTrigger) Reset() {
	*x = TradeTrigger{}
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeTrigger) ProtoMessage() {}

func (x *TradeTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeTrigger.ProtoReflect.Descriptor instead.
func (*TradeTrigger) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescGZIP(), []int{3}
}

func (x *TradeTrigger) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *TradeTrigger) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeTrigger) GetExecutionPrice() float64 {
	if x != nil {
		return x.ExecutionPrice
	}
	return 0
}

func (x *TradeTrigger) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TradeTrigger) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *TradeTrigger) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Orderbook struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StockCode        string                 `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`                 // T:9
	Body             string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`                                            // T:9
	SequenceNumber   int64                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // T:3
	OrderBookId      int64                  `protobuf:"varint,4,opt,name=order_book_id,json=orderBookId,proto3" json:"order_book_id,omitempty"`        // T:3
	Datetime         string                 `protobuf:"bytes,5,opt,name=datetime,proto3" json:"datetime,omitempty"`                                    // T:9
	Source           Source                 `protobuf:"varint,6,opt,name=source,proto3,enum=securities.transactional.datafeed.consumer.entity.v1.Source" json:"source,omitempty"`
	SwitchReset      *SwitchReset           `protobuf:"bytes,7,opt,name=switch_reset,json=switchReset,proto3" json:"switch_reset,omitempty"`
	Board            BoardType              `protobuf:"varint,8,opt,name=board,proto3,enum=securities.transactional.datafeed.consumer.entity.v1.BoardType" json:"board,omitempty"`
	ItchIncomingTime string                 `protobuf:"bytes,9,opt,name=itch_incoming_time,json=itchIncomingTime,proto3" json:"itch_incoming_time,omitempty"` // T:9
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Orderbook) Reset() {
	*x = Orderbook{}
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orderbook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orderbook) ProtoMessage() {}

func (x *Orderbook) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orderbook.ProtoReflect.Descriptor instead.
func (*Orderbook) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescGZIP(), []int{4}
}

func (x *Orderbook) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *Orderbook) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Orderbook) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Orderbook) GetOrderBookId() int64 {
	if x != nil {
		return x.OrderBookId
	}
	return 0
}

func (x *Orderbook) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *Orderbook) GetSource() Source {
	if x != nil {
		return x.Source
	}
	return Source_SOURCE_UNSPECIFIED
}

func (x *Orderbook) GetSwitchReset() *SwitchReset {
	if x != nil {
		return x.SwitchReset
	}
	return nil
}

func (x *Orderbook) GetBoard() BoardType {
	if x != nil {
		return x.Board
	}
	return BoardType_BOARD_TYPE_UNSPECIFIED
}

func (x *Orderbook) GetItchIncomingTime() string {
	if x != nil {
		return x.ItchIncomingTime
	}
	return ""
}

type SwitchReset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          Source                 `protobuf:"varint,1,opt,name=from,proto3,enum=securities.transactional.datafeed.consumer.entity.v1.Source" json:"from,omitempty"`
	To            Source                 `protobuf:"varint,2,opt,name=to,proto3,enum=securities.transactional.datafeed.consumer.entity.v1.Source" json:"to,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`     // T:9
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=datetime,proto3" json:"datetime,omitempty"` // jsonName: date_time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchReset) Reset() {
	*x = SwitchReset{}
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchReset) ProtoMessage() {}

func (x *SwitchReset) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchReset.ProtoReflect.Descriptor instead.
func (*SwitchReset) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescGZIP(), []int{5}
}

func (x *SwitchReset) GetFrom() Source {
	if x != nil {
		return x.From
	}
	return Source_SOURCE_UNSPECIFIED
}

func (x *SwitchReset) GetTo() Source {
	if x != nil {
		return x.To
	}
	return Source_SOURCE_UNSPECIFIED
}

func (x *SwitchReset) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SwitchReset) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

var File_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto protoreflect.FileDescriptor

const file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDesc = "" +
	"\n" +
	"Msecurities/transactional/datafeed/consumer/entity/v1/consumer_entity_v1.proto\x124securities.transactional.datafeed.consumer.entity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x06Change\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x01R\n" +
	"percentage\"\x95\x02\n" +
	"\bIntraday\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12\x1a\n" +
	"\bdatetime\x18\x02 \x01(\tR\bdatetime\x12\x12\n" +
	"\x04open\x18\x03 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x04 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x06 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\a \x01(\x01R\x06volume\x12T\n" +
	"\x06change\x18\b \x01(\v2<.securities.transactional.datafeed.consumer.entity.v1.ChangeR\x06change\x12\x10\n" +
	"\x03lot\x18\t \x01(\x03R\x03lot\"\xd5\b\n" +
	"\tLivePrice\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12\x1c\n" +
	"\tlastprice\x18\x02 \x01(\x01R\tlastprice\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\x12\x12\n" +
	"\x04high\x18\x04 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\x01R\x03low\x12\x12\n" +
	"\x04open\x18\x06 \x01(\x01R\x04open\x12\x1c\n" +
	"\tfrequency\x18\a \x01(\x01R\tfrequency\x12\x17\n" +
	"\afrg_buy\x18\b \x01(\x01R\x06frgBuy\x12\x19\n" +
	"\bfrg_sell\x18\t \x01(\x01R\afrgSell\x12\x18\n" +
	"\aaverage\x18\n" +
	" \x01(\x01R\aaverage\x12\x12\n" +
	"\x04date\x18\v \x01(\tR\x04date\x12\x14\n" +
	"\x05close\x18\f \x01(\x01R\x05close\x12\x12\n" +
	"\x04prev\x18\r \x01(\x01R\x04prev\x12\x14\n" +
	"\x05value\x18\x0e \x01(\x01R\x05value\x12T\n" +
	"\x06change\x18\x0f \x01(\v2<.securities.transactional.datafeed.consumer.entity.v1.ChangeR\x06change\x12\x1d\n" +
	"\n" +
	"order_verb\x18\x10 \x01(\tR\torderVerb\x12\x1a\n" +
	"\bquantity\x18\x11 \x01(\x03R\bquantity\x12\x19\n" +
	"\bis_index\x18\x12 \x01(\bR\aisIndex\x12'\n" +
	"\x0fsequence_number\x18\x13 \x01(\x03R\x0esequenceNumber\x12\"\n" +
	"\rorder_book_id\x18\x14 \x01(\x03R\vorderBookId\x12!\n" +
	"\forder_number\x18\x15 \x01(\x03R\vorderNumber\x12!\n" +
	"\fmatch_number\x18\x16 \x01(\x03R\vmatchNumber\x12U\n" +
	"\x05board\x18\x17 \x01(\x0e2?.securities.transactional.datafeed.consumer.entity.v1.BoardTypeR\x05board\x12T\n" +
	"\x06source\x18\x18 \x01(\x0e2<.securities.transactional.datafeed.consumer.entity.v1.SourceR\x06source\x12d\n" +
	"\fswitch_reset\x18\x19 \x01(\v2A.securities.transactional.datafeed.consumer.entity.v1.SwitchResetR\vswitchReset\x12,\n" +
	"\x12itch_incoming_time\x18\x1a \x01(\tR\x10itchIncomingTime\x12g\n" +
	"\rtrade_trigger\x18\x1b \x01(\v2B.securities.transactional.datafeed.consumer.entity.v1.TradeTriggerR\ftradeTrigger\x12\x10\n" +
	"\x03lot\x18\x1c \x01(\x01R\x03lot\"\xbe\x01\n" +
	"\fTradeTrigger\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12'\n" +
	"\x0fexecution_price\x18\x03 \x01(\x01R\x0eexecutionPrice\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"\xe8\x03\n" +
	"\tOrderbook\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x03R\x0esequenceNumber\x12\"\n" +
	"\rorder_book_id\x18\x04 \x01(\x03R\vorderBookId\x12\x1a\n" +
	"\bdatetime\x18\x05 \x01(\tR\bdatetime\x12T\n" +
	"\x06source\x18\x06 \x01(\x0e2<.securities.transactional.datafeed.consumer.entity.v1.SourceR\x06source\x12d\n" +
	"\fswitch_reset\x18\a \x01(\v2A.securities.transactional.datafeed.consumer.entity.v1.SwitchResetR\vswitchReset\x12U\n" +
	"\x05board\x18\b \x01(\x0e2?.securities.transactional.datafeed.consumer.entity.v1.BoardTypeR\x05board\x12,\n" +
	"\x12itch_incoming_time\x18\t \x01(\tR\x10itchIncomingTime\"\xfd\x01\n" +
	"\vSwitchReset\x12P\n" +
	"\x04from\x18\x01 \x01(\x0e2<.securities.transactional.datafeed.consumer.entity.v1.SourceR\x04from\x12L\n" +
	"\x02to\x18\x02 \x01(\x0e2<.securities.transactional.datafeed.consumer.entity.v1.SourceR\x02to\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x126\n" +
	"\bdatetime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime*`\n" +
	"\tBoardType\x12\x1a\n" +
	"\x16BOARD_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rBOARD_TYPE_RG\x10\x01\x12\x11\n" +
	"\rBOARD_TYPE_TN\x10\x02\x12\x11\n" +
	"\rBOARD_TYPE_NG\x10\x03*T\n" +
	"\x06Source\x12\x16\n" +
	"\x12SOURCE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSOURCE_ITCH\x10\x01\x12\x0e\n" +
	"\n" +
	"SOURCE_IMQ\x10\x02\x12\x11\n" +
	"\rSOURCE_CRYPTO\x10\x03B\x92\x01Z\x8f\x01github.com/nofendian17/sbterm-server/internal/infrastructure/stockbit/proto/securities/transactional/datafeed/consumer/entity/v1;dataconsumerv1b\x06proto3"

var (
	file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescOnce sync.Once
	file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescData []byte
)

func file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescGZIP() []byte {
	file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescOnce.Do(func() {
		file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDesc), len(file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDesc)))
	})
	return file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDescData
}

var file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_goTypes = []any{
	(BoardType)(0),                // 0: securities.transactional.datafeed.consumer.entity.v1.BoardType
	(Source)(0),                   // 1: securities.transactional.datafeed.consumer.entity.v1.Source
	(*Change)(nil),                // 2: securities.transactional.datafeed.consumer.entity.v1.Change
	(*Intraday)(nil),              // 3: securities.transactional.datafeed.consumer.entity.v1.Intraday
	(*LivePrice)(nil),             // 4: securities.transactional.datafeed.consumer.entity.v1.LivePrice
	(*TradeTrigger)(nil),          // 5: securities.transactional.datafeed.consumer.entity.v1.TradeTrigger
	(*Orderbook)(nil),             // 6: securities.transactional.datafeed.consumer.entity.v1.Orderbook
	(*SwitchReset)(nil),           // 7: securities.transactional.datafeed.consumer.entity.v1.SwitchReset
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_depIdxs = []int32{
	2,  // 0: securities.transactional.datafeed.consumer.entity.v1.Intraday.change:type_name -> securities.transactional.datafeed.consumer.entity.v1.Change
	2,  // 1: securities.transactional.datafeed.consumer.entity.v1.LivePrice.change:type_name -> securities.transactional.datafeed.consumer.entity.v1.Change
	0,  // 2: securities.transactional.datafeed.consumer.entity.v1.LivePrice.board:type_name -> securities.transactional.datafeed.consumer.entity.v1.BoardType
	1,  // 3: securities.transactional.datafeed.consumer.entity.v1.LivePrice.source:type_name -> securities.transactional.datafeed.consumer.entity.v1.Source
	7,  // 4: securities.transactional.datafeed.consumer.entity.v1.LivePrice.switch_reset:type_name -> securities.transactional.datafeed.consumer.entity.v1.SwitchReset
	5,  // 5: securities.transactional.datafeed.consumer.entity.v1.LivePrice.trade_trigger:type_name -> securities.transactional.datafeed.consumer.entity.v1.TradeTrigger
	1,  // 6: securities.transactional.datafeed.consumer.entity.v1.Orderbook.source:type_name -> securities.transactional.datafeed.consumer.entity.v1.Source
	7,  // 7: securities.transactional.datafeed.consumer.entity.v1.Orderbook.switch_reset:type_name -> securities.transactional.datafeed.consumer.entity.v1.SwitchReset
	0,  // 8: securities.transactional.datafeed.consumer.entity.v1.Orderbook.board:type_name -> securities.transactional.datafeed.consumer.entity.v1.BoardType
	1,  // 9: securities.transactional.datafeed.consumer.entity.v1.SwitchReset.from:type_name -> securities.transactional.datafeed.consumer.entity.v1.Source
	1,  // 10: securities.transactional.datafeed.consumer.entity.v1.SwitchReset.to:type_name -> securities.transactional.datafeed.consumer.entity.v1.Source
	8,  // 11: securities.transactional.datafeed.consumer.entity.v1.SwitchReset.datetime:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() {
	file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_init()
}
func file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_init() {
	if File_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDesc), len(file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_goTypes,
		DependencyIndexes: file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_depIdxs,
		EnumInfos:         file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_enumTypes,
		MessageInfos:      file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_msgTypes,
	}.Build()
	File_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto = out.File
	file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_goTypes = nil
	file_securities_transactional_datafeed_consumer_entity_v1_consumer_entity_v1_proto_depIdxs = nil
}
