// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: securities/transactional/datafeed/v1/datafeed_websocket.proto

// Reconstructed from stockbit.com webpack bundle (chunk 51232-5d0c93927d38e370.js,
// module 228) — protobuf-es message definitions. NOT an official schema.
// Datafeed websocket — koneksi wss://wssfeed.stockbit.com/?wskey=<key>.

package datav1

import (
	v12 "github.com/nofendian17/sbterm/libs/proto/financial/company_price_feed/entity/v1"
	v21 "github.com/nofendian17/sbterm/libs/proto/financial/company_price_feed/entity/v2"
	v2 "github.com/nofendian17/sbterm/libs/proto/financial/emitten/entity/v2"
	v11 "github.com/nofendian17/sbterm/libs/proto/financial/order_trade/entity/v1"
	v1 "github.com/nofendian17/sbterm/libs/proto/securities/transactional/datafeed/consumer/entity/v1"
	v3 "github.com/nofendian17/sbterm/libs/proto/securities/transactional/datafeed/consumer/entity/v3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Top20Type int32

const (
	Top20Type_TOP20_TYPE_UNSPECIFIED          Top20Type = 0
	Top20Type_TOP20_TYPE_FREQUENCY_RG         Top20Type = 2
	Top20Type_TOP20_TYPE_PERCENTAGE_GAINER_RG Top20Type = 5
	Top20Type_TOP20_TYPE_PERCENTAGE_LOSER_RG  Top20Type = 6
)

// Enum value maps for Top20Type.
var (
	Top20Type_name = map[int32]string{
		0: "TOP20_TYPE_UNSPECIFIED",
		2: "TOP20_TYPE_FREQUENCY_RG",
		5: "TOP20_TYPE_PERCENTAGE_GAINER_RG",
		6: "TOP20_TYPE_PERCENTAGE_LOSER_RG",
	}
	Top20Type_value = map[string]int32{
		"TOP20_TYPE_UNSPECIFIED":          0,
		"TOP20_TYPE_FREQUENCY_RG":         2,
		"TOP20_TYPE_PERCENTAGE_GAINER_RG": 5,
		"TOP20_TYPE_PERCENTAGE_LOSER_RG":  6,
	}
)

func (x Top20Type) Enum() *Top20Type {
	p := new(Top20Type)
	*p = x
	return p
}

func (x Top20Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Top20Type) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_enumTypes[0].Descriptor()
}

func (Top20Type) Type() protoreflect.EnumType {
	return &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_enumTypes[0]
}

func (x Top20Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Top20Type.Descriptor instead.
func (Top20Type) EnumDescriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED  ErrorCode = 0
	ErrorCode_ERROR_CODE_BAD_REQUEST  ErrorCode = 400
	ErrorCode_ERROR_CODE_UNAUTHORIZED ErrorCode = 401
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERROR_CODE_UNSPECIFIED",
		400: "ERROR_CODE_BAD_REQUEST",
		401: "ERROR_CODE_UNAUTHORIZED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":  0,
		"ERROR_CODE_BAD_REQUEST":  400,
		"ERROR_CODE_UNAUTHORIZED": 401,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{1}
}

type TradeType int32

const (
	TradeType_TRADE_TYPE_UNSPECIFIED TradeType = 0
	TradeType_TRADE_TYPE_BUY         TradeType = 1
	TradeType_TRADE_TYPE_SELL        TradeType = 2
)

// Enum value maps for TradeType.
var (
	TradeType_name = map[int32]string{
		0: "TRADE_TYPE_UNSPECIFIED",
		1: "TRADE_TYPE_BUY",
		2: "TRADE_TYPE_SELL",
	}
	TradeType_value = map[string]int32{
		"TRADE_TYPE_UNSPECIFIED": 0,
		"TRADE_TYPE_BUY":         1,
		"TRADE_TYPE_SELL":        2,
	}
)

func (x TradeType) Enum() *TradeType {
	p := new(TradeType)
	*p = x
	return p
}

func (x TradeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeType) Descriptor() protoreflect.EnumDescriptor {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_enumTypes[2].Descriptor()
}

func (TradeType) Type() protoreflect.EnumType {
	return &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_enumTypes[2]
}

func (x TradeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeType.Descriptor instead.
func (TradeType) EnumDescriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{2}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"` // T:1
	Lot           float64                `protobuf:"fixed64,2,opt,name=lot,proto3" json:"lot,omitempty"`     // T:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *Bid) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Bid) GetLot() float64 {
	if x != nil {
		return x.Lot
	}
	return 0
}

type Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"` // T:1
	Lot           float64                `protobuf:"fixed64,2,opt,name=lot,proto3" json:"lot,omitempty"`     // T:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{3}
}

func (x *Offer) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Offer) GetLot() float64 {
	if x != nil {
		return x.Lot
	}
	return 0
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`           // T:1
	Percentage    float64                `protobuf:"fixed64,2,opt,name=percentage,proto3" json:"percentage,omitempty"` // T:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{4}
}

func (x *Change) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Change) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=securities.transactional.datafeed.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RunningTrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebsocketTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=websocket_time,json=websocketTime,proto3" json:"websocket_time,omitempty"`
	Stock         string                 `protobuf:"bytes,2,opt,name=stock,proto3" json:"stock,omitempty"`     // T:9
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`   // T:1
	Volume        float64                `protobuf:"fixed64,4,opt,name=volume,proto3" json:"volume,omitempty"` // T:1
	Action        TradeType              `protobuf:"varint,5,opt,name=action,proto3,enum=securities.transactional.datafeed.v1.TradeType" json:"action,omitempty"`
	IsGlobal      bool                   `protobuf:"varint,6,opt,name=is_global,json=isGlobal,proto3" json:"is_global,omitempty"` // T:8
	Time          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	Change        *Change                `protobuf:"bytes,8,opt,name=change,proto3" json:"change,omitempty"`
	TradeNumber   int32                  `protobuf:"varint,9,opt,name=trade_number,json=tradeNumber,proto3" json:"trade_number,omitempty"` // T:5
	MarketBoard   v1.BoardType           `protobuf:"varint,10,opt,name=market_board,json=marketBoard,proto3,enum=securities.transactional.datafeed.consumer.entity.v1.BoardType" json:"market_board,omitempty"`
	Value         float64                `protobuf:"fixed64,11,opt,name=value,proto3" json:"value,omitempty"` // T:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningTrade) Reset() {
	*x = RunningTrade{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningTrade) ProtoMessage() {}

func (x *RunningTrade) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningTrade.ProtoReflect.Descriptor instead.
func (*RunningTrade) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{6}
}

func (x *RunningTrade) GetWebsocketTime() *timestamppb.Timestamp {
	if x != nil {
		return x.WebsocketTime
	}
	return nil
}

func (x *RunningTrade) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *RunningTrade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RunningTrade) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *RunningTrade) GetAction() TradeType {
	if x != nil {
		return x.Action
	}
	return TradeType_TRADE_TYPE_UNSPECIFIED
}

func (x *RunningTrade) GetIsGlobal() bool {
	if x != nil {
		return x.IsGlobal
	}
	return false
}

func (x *RunningTrade) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RunningTrade) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *RunningTrade) GetTradeNumber() int32 {
	if x != nil {
		return x.TradeNumber
	}
	return 0
}

func (x *RunningTrade) GetMarketBoard() v1.BoardType {
	if x != nil {
		return x.MarketBoard
	}
	return v1.BoardType(0)
}

func (x *RunningTrade) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type RunningTradeBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         []*RunningTrade        `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningTradeBatch) Reset() {
	*x = RunningTradeBatch{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningTradeBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningTradeBatch) ProtoMessage() {}

func (x *RunningTradeBatch) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningTradeBatch.ProtoReflect.Descriptor instead.
func (*RunningTradeBatch) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{7}
}

func (x *RunningTradeBatch) GetBatch() []*RunningTrade {
	if x != nil {
		return x.Batch
	}
	return nil
}

type Hotlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockSymbol   string                 `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"` // T:9
	LastPrice     float64                `protobuf:"fixed64,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`     // T:1
	Change        *Change                `protobuf:"bytes,3,opt,name=change,proto3" json:"change,omitempty"`
	Uma           bool                   `protobuf:"varint,4,opt,name=uma,proto3" json:"uma,omitempty"` // T:8
	CorpAction    *v2.CorpAction         `protobuf:"bytes,5,opt,name=corp_action,json=corpAction,proto3" json:"corp_action,omitempty"`
	Notations     []*v2.Notation         `protobuf:"bytes,6,rep,name=notations,proto3" json:"notations,omitempty"`
	StockName     string                 `protobuf:"bytes,7,opt,name=stock_name,json=stockName,proto3" json:"stock_name,omitempty"` // T:9
	IconUrl       string                 `protobuf:"bytes,8,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`       // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hotlist) Reset() {
	*x = Hotlist{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hotlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotlist) ProtoMessage() {}

func (x *Hotlist) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotlist.ProtoReflect.Descriptor instead.
func (*Hotlist) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{8}
}

func (x *Hotlist) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *Hotlist) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *Hotlist) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *Hotlist) GetUma() bool {
	if x != nil {
		return x.Uma
	}
	return false
}

func (x *Hotlist) GetCorpAction() *v2.CorpAction {
	if x != nil {
		return x.CorpAction
	}
	return nil
}

func (x *Hotlist) GetNotations() []*v2.Notation {
	if x != nil {
		return x.Notations
	}
	return nil
}

func (x *Hotlist) GetStockName() string {
	if x != nil {
		return x.StockName
	}
	return ""
}

func (x *Hotlist) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

type Top20 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hotlist       []*Hotlist             `protobuf:"bytes,1,rep,name=hotlist,proto3" json:"hotlist,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Type          Top20Type              `protobuf:"varint,3,opt,name=type,proto3,enum=securities.transactional.datafeed.v1.Top20Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Top20) Reset() {
	*x = Top20{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Top20) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top20) ProtoMessage() {}

func (x *Top20) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Top20.ProtoReflect.Descriptor instead.
func (*Top20) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{9}
}

func (x *Top20) GetHotlist() []*Hotlist {
	if x != nil {
		return x.Hotlist
	}
	return nil
}

func (x *Top20) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Top20) GetType() Top20Type {
	if x != nil {
		return x.Type
	}
	return Top20Type_TOP20_TYPE_UNSPECIFIED
}

type Watchlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockSymbol   string                 `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"` // T:9
	LastPrice     float64                `protobuf:"fixed64,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`     // T:1
	Change        *Change                `protobuf:"bytes,3,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Watchlist) Reset() {
	*x = Watchlist{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Watchlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watchlist) ProtoMessage() {}

func (x *Watchlist) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watchlist.ProtoReflect.Descriptor instead.
func (*Watchlist) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{10}
}

func (x *Watchlist) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *Watchlist) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *Watchlist) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

type OrderBookHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockSymbol   string                 `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"` // T:9
	Change        *Change                `protobuf:"bytes,2,opt,name=change,proto3" json:"change,omitempty"`
	Price         *Price                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookHeader) Reset() {
	*x = OrderBookHeader{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookHeader) ProtoMessage() {}

func (x *OrderBookHeader) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookHeader.ProtoReflect.Descriptor instead.
func (*OrderBookHeader) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{11}
}

func (x *OrderBookHeader) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *OrderBookHeader) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *OrderBookHeader) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OrderBookHeader) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type OrderBookBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockSymbol   string                 `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"` // T:9
	Bid           []*Bid                 `protobuf:"bytes,2,rep,name=bid,proto3" json:"bid,omitempty"`
	Offer         []*Offer               `protobuf:"bytes,3,rep,name=offer,proto3" json:"offer,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookBody) Reset() {
	*x = OrderBookBody{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookBody) ProtoMessage() {}

func (x *OrderBookBody) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookBody.ProtoReflect.Descriptor instead.
func (*OrderBookBody) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{12}
}

func (x *OrderBookBody) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *OrderBookBody) GetBid() []*Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *OrderBookBody) GetOffer() []*Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *OrderBookBody) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          float64                `protobuf:"fixed64,1,opt,name=open,proto3" json:"open,omitempty"`           // T:1
	High          float64                `protobuf:"fixed64,2,opt,name=high,proto3" json:"high,omitempty"`           // T:1
	Low           float64                `protobuf:"fixed64,3,opt,name=low,proto3" json:"low,omitempty"`             // T:1
	Avg           float64                `protobuf:"fixed64,4,opt,name=avg,proto3" json:"avg,omitempty"`             // T:1
	Last          float64                `protobuf:"fixed64,5,opt,name=last,proto3" json:"last,omitempty"`           // T:1
	Prev          float64                `protobuf:"fixed64,6,opt,name=prev,proto3" json:"prev,omitempty"`           // T:1
	Frequency     float64                `protobuf:"fixed64,7,opt,name=frequency,proto3" json:"frequency,omitempty"` // T:1
	Fbuy          float64                `protobuf:"fixed64,8,opt,name=fbuy,proto3" json:"fbuy,omitempty"`           // T:1
	Fsell         float64                `protobuf:"fixed64,9,opt,name=fsell,proto3" json:"fsell,omitempty"`         // T:1
	Lot           float64                `protobuf:"fixed64,10,opt,name=lot,proto3" json:"lot,omitempty"`            // T:1
	Val           float64                `protobuf:"fixed64,11,opt,name=val,proto3" json:"val,omitempty"`            // T:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{13}
}

func (x *Price) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Price) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Price) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Price) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *Price) GetLast() float64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *Price) GetPrev() float64 {
	if x != nil {
		return x.Prev
	}
	return 0
}

func (x *Price) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *Price) GetFbuy() float64 {
	if x != nil {
		return x.Fbuy
	}
	return 0
}

func (x *Price) GetFsell() float64 {
	if x != nil {
		return x.Fsell
	}
	return 0
}

func (x *Price) GetLot() float64 {
	if x != nil {
		return x.Lot
	}
	return 0
}

func (x *Price) GetVal() float64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type WebsocketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // T:9
	Channel       *WebsocketChannel      `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"` // T:9
	Ping          *PingRequest           `protobuf:"bytes,4,opt,name=ping,proto3" json:"ping,omitempty"`
	AccessToken   string                 `protobuf:"bytes,5,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketRequest) Reset() {
	*x = WebsocketRequest{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketRequest) ProtoMessage() {}

func (x *WebsocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketRequest.ProtoReflect.Descriptor instead.
func (*WebsocketRequest) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{14}
}

func (x *WebsocketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WebsocketRequest) GetChannel() *WebsocketChannel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *WebsocketRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WebsocketRequest) GetPing() *PingRequest {
	if x != nil {
		return x.Ping
	}
	return nil
}

func (x *WebsocketRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type WebsocketChannel struct {
	state             protoimpl.MessageState             `protogen:"open.v1"`
	Watchlist         []string                           `protobuf:"bytes,1,rep,name=watchlist,proto3" json:"watchlist,omitempty"`                                            // T:9
	OrderBook         []string                           `protobuf:"bytes,2,rep,name=order_book,json=orderBook,proto3" json:"order_book,omitempty"`                           // T:9
	RunningTrade      []string                           `protobuf:"bytes,3,rep,name=running_trade,json=runningTrade,proto3" json:"running_trade,omitempty"`                  // T:9
	IsHotlist         bool                               `protobuf:"varint,4,opt,name=is_hotlist,json=isHotlist,proto3" json:"is_hotlist,omitempty"`                          // T:8
	RunningTradeBatch []string                           `protobuf:"bytes,5,rep,name=running_trade_batch,json=runningTradeBatch,proto3" json:"running_trade_batch,omitempty"` // T:9
	Liveprice         []string                           `protobuf:"bytes,6,rep,name=liveprice,proto3" json:"liveprice,omitempty"`                                            // T:9
	Iepiev            []string                           `protobuf:"bytes,7,rep,name=iepiev,proto3" json:"iepiev,omitempty"`                                                  // T:9
	Intraday          []string                           `protobuf:"bytes,8,rep,name=intraday,proto3" json:"intraday,omitempty"`                                              // T:9
	BestBidOffer      []string                           `protobuf:"bytes,9,rep,name=best_bid_offer,json=bestBidOffer,proto3" json:"best_bid_offer,omitempty"`                // T:9
	MarketMover       []*v11.MarketMoverWebsocketRequest `protobuf:"bytes,10,rep,name=market_mover,json=marketMover,proto3" json:"market_mover,omitempty"`
	OrderQueue        []*v11.OrderQueueWebsocketRequest  `protobuf:"bytes,11,rep,name=order_queue,json=orderQueue,proto3" json:"order_queue,omitempty"`
	LivepriceV3       []string                           `protobuf:"bytes,12,rep,name=liveprice_v3,json=livepriceV3,proto3" json:"liveprice_v3,omitempty"`   // T:9
	OrderBookV3       []string                           `protobuf:"bytes,13,rep,name=order_book_v3,json=orderBookV3,proto3" json:"order_book_v3,omitempty"` // T:9
	IntradayV3        []string                           `protobuf:"bytes,14,rep,name=intraday_v3,json=intradayV3,proto3" json:"intraday_v3,omitempty"`      // T:9
	Tradebook         []*v11.TradebookWebsocketRequest   `protobuf:"bytes,15,rep,name=tradebook,proto3" json:"tradebook,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WebsocketChannel) Reset() {
	*x = WebsocketChannel{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketChannel) ProtoMessage() {}

func (x *WebsocketChannel) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketChannel.ProtoReflect.Descriptor instead.
func (*WebsocketChannel) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{15}
}

func (x *WebsocketChannel) GetWatchlist() []string {
	if x != nil {
		return x.Watchlist
	}
	return nil
}

func (x *WebsocketChannel) GetOrderBook() []string {
	if x != nil {
		return x.OrderBook
	}
	return nil
}

func (x *WebsocketChannel) GetRunningTrade() []string {
	if x != nil {
		return x.RunningTrade
	}
	return nil
}

func (x *WebsocketChannel) GetIsHotlist() bool {
	if x != nil {
		return x.IsHotlist
	}
	return false
}

func (x *WebsocketChannel) GetRunningTradeBatch() []string {
	if x != nil {
		return x.RunningTradeBatch
	}
	return nil
}

func (x *WebsocketChannel) GetLiveprice() []string {
	if x != nil {
		return x.Liveprice
	}
	return nil
}

func (x *WebsocketChannel) GetIepiev() []string {
	if x != nil {
		return x.Iepiev
	}
	return nil
}

func (x *WebsocketChannel) GetIntraday() []string {
	if x != nil {
		return x.Intraday
	}
	return nil
}

func (x *WebsocketChannel) GetBestBidOffer() []string {
	if x != nil {
		return x.BestBidOffer
	}
	return nil
}

func (x *WebsocketChannel) GetMarketMover() []*v11.MarketMoverWebsocketRequest {
	if x != nil {
		return x.MarketMover
	}
	return nil
}

func (x *WebsocketChannel) GetOrderQueue() []*v11.OrderQueueWebsocketRequest {
	if x != nil {
		return x.OrderQueue
	}
	return nil
}

func (x *WebsocketChannel) GetLivepriceV3() []string {
	if x != nil {
		return x.LivepriceV3
	}
	return nil
}

func (x *WebsocketChannel) GetOrderBookV3() []string {
	if x != nil {
		return x.OrderBookV3
	}
	return nil
}

func (x *WebsocketChannel) GetIntradayV3() []string {
	if x != nil {
		return x.IntradayV3
	}
	return nil
}

func (x *WebsocketChannel) GetTradebook() []*v11.TradebookWebsocketRequest {
	if x != nil {
		return x.Tradebook
	}
	return nil
}

type WebsocketWrapMessageChannel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageChannel:
	//
	//	*WebsocketWrapMessageChannel_RunningTrade
	//	*WebsocketWrapMessageChannel_Ping
	//	*WebsocketWrapMessageChannel_Top20
	//	*WebsocketWrapMessageChannel_Watchlist
	//	*WebsocketWrapMessageChannel_OrderbookHeader
	//	*WebsocketWrapMessageChannel_OrderbookBody
	//	*WebsocketWrapMessageChannel_Error
	//	*WebsocketWrapMessageChannel_RunningTradeBatch
	//	*WebsocketWrapMessageChannel_Liveprice
	//	*WebsocketWrapMessageChannel_Orderbook
	//	*WebsocketWrapMessageChannel_Iepiev
	//	*WebsocketWrapMessageChannel_Intraday
	//	*WebsocketWrapMessageChannel_BestBidOffer
	//	*WebsocketWrapMessageChannel_MarketMoverBatch
	//	*WebsocketWrapMessageChannel_OrderQueue
	//	*WebsocketWrapMessageChannel_LivepriceV3
	//	*WebsocketWrapMessageChannel_OrderbookV3
	//	*WebsocketWrapMessageChannel_IntradayV3
	//	*WebsocketWrapMessageChannel_Tradebook
	MessageChannel isWebsocketWrapMessageChannel_MessageChannel `protobuf_oneof:"message_channel"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebsocketWrapMessageChannel) Reset() {
	*x = WebsocketWrapMessageChannel{}
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketWrapMessageChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketWrapMessageChannel) ProtoMessage() {}

func (x *WebsocketWrapMessageChannel) ProtoReflect() protoreflect.Message {
	mi := &file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketWrapMessageChannel.ProtoReflect.Descriptor instead.
func (*WebsocketWrapMessageChannel) Descriptor() ([]byte, []int) {
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP(), []int{16}
}

func (x *WebsocketWrapMessageChannel) GetMessageChannel() isWebsocketWrapMessageChannel_MessageChannel {
	if x != nil {
		return x.MessageChannel
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetRunningTrade() *RunningTrade {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_RunningTrade); ok {
			return x.RunningTrade
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetPing() *PingResponse {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetTop20() *Top20 {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_Top20); ok {
			return x.Top20
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetWatchlist() *Watchlist {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_Watchlist); ok {
			return x.Watchlist
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetOrderbookHeader() *OrderBookHeader {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_OrderbookHeader); ok {
			return x.OrderbookHeader
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetOrderbookBody() *OrderBookBody {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_OrderbookBody); ok {
			return x.OrderbookBody
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetError() *Error {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetRunningTradeBatch() *RunningTradeBatch {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_RunningTradeBatch); ok {
			return x.RunningTradeBatch
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetLiveprice() *v1.LivePrice {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_Liveprice); ok {
			return x.Liveprice
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetOrderbook() *v1.Orderbook {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_Orderbook); ok {
			return x.Orderbook
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetIepiev() *v21.IEPIEV {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_Iepiev); ok {
			return x.Iepiev
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetIntraday() *v1.Intraday {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_Intraday); ok {
			return x.Intraday
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetBestBidOffer() *v12.BestBidOfferWS {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_BestBidOffer); ok {
			return x.BestBidOffer
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetMarketMoverBatch() *v11.MarketMoverBatch {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_MarketMoverBatch); ok {
			return x.MarketMoverBatch
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetOrderQueue() *v11.OrderQueueWebsocket {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_OrderQueue); ok {
			return x.OrderQueue
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetLivepriceV3() *v3.LivePrice {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_LivepriceV3); ok {
			return x.LivepriceV3
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetOrderbookV3() *v3.Orderbook {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_OrderbookV3); ok {
			return x.OrderbookV3
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetIntradayV3() *v3.Intraday {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_IntradayV3); ok {
			return x.IntradayV3
		}
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetTradebook() *v11.TradebookWSMessage {
	if x != nil {
		if x, ok := x.MessageChannel.(*WebsocketWrapMessageChannel_Tradebook); ok {
			return x.Tradebook
		}
	}
	return nil
}

type isWebsocketWrapMessageChannel_MessageChannel interface {
	isWebsocketWrapMessageChannel_MessageChannel()
}

type WebsocketWrapMessageChannel_RunningTrade struct {
	RunningTrade *RunningTrade `protobuf:"bytes,1,opt,name=running_trade,json=runningTrade,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Ping struct {
	Ping *PingResponse `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Top20 struct {
	Top20 *Top20 `protobuf:"bytes,3,opt,name=top20,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Watchlist struct {
	Watchlist *Watchlist `protobuf:"bytes,4,opt,name=watchlist,proto3,oneof"`
}

type WebsocketWrapMessageChannel_OrderbookHeader struct {
	OrderbookHeader *OrderBookHeader `protobuf:"bytes,5,opt,name=orderbook_header,json=orderbookHeader,proto3,oneof"`
}

type WebsocketWrapMessageChannel_OrderbookBody struct {
	OrderbookBody *OrderBookBody `protobuf:"bytes,6,opt,name=orderbook_body,json=orderbookBody,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Error struct {
	Error *Error `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

type WebsocketWrapMessageChannel_RunningTradeBatch struct {
	RunningTradeBatch *RunningTradeBatch `protobuf:"bytes,8,opt,name=running_trade_batch,json=runningTradeBatch,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Liveprice struct {
	Liveprice *v1.LivePrice `protobuf:"bytes,9,opt,name=liveprice,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Orderbook struct {
	Orderbook *v1.Orderbook `protobuf:"bytes,10,opt,name=orderbook,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Iepiev struct {
	Iepiev *v21.IEPIEV `protobuf:"bytes,11,opt,name=iepiev,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Intraday struct {
	Intraday *v1.Intraday `protobuf:"bytes,12,opt,name=intraday,proto3,oneof"`
}

type WebsocketWrapMessageChannel_BestBidOffer struct {
	BestBidOffer *v12.BestBidOfferWS `protobuf:"bytes,13,opt,name=best_bid_offer,json=bestBidOffer,proto3,oneof"`
}

type WebsocketWrapMessageChannel_MarketMoverBatch struct {
	MarketMoverBatch *v11.MarketMoverBatch `protobuf:"bytes,14,opt,name=market_mover_batch,json=marketMoverBatch,proto3,oneof"`
}

type WebsocketWrapMessageChannel_OrderQueue struct {
	OrderQueue *v11.OrderQueueWebsocket `protobuf:"bytes,15,opt,name=order_queue,json=orderQueue,proto3,oneof"`
}

type WebsocketWrapMessageChannel_LivepriceV3 struct {
	LivepriceV3 *v3.LivePrice `protobuf:"bytes,16,opt,name=liveprice_v3,json=livepriceV3,proto3,oneof"`
}

type WebsocketWrapMessageChannel_OrderbookV3 struct {
	OrderbookV3 *v3.Orderbook `protobuf:"bytes,17,opt,name=orderbook_v3,json=orderbookV3,proto3,oneof"`
}

type WebsocketWrapMessageChannel_IntradayV3 struct {
	IntradayV3 *v3.Intraday `protobuf:"bytes,18,opt,name=intraday_v3,json=intradayV3,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Tradebook struct {
	Tradebook *v11.TradebookWSMessage `protobuf:"bytes,19,opt,name=tradebook,proto3,oneof"`
}

func (*WebsocketWrapMessageChannel_RunningTrade) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_Ping) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_Top20) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_Watchlist) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_OrderbookHeader) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_OrderbookBody) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_Error) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_RunningTradeBatch) isWebsocketWrapMessageChannel_MessageChannel() {
}

func (*WebsocketWrapMessageChannel_Liveprice) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_Orderbook) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_Iepiev) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_Intraday) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_BestBidOffer) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_MarketMoverBatch) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_OrderQueue) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_LivepriceV3) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_OrderbookV3) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_IntradayV3) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_Tradebook) isWebsocketWrapMessageChannel_MessageChannel() {}

var File_securities_transactional_datafeed_v1_datafeed_websocket_proto protoreflect.FileDescriptor

const file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDesc = "" +
	"\n" +
	"=securities/transactional/datafeed/v1/datafeed_websocket.proto\x12$securities.transactional.datafeed.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1aIfinancial/company_price_feed/entity/v1/company_price_feed_entity_v1.proto\x1aIfinancial/company_price_feed/entity/v2/company_price_feed_entity_v2.proto\x1a3financial/emitten/entity/v2/emitten_entity_v2.proto\x1a;financial/order_trade/entity/v1/order_trade_entity_v1.proto\x1aMsecurities/transactional/datafeed/consumer/entity/v1/consumer_entity_v1.proto\x1aMsecurities/transactional/datafeed/consumer/entity/v3/consumer_entity_v3.proto\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"-\n" +
	"\x03Bid\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x10\n" +
	"\x03lot\x18\x02 \x01(\x01R\x03lot\"/\n" +
	"\x05Offer\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x10\n" +
	"\x03lot\x18\x02 \x01(\x01R\x03lot\">\n" +
	"\x06Change\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x01R\n" +
	"percentage\"f\n" +
	"\x05Error\x12C\n" +
	"\x04code\x18\x01 \x01(\x0e2/.securities.transactional.datafeed.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8e\x04\n" +
	"\fRunningTrade\x12A\n" +
	"\x0ewebsocket_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\rwebsocketTime\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\tR\x05stock\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\x01R\x06volume\x12G\n" +
	"\x06action\x18\x05 \x01(\x0e2/.securities.transactional.datafeed.v1.TradeTypeR\x06action\x12\x1b\n" +
	"\tis_global\x18\x06 \x01(\bR\bisGlobal\x12.\n" +
	"\x04time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12D\n" +
	"\x06change\x18\b \x01(\v2,.securities.transactional.datafeed.v1.ChangeR\x06change\x12!\n" +
	"\ftrade_number\x18\t \x01(\x05R\vtradeNumber\x12b\n" +
	"\fmarket_board\x18\n" +
	" \x01(\x0e2?.securities.transactional.datafeed.consumer.entity.v1.BoardTypeR\vmarketBoard\x12\x14\n" +
	"\x05value\x18\v \x01(\x01R\x05value\"]\n" +
	"\x11RunningTradeBatch\x12H\n" +
	"\x05batch\x18\x01 \x03(\v22.securities.transactional.datafeed.v1.RunningTradeR\x05batch\"\xec\x02\n" +
	"\aHotlist\x12!\n" +
	"\fstock_symbol\x18\x01 \x01(\tR\vstockSymbol\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\x01R\tlastPrice\x12D\n" +
	"\x06change\x18\x03 \x01(\v2,.securities.transactional.datafeed.v1.ChangeR\x06change\x12\x10\n" +
	"\x03uma\x18\x04 \x01(\bR\x03uma\x12H\n" +
	"\vcorp_action\x18\x05 \x01(\v2'.financial.emitten.entity.v2.CorpActionR\n" +
	"corpAction\x12C\n" +
	"\tnotations\x18\x06 \x03(\v2%.financial.emitten.entity.v2.NotationR\tnotations\x12\x1d\n" +
	"\n" +
	"stock_name\x18\a \x01(\tR\tstockName\x12\x19\n" +
	"\bicon_url\x18\b \x01(\tR\aiconUrl\"\xc5\x01\n" +
	"\x05Top20\x12G\n" +
	"\ahotlist\x18\x01 \x03(\v2-.securities.transactional.datafeed.v1.HotlistR\ahotlist\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12C\n" +
	"\x04type\x18\x03 \x01(\x0e2/.securities.transactional.datafeed.v1.Top20TypeR\x04type\"\x93\x01\n" +
	"\tWatchlist\x12!\n" +
	"\fstock_symbol\x18\x01 \x01(\tR\vstockSymbol\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\x01R\tlastPrice\x12D\n" +
	"\x06change\x18\x03 \x01(\v2,.securities.transactional.datafeed.v1.ChangeR\x06change\"\xed\x01\n" +
	"\x0fOrderBookHeader\x12!\n" +
	"\fstock_symbol\x18\x01 \x01(\tR\vstockSymbol\x12D\n" +
	"\x06change\x18\x02 \x01(\v2,.securities.transactional.datafeed.v1.ChangeR\x06change\x12A\n" +
	"\x05price\x18\x03 \x01(\v2+.securities.transactional.datafeed.v1.PriceR\x05price\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\xe2\x01\n" +
	"\rOrderBookBody\x12!\n" +
	"\fstock_symbol\x18\x01 \x01(\tR\vstockSymbol\x12;\n" +
	"\x03bid\x18\x02 \x03(\v2).securities.transactional.datafeed.v1.BidR\x03bid\x12A\n" +
	"\x05offer\x18\x03 \x03(\v2+.securities.transactional.datafeed.v1.OfferR\x05offer\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\xe7\x01\n" +
	"\x05Price\x12\x12\n" +
	"\x04open\x18\x01 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x03 \x01(\x01R\x03low\x12\x10\n" +
	"\x03avg\x18\x04 \x01(\x01R\x03avg\x12\x12\n" +
	"\x04last\x18\x05 \x01(\x01R\x04last\x12\x12\n" +
	"\x04prev\x18\x06 \x01(\x01R\x04prev\x12\x1c\n" +
	"\tfrequency\x18\a \x01(\x01R\tfrequency\x12\x12\n" +
	"\x04fbuy\x18\b \x01(\x01R\x04fbuy\x12\x14\n" +
	"\x05fsell\x18\t \x01(\x01R\x05fsell\x12\x10\n" +
	"\x03lot\x18\n" +
	" \x01(\x01R\x03lot\x12\x10\n" +
	"\x03val\x18\v \x01(\x01R\x03val\"\xf9\x01\n" +
	"\x10WebsocketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12P\n" +
	"\achannel\x18\x02 \x01(\v26.securities.transactional.datafeed.v1.WebsocketChannelR\achannel\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12E\n" +
	"\x04ping\x18\x04 \x01(\v21.securities.transactional.datafeed.v1.PingRequestR\x04ping\x12!\n" +
	"\faccess_token\x18\x05 \x01(\tR\vaccessToken\"\xbc\x05\n" +
	"\x10WebsocketChannel\x12\x1c\n" +
	"\twatchlist\x18\x01 \x03(\tR\twatchlist\x12\x1d\n" +
	"\n" +
	"order_book\x18\x02 \x03(\tR\torderBook\x12#\n" +
	"\rrunning_trade\x18\x03 \x03(\tR\frunningTrade\x12\x1d\n" +
	"\n" +
	"is_hotlist\x18\x04 \x01(\bR\tisHotlist\x12.\n" +
	"\x13running_trade_batch\x18\x05 \x03(\tR\x11runningTradeBatch\x12\x1c\n" +
	"\tliveprice\x18\x06 \x03(\tR\tliveprice\x12\x16\n" +
	"\x06iepiev\x18\a \x03(\tR\x06iepiev\x12\x1a\n" +
	"\bintraday\x18\b \x03(\tR\bintraday\x12$\n" +
	"\x0ebest_bid_offer\x18\t \x03(\tR\fbestBidOffer\x12_\n" +
	"\fmarket_mover\x18\n" +
	" \x03(\v2<.financial.order_trade.entity.v1.MarketMoverWebsocketRequestR\vmarketMover\x12\\\n" +
	"\vorder_queue\x18\v \x03(\v2;.financial.order_trade.entity.v1.OrderQueueWebsocketRequestR\n" +
	"orderQueue\x12!\n" +
	"\fliveprice_v3\x18\f \x03(\tR\vlivepriceV3\x12\"\n" +
	"\rorder_book_v3\x18\r \x03(\tR\vorderBookV3\x12\x1f\n" +
	"\vintraday_v3\x18\x0e \x03(\tR\n" +
	"intradayV3\x12X\n" +
	"\ttradebook\x18\x0f \x03(\v2:.financial.order_trade.entity.v1.TradebookWebsocketRequestR\ttradebook\"\xe7\r\n" +
	"\x1bWebsocketWrapMessageChannel\x12Y\n" +
	"\rrunning_trade\x18\x01 \x01(\v22.securities.transactional.datafeed.v1.RunningTradeH\x00R\frunningTrade\x12H\n" +
	"\x04ping\x18\x02 \x01(\v22.securities.transactional.datafeed.v1.PingResponseH\x00R\x04ping\x12C\n" +
	"\x05top20\x18\x03 \x01(\v2+.securities.transactional.datafeed.v1.Top20H\x00R\x05top20\x12O\n" +
	"\twatchlist\x18\x04 \x01(\v2/.securities.transactional.datafeed.v1.WatchlistH\x00R\twatchlist\x12b\n" +
	"\x10orderbook_header\x18\x05 \x01(\v25.securities.transactional.datafeed.v1.OrderBookHeaderH\x00R\x0forderbookHeader\x12\\\n" +
	"\x0eorderbook_body\x18\x06 \x01(\v23.securities.transactional.datafeed.v1.OrderBookBodyH\x00R\rorderbookBody\x12C\n" +
	"\x05error\x18\a \x01(\v2+.securities.transactional.datafeed.v1.ErrorH\x00R\x05error\x12i\n" +
	"\x13running_trade_batch\x18\b \x01(\v27.securities.transactional.datafeed.v1.RunningTradeBatchH\x00R\x11runningTradeBatch\x12_\n" +
	"\tliveprice\x18\t \x01(\v2?.securities.transactional.datafeed.consumer.entity.v1.LivePriceH\x00R\tliveprice\x12_\n" +
	"\torderbook\x18\n" +
	" \x01(\v2?.securities.transactional.datafeed.consumer.entity.v1.OrderbookH\x00R\torderbook\x12H\n" +
	"\x06iepiev\x18\v \x01(\v2..financial.company_price_feed.entity.v2.IEPIEVH\x00R\x06iepiev\x12\\\n" +
	"\bintraday\x18\f \x01(\v2>.securities.transactional.datafeed.consumer.entity.v1.IntradayH\x00R\bintraday\x12^\n" +
	"\x0ebest_bid_offer\x18\r \x01(\v26.financial.company_price_feed.entity.v1.BestBidOfferWSH\x00R\fbestBidOffer\x12a\n" +
	"\x12market_mover_batch\x18\x0e \x01(\v21.financial.order_trade.entity.v1.MarketMoverBatchH\x00R\x10marketMoverBatch\x12W\n" +
	"\vorder_queue\x18\x0f \x01(\v24.financial.order_trade.entity.v1.OrderQueueWebsocketH\x00R\n" +
	"orderQueue\x12d\n" +
	"\fliveprice_v3\x18\x10 \x01(\v2?.securities.transactional.datafeed.consumer.entity.v3.LivePriceH\x00R\vlivepriceV3\x12d\n" +
	"\forderbook_v3\x18\x11 \x01(\v2?.securities.transactional.datafeed.consumer.entity.v3.OrderbookH\x00R\vorderbookV3\x12a\n" +
	"\vintraday_v3\x18\x12 \x01(\v2>.securities.transactional.datafeed.consumer.entity.v3.IntradayH\x00R\n" +
	"intradayV3\x12S\n" +
	"\ttradebook\x18\x13 \x01(\v23.financial.order_trade.entity.v1.TradebookWSMessageH\x00R\ttradebookB\x11\n" +
	"\x0fmessage_channel*\x8d\x01\n" +
	"\tTop20Type\x12\x1a\n" +
	"\x16TOP20_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TOP20_TYPE_FREQUENCY_RG\x10\x02\x12#\n" +
	"\x1fTOP20_TYPE_PERCENTAGE_GAINER_RG\x10\x05\x12\"\n" +
	"\x1eTOP20_TYPE_PERCENTAGE_LOSER_RG\x10\x06*b\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x16ERROR_CODE_BAD_REQUEST\x10\x90\x03\x12\x1c\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x91\x03*P\n" +
	"\tTradeType\x12\x1a\n" +
	"\x16TRADE_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTRADE_TYPE_BUY\x10\x01\x12\x13\n" +
	"\x0fTRADE_TYPE_SELL\x10\x02ByZwgithub.com/nofendian17/sbterm-server/internal/infrastructure/stockbit/proto/securities/transactional/datafeed/v1;datav1b\x06proto3"

var (
	file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescOnce sync.Once
	file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescData []byte
)

func file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescGZIP() []byte {
	file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescOnce.Do(func() {
		file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDesc), len(file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDesc)))
	})
	return file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDescData
}

var file_securities_transactional_datafeed_v1_datafeed_websocket_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_securities_transactional_datafeed_v1_datafeed_websocket_proto_goTypes = []any{
	(Top20Type)(0),                          // 0: securities.transactional.datafeed.v1.Top20Type
	(ErrorCode)(0),                          // 1: securities.transactional.datafeed.v1.ErrorCode
	(TradeType)(0),                          // 2: securities.transactional.datafeed.v1.TradeType
	(*PingRequest)(nil),                     // 3: securities.transactional.datafeed.v1.PingRequest
	(*PingResponse)(nil),                    // 4: securities.transactional.datafeed.v1.PingResponse
	(*Bid)(nil),                             // 5: securities.transactional.datafeed.v1.Bid
	(*Offer)(nil),                           // 6: securities.transactional.datafeed.v1.Offer
	(*Change)(nil),                          // 7: securities.transactional.datafeed.v1.Change
	(*Error)(nil),                           // 8: securities.transactional.datafeed.v1.Error
	(*RunningTrade)(nil),                    // 9: securities.transactional.datafeed.v1.RunningTrade
	(*RunningTradeBatch)(nil),               // 10: securities.transactional.datafeed.v1.RunningTradeBatch
	(*Hotlist)(nil),                         // 11: securities.transactional.datafeed.v1.Hotlist
	(*Top20)(nil),                           // 12: securities.transactional.datafeed.v1.Top20
	(*Watchlist)(nil),                       // 13: securities.transactional.datafeed.v1.Watchlist
	(*OrderBookHeader)(nil),                 // 14: securities.transactional.datafeed.v1.OrderBookHeader
	(*OrderBookBody)(nil),                   // 15: securities.transactional.datafeed.v1.OrderBookBody
	(*Price)(nil),                           // 16: securities.transactional.datafeed.v1.Price
	(*WebsocketRequest)(nil),                // 17: securities.transactional.datafeed.v1.WebsocketRequest
	(*WebsocketChannel)(nil),                // 18: securities.transactional.datafeed.v1.WebsocketChannel
	(*WebsocketWrapMessageChannel)(nil),     // 19: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel
	(*timestamppb.Timestamp)(nil),           // 20: google.protobuf.Timestamp
	(v1.BoardType)(0),                       // 21: securities.transactional.datafeed.consumer.entity.v1.BoardType
	(*v2.CorpAction)(nil),                   // 22: financial.emitten.entity.v2.CorpAction
	(*v2.Notation)(nil),                     // 23: financial.emitten.entity.v2.Notation
	(*v11.MarketMoverWebsocketRequest)(nil), // 24: financial.order_trade.entity.v1.MarketMoverWebsocketRequest
	(*v11.OrderQueueWebsocketRequest)(nil),  // 25: financial.order_trade.entity.v1.OrderQueueWebsocketRequest
	(*v11.TradebookWebsocketRequest)(nil),   // 26: financial.order_trade.entity.v1.TradebookWebsocketRequest
	(*v1.LivePrice)(nil),                    // 27: securities.transactional.datafeed.consumer.entity.v1.LivePrice
	(*v1.Orderbook)(nil),                    // 28: securities.transactional.datafeed.consumer.entity.v1.Orderbook
	(*v21.IEPIEV)(nil),                      // 29: financial.company_price_feed.entity.v2.IEPIEV
	(*v1.Intraday)(nil),                     // 30: securities.transactional.datafeed.consumer.entity.v1.Intraday
	(*v12.BestBidOfferWS)(nil),              // 31: financial.company_price_feed.entity.v1.BestBidOfferWS
	(*v11.MarketMoverBatch)(nil),            // 32: financial.order_trade.entity.v1.MarketMoverBatch
	(*v11.OrderQueueWebsocket)(nil),         // 33: financial.order_trade.entity.v1.OrderQueueWebsocket
	(*v3.LivePrice)(nil),                    // 34: securities.transactional.datafeed.consumer.entity.v3.LivePrice
	(*v3.Orderbook)(nil),                    // 35: securities.transactional.datafeed.consumer.entity.v3.Orderbook
	(*v3.Intraday)(nil),                     // 36: securities.transactional.datafeed.consumer.entity.v3.Intraday
	(*v11.TradebookWSMessage)(nil),          // 37: financial.order_trade.entity.v1.TradebookWSMessage
}
var file_securities_transactional_datafeed_v1_datafeed_websocket_proto_depIdxs = []int32{
	1,  // 0: securities.transactional.datafeed.v1.Error.code:type_name -> securities.transactional.datafeed.v1.ErrorCode
	20, // 1: securities.transactional.datafeed.v1.RunningTrade.websocket_time:type_name -> google.protobuf.Timestamp
	2,  // 2: securities.transactional.datafeed.v1.RunningTrade.action:type_name -> securities.transactional.datafeed.v1.TradeType
	20, // 3: securities.transactional.datafeed.v1.RunningTrade.time:type_name -> google.protobuf.Timestamp
	7,  // 4: securities.transactional.datafeed.v1.RunningTrade.change:type_name -> securities.transactional.datafeed.v1.Change
	21, // 5: securities.transactional.datafeed.v1.RunningTrade.market_board:type_name -> securities.transactional.datafeed.consumer.entity.v1.BoardType
	9,  // 6: securities.transactional.datafeed.v1.RunningTradeBatch.batch:type_name -> securities.transactional.datafeed.v1.RunningTrade
	7,  // 7: securities.transactional.datafeed.v1.Hotlist.change:type_name -> securities.transactional.datafeed.v1.Change
	22, // 8: securities.transactional.datafeed.v1.Hotlist.corp_action:type_name -> financial.emitten.entity.v2.CorpAction
	23, // 9: securities.transactional.datafeed.v1.Hotlist.notations:type_name -> financial.emitten.entity.v2.Notation
	11, // 10: securities.transactional.datafeed.v1.Top20.hotlist:type_name -> securities.transactional.datafeed.v1.Hotlist
	20, // 11: securities.transactional.datafeed.v1.Top20.time:type_name -> google.protobuf.Timestamp
	0,  // 12: securities.transactional.datafeed.v1.Top20.type:type_name -> securities.transactional.datafeed.v1.Top20Type
	7,  // 13: securities.transactional.datafeed.v1.Watchlist.change:type_name -> securities.transactional.datafeed.v1.Change
	7,  // 14: securities.transactional.datafeed.v1.OrderBookHeader.change:type_name -> securities.transactional.datafeed.v1.Change
	16, // 15: securities.transactional.datafeed.v1.OrderBookHeader.price:type_name -> securities.transactional.datafeed.v1.Price
	20, // 16: securities.transactional.datafeed.v1.OrderBookHeader.time:type_name -> google.protobuf.Timestamp
	5,  // 17: securities.transactional.datafeed.v1.OrderBookBody.bid:type_name -> securities.transactional.datafeed.v1.Bid
	6,  // 18: securities.transactional.datafeed.v1.OrderBookBody.offer:type_name -> securities.transactional.datafeed.v1.Offer
	20, // 19: securities.transactional.datafeed.v1.OrderBookBody.time:type_name -> google.protobuf.Timestamp
	18, // 20: securities.transactional.datafeed.v1.WebsocketRequest.channel:type_name -> securities.transactional.datafeed.v1.WebsocketChannel
	3,  // 21: securities.transactional.datafeed.v1.WebsocketRequest.ping:type_name -> securities.transactional.datafeed.v1.PingRequest
	24, // 22: securities.transactional.datafeed.v1.WebsocketChannel.market_mover:type_name -> financial.order_trade.entity.v1.MarketMoverWebsocketRequest
	25, // 23: securities.transactional.datafeed.v1.WebsocketChannel.order_queue:type_name -> financial.order_trade.entity.v1.OrderQueueWebsocketRequest
	26, // 24: securities.transactional.datafeed.v1.WebsocketChannel.tradebook:type_name -> financial.order_trade.entity.v1.TradebookWebsocketRequest
	9,  // 25: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.running_trade:type_name -> securities.transactional.datafeed.v1.RunningTrade
	4,  // 26: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.ping:type_name -> securities.transactional.datafeed.v1.PingResponse
	12, // 27: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.top20:type_name -> securities.transactional.datafeed.v1.Top20
	13, // 28: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.watchlist:type_name -> securities.transactional.datafeed.v1.Watchlist
	14, // 29: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.orderbook_header:type_name -> securities.transactional.datafeed.v1.OrderBookHeader
	15, // 30: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.orderbook_body:type_name -> securities.transactional.datafeed.v1.OrderBookBody
	8,  // 31: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.error:type_name -> securities.transactional.datafeed.v1.Error
	10, // 32: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.running_trade_batch:type_name -> securities.transactional.datafeed.v1.RunningTradeBatch
	27, // 33: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.liveprice:type_name -> securities.transactional.datafeed.consumer.entity.v1.LivePrice
	28, // 34: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.orderbook:type_name -> securities.transactional.datafeed.consumer.entity.v1.Orderbook
	29, // 35: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.iepiev:type_name -> financial.company_price_feed.entity.v2.IEPIEV
	30, // 36: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.intraday:type_name -> securities.transactional.datafeed.consumer.entity.v1.Intraday
	31, // 37: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.best_bid_offer:type_name -> financial.company_price_feed.entity.v1.BestBidOfferWS
	32, // 38: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.market_mover_batch:type_name -> financial.order_trade.entity.v1.MarketMoverBatch
	33, // 39: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.order_queue:type_name -> financial.order_trade.entity.v1.OrderQueueWebsocket
	34, // 40: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.liveprice_v3:type_name -> securities.transactional.datafeed.consumer.entity.v3.LivePrice
	35, // 41: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.orderbook_v3:type_name -> securities.transactional.datafeed.consumer.entity.v3.Orderbook
	36, // 42: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.intraday_v3:type_name -> securities.transactional.datafeed.consumer.entity.v3.Intraday
	37, // 43: securities.transactional.datafeed.v1.WebsocketWrapMessageChannel.tradebook:type_name -> financial.order_trade.entity.v1.TradebookWSMessage
	44, // [44:44] is the sub-list for method output_type
	44, // [44:44] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_securities_transactional_datafeed_v1_datafeed_websocket_proto_init() }
func file_securities_transactional_datafeed_v1_datafeed_websocket_proto_init() {
	if File_securities_transactional_datafeed_v1_datafeed_websocket_proto != nil {
		return
	}
	file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes[16].OneofWrappers = []any{
		(*WebsocketWrapMessageChannel_RunningTrade)(nil),
		(*WebsocketWrapMessageChannel_Ping)(nil),
		(*WebsocketWrapMessageChannel_Top20)(nil),
		(*WebsocketWrapMessageChannel_Watchlist)(nil),
		(*WebsocketWrapMessageChannel_OrderbookHeader)(nil),
		(*WebsocketWrapMessageChannel_OrderbookBody)(nil),
		(*WebsocketWrapMessageChannel_Error)(nil),
		(*WebsocketWrapMessageChannel_RunningTradeBatch)(nil),
		(*WebsocketWrapMessageChannel_Liveprice)(nil),
		(*WebsocketWrapMessageChannel_Orderbook)(nil),
		(*WebsocketWrapMessageChannel_Iepiev)(nil),
		(*WebsocketWrapMessageChannel_Intraday)(nil),
		(*WebsocketWrapMessageChannel_BestBidOffer)(nil),
		(*WebsocketWrapMessageChannel_MarketMoverBatch)(nil),
		(*WebsocketWrapMessageChannel_OrderQueue)(nil),
		(*WebsocketWrapMessageChannel_LivepriceV3)(nil),
		(*WebsocketWrapMessageChannel_OrderbookV3)(nil),
		(*WebsocketWrapMessageChannel_IntradayV3)(nil),
		(*WebsocketWrapMessageChannel_Tradebook)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDesc), len(file_securities_transactional_datafeed_v1_datafeed_websocket_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_securities_transactional_datafeed_v1_datafeed_websocket_proto_goTypes,
		DependencyIndexes: file_securities_transactional_datafeed_v1_datafeed_websocket_proto_depIdxs,
		EnumInfos:         file_securities_transactional_datafeed_v1_datafeed_websocket_proto_enumTypes,
		MessageInfos:      file_securities_transactional_datafeed_v1_datafeed_websocket_proto_msgTypes,
	}.Build()
	File_securities_transactional_datafeed_v1_datafeed_websocket_proto = out.File
	file_securities_transactional_datafeed_v1_datafeed_websocket_proto_goTypes = nil
	file_securities_transactional_datafeed_v1_datafeed_websocket_proto_depIdxs = nil
}
