// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: google/type/money.proto

// Stub lokal — rekonstruksi dari stockbit.com webpack bundle (module 76557).
// Wire format identik dengan google.type.Money.

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  string                 `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Units         int64                  `protobuf:"varint,2,opt,name=units,proto3" json:"units,omitempty"`
	Nanos         int32                  `protobuf:"varint,3,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_google_type_money_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_google_type_money_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_google_type_money_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Money) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Money) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

var File_google_type_money_proto protoreflect.FileDescriptor

const file_google_type_money_proto_rawDesc = "" +
	"\n" +
	"\x17google/type/money.proto\x12\vgoogle.type\"X\n" +
	"\x05Money\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12\x14\n" +
	"\x05units\x18\x02 \x01(\x03R\x05units\x12\x14\n" +
	"\x05nanos\x18\x03 \x01(\x05R\x05nanosB_Z]github.com/nofendian17/sbterm-server/internal/infrastructure/stockbit/proto/google/type;typesb\x06proto3"

var (
	file_google_type_money_proto_rawDescOnce sync.Once
	file_google_type_money_proto_rawDescData []byte
)

func file_google_type_money_proto_rawDescGZIP() []byte {
	file_google_type_money_proto_rawDescOnce.Do(func() {
		file_google_type_money_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_type_money_proto_rawDesc), len(file_google_type_money_proto_rawDesc)))
	})
	return file_google_type_money_proto_rawDescData
}

var file_google_type_money_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_type_money_proto_goTypes = []any{
	(*Money)(nil), // 0: google.type.Money
}
var file_google_type_money_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_type_money_proto_init() }
func file_google_type_money_proto_init() {
	if File_google_type_money_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_type_money_proto_rawDesc), len(file_google_type_money_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_type_money_proto_goTypes,
		DependencyIndexes: file_google_type_money_proto_depIdxs,
		MessageInfos:      file_google_type_money_proto_msgTypes,
	}.Build()
	File_google_type_money_proto = out.File
	file_google_type_money_proto_goTypes = nil
	file_google_type_money_proto_depIdxs = nil
}
