// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: social/stream/entity/v1/stream_entity_v1.proto

// Reconstructed from stockbit.com webpack bundle (chunk 56256....js,
// module 45621) — protobuf-es message definitions. NOT an official schema.
// Entitas stream social — koneksi wss://wssocial.stockbit.com/?wskey=<key>.

package streamentityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareTradeInfo_OrderType int32

const (
	ShareTradeInfo_ORDER_TYPE_UNSPECIFIED ShareTradeInfo_OrderType = 0
	ShareTradeInfo_ORDER_TYPE_BUY         ShareTradeInfo_OrderType = 1
	ShareTradeInfo_ORDER_TYPE_SELL        ShareTradeInfo_OrderType = 2
)

// Enum value maps for ShareTradeInfo_OrderType.
var (
	ShareTradeInfo_OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_BUY",
		2: "ORDER_TYPE_SELL",
	}
	ShareTradeInfo_OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_BUY":         1,
		"ORDER_TYPE_SELL":        2,
	}
)

func (x ShareTradeInfo_OrderType) Enum() *ShareTradeInfo_OrderType {
	p := new(ShareTradeInfo_OrderType)
	*p = x
	return p
}

func (x ShareTradeInfo_OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShareTradeInfo_OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_social_stream_entity_v1_stream_entity_v1_proto_enumTypes[0].Descriptor()
}

func (ShareTradeInfo_OrderType) Type() protoreflect.EnumType {
	return &file_social_stream_entity_v1_stream_entity_v1_proto_enumTypes[0]
}

func (x ShareTradeInfo_OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShareTradeInfo_OrderType.Descriptor instead.
func (ShareTradeInfo_OrderType) EnumDescriptor() ([]byte, []int) {
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP(), []int{3, 0}
}

type ShareTradeInfo_PNL_Type int32

const (
	ShareTradeInfo_PNL_TYPE_UNSPECIFIED ShareTradeInfo_PNL_Type = 0
	ShareTradeInfo_PNL_TYPE_GAIN        ShareTradeInfo_PNL_Type = 1
	ShareTradeInfo_PNL_TYPE_LOSS        ShareTradeInfo_PNL_Type = 2
)

// Enum value maps for ShareTradeInfo_PNL_Type.
var (
	ShareTradeInfo_PNL_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_GAIN",
		2: "TYPE_LOSS",
	}
	ShareTradeInfo_PNL_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_GAIN":        1,
		"TYPE_LOSS":        2,
	}
)

func (x ShareTradeInfo_PNL_Type) Enum() *ShareTradeInfo_PNL_Type {
	p := new(ShareTradeInfo_PNL_Type)
	*p = x
	return p
}

func (x ShareTradeInfo_PNL_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShareTradeInfo_PNL_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_social_stream_entity_v1_stream_entity_v1_proto_enumTypes[1].Descriptor()
}

func (ShareTradeInfo_PNL_Type) Type() protoreflect.EnumType {
	return &file_social_stream_entity_v1_stream_entity_v1_proto_enumTypes[1]
}

func (x ShareTradeInfo_PNL_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShareTradeInfo_PNL_Type.Descriptor instead.
func (ShareTradeInfo_PNL_Type) EnumDescriptor() ([]byte, []int) {
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP(), []int{3, 0, 0}
}

type Insider_Type int32

const (
	Insider_TYPE_UNSPECIFIED Insider_Type = 0
	Insider_TYPE_LOCAL       Insider_Type = 1
	Insider_TYPE_FOREIGN     Insider_Type = 2
)

// Enum value maps for Insider_Type.
var (
	Insider_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_LOCAL",
		2: "TYPE_FOREIGN",
	}
	Insider_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_LOCAL":       1,
		"TYPE_FOREIGN":     2,
	}
)

func (x Insider_Type) Enum() *Insider_Type {
	p := new(Insider_Type)
	*p = x
	return p
}

func (x Insider_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Insider_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_social_stream_entity_v1_stream_entity_v1_proto_enumTypes[2].Descriptor()
}

func (Insider_Type) Type() protoreflect.EnumType {
	return &file_social_stream_entity_v1_stream_entity_v1_proto_enumTypes[2]
}

func (x Insider_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Insider_Type.Descriptor instead.
func (Insider_Type) EnumDescriptor() ([]byte, []int) {
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP(), []int{4, 0}
}

type Insider_Action int32

const (
	Insider_ACTION_UNSPECIFIED Insider_Action = 0
	Insider_ACTION_BOUGHT      Insider_Action = 1
	Insider_ACTION_SOLD        Insider_Action = 2
)

// Enum value maps for Insider_Action.
var (
	Insider_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_BOUGHT",
		2: "ACTION_SOLD",
	}
	Insider_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_BOUGHT":      1,
		"ACTION_SOLD":        2,
	}
)

func (x Insider_Action) Enum() *Insider_Action {
	p := new(Insider_Action)
	*p = x
	return p
}

func (x Insider_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Insider_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_social_stream_entity_v1_stream_entity_v1_proto_enumTypes[3].Descriptor()
}

func (Insider_Action) Type() protoreflect.EnumType {
	return &file_social_stream_entity_v1_stream_entity_v1_proto_enumTypes[3]
}

func (x Insider_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Insider_Action.Descriptor instead.
func (Insider_Action) EnumDescriptor() ([]byte, []int) {
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP(), []int{4, 1}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            // T:5
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"` // T:9
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`   // T:9
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`     // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type ReplyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyInfo) Reset() {
	*x = ReplyInfo{}
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyInfo) ProtoMessage() {}

func (x *ReplyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyInfo.ProtoReflect.Descriptor instead.
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyInfo) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type FollowingActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Info          string                 `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"` // T:9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowingActivity) Reset() {
	*x = FollowingActivity{}
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowingActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowingActivity) ProtoMessage() {}

func (x *FollowingActivity) ProtoReflect() protoreflect.Message {
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowingActivity.ProtoReflect.Descriptor instead.
func (*FollowingActivity) Descriptor() ([]byte, []int) {
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP(), []int{2}
}

func (x *FollowingActivity) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *FollowingActivity) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type ShareTradeInfo struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Text          string                   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`     // T:9
	Symbol        string                   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"` // T:9
	OrderType     ShareTradeInfo_OrderType `protobuf:"varint,3,opt,name=order_type,json=orderType,proto3,enum=social.stream.entity.v1.ShareTradeInfo_OrderType" json:"order_type,omitempty"`
	Price         string                   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"` // T:9
	Pnl           *ShareTradeInfo_PNL      `protobuf:"bytes,5,opt,name=pnl,proto3" json:"pnl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareTradeInfo) Reset() {
	*x = ShareTradeInfo{}
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareTradeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareTradeInfo) ProtoMessage() {}

func (x *ShareTradeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareTradeInfo.ProtoReflect.Descriptor instead.
func (*ShareTradeInfo) Descriptor() ([]byte, []int) {
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP(), []int{3}
}

func (x *ShareTradeInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ShareTradeInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ShareTradeInfo) GetOrderType() ShareTradeInfo_OrderType {
	if x != nil {
		return x.OrderType
	}
	return ShareTradeInfo_ORDER_TYPE_UNSPECIFIED
}

func (x *ShareTradeInfo) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ShareTradeInfo) GetPnl() *ShareTradeInfo_PNL {
	if x != nil {
		return x.Pnl
	}
	return nil
}

// Tidak direferensikan oleh field mana pun di graph mencapai (unreachable),
// disertakan untuk kelengkapan modul.
type Insider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Insider) Reset() {
	*x = Insider{}
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Insider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insider) ProtoMessage() {}

func (x *Insider) ProtoReflect() protoreflect.Message {
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insider.ProtoReflect.Descriptor instead.
func (*Insider) Descriptor() ([]byte, []int) {
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP(), []int{4}
}

type ShareTradeInfo_PNL struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Percentage    string                  `protobuf:"bytes,1,opt,name=percentage,proto3" json:"percentage,omitempty"` // T:9
	Type          ShareTradeInfo_PNL_Type `protobuf:"varint,2,opt,name=type,proto3,enum=social.stream.entity.v1.ShareTradeInfo_PNL_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareTradeInfo_PNL) Reset() {
	*x = ShareTradeInfo_PNL{}
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareTradeInfo_PNL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareTradeInfo_PNL) ProtoMessage() {}

func (x *ShareTradeInfo_PNL) ProtoReflect() protoreflect.Message {
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareTradeInfo_PNL.ProtoReflect.Descriptor instead.
func (*ShareTradeInfo_PNL) Descriptor() ([]byte, []int) {
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ShareTradeInfo_PNL) GetPercentage() string {
	if x != nil {
		return x.Percentage
	}
	return ""
}

func (x *ShareTradeInfo_PNL) GetType() ShareTradeInfo_PNL_Type {
	if x != nil {
		return x.Type
	}
	return ShareTradeInfo_PNL_TYPE_UNSPECIFIED
}

type Insider_Shareholder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // T:9
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`    // T:5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Insider_Shareholder) Reset() {
	*x = Insider_Shareholder{}
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Insider_Shareholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insider_Shareholder) ProtoMessage() {}

func (x *Insider_Shareholder) ProtoReflect() protoreflect.Message {
	mi := &file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insider_Shareholder.ProtoReflect.Descriptor instead.
func (*Insider_Shareholder) Descriptor() ([]byte, []int) {
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Insider_Shareholder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Insider_Shareholder) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_social_stream_entity_v1_stream_entity_v1_proto protoreflect.FileDescriptor

const file_social_stream_entity_v1_stream_entity_v1_proto_rawDesc = "" +
	"\n" +
	".social/stream/entity/v1/stream_entity_v1.proto\x12\x17social.stream.entity.v1\"d\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\">\n" +
	"\tReplyInfo\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.social.stream.entity.v1.UserR\x04user\"\\\n" +
	"\x11FollowingActivity\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.social.stream.entity.v1.UserR\x05users\x12\x12\n" +
	"\x04info\x18\x02 \x01(\tR\x04info\"\xdf\x03\n" +
	"\x0eShareTradeInfo\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12P\n" +
	"\n" +
	"order_type\x18\x03 \x01(\x0e21.social.stream.entity.v1.ShareTradeInfo.OrderTypeR\torderType\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12=\n" +
	"\x03pnl\x18\x05 \x01(\v2+.social.stream.entity.v1.ShareTradeInfo.PNLR\x03pnl\x1a\xa7\x01\n" +
	"\x03PNL\x12\x1e\n" +
	"\n" +
	"percentage\x18\x01 \x01(\tR\n" +
	"percentage\x12D\n" +
	"\x04type\x18\x02 \x01(\x0e20.social.stream.entity.v1.ShareTradeInfo.PNL.TypeR\x04type\":\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_GAIN\x10\x01\x12\r\n" +
	"\tTYPE_LOSS\x10\x02\"P\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_TYPE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_TYPE_SELL\x10\x02\"\xc2\x01\n" +
	"\aInsider\x1a1\n" +
	"\vShareholder\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\">\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_LOCAL\x10\x01\x12\x10\n" +
	"\fTYPE_FOREIGN\x10\x02\"D\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_BOUGHT\x10\x01\x12\x0f\n" +
	"\vACTION_SOLD\x10\x02BtZrgithub.com/nofendian17/sbterm-server/internal/infrastructure/stockbit/proto/social/stream/entity/v1;streamentityv1b\x06proto3"

var (
	file_social_stream_entity_v1_stream_entity_v1_proto_rawDescOnce sync.Once
	file_social_stream_entity_v1_stream_entity_v1_proto_rawDescData []byte
)

func file_social_stream_entity_v1_stream_entity_v1_proto_rawDescGZIP() []byte {
	file_social_stream_entity_v1_stream_entity_v1_proto_rawDescOnce.Do(func() {
		file_social_stream_entity_v1_stream_entity_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_stream_entity_v1_stream_entity_v1_proto_rawDesc), len(file_social_stream_entity_v1_stream_entity_v1_proto_rawDesc)))
	})
	return file_social_stream_entity_v1_stream_entity_v1_proto_rawDescData
}

var file_social_stream_entity_v1_stream_entity_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_social_stream_entity_v1_stream_entity_v1_proto_goTypes = []any{
	(ShareTradeInfo_OrderType)(0), // 0: social.stream.entity.v1.ShareTradeInfo.OrderType
	(ShareTradeInfo_PNL_Type)(0),  // 1: social.stream.entity.v1.ShareTradeInfo.PNL.Type
	(Insider_Type)(0),             // 2: social.stream.entity.v1.Insider.Type
	(Insider_Action)(0),           // 3: social.stream.entity.v1.Insider.Action
	(*User)(nil),                  // 4: social.stream.entity.v1.User
	(*ReplyInfo)(nil),             // 5: social.stream.entity.v1.ReplyInfo
	(*FollowingActivity)(nil),     // 6: social.stream.entity.v1.FollowingActivity
	(*ShareTradeInfo)(nil),        // 7: social.stream.entity.v1.ShareTradeInfo
	(*Insider)(nil),               // 8: social.stream.entity.v1.Insider
	(*ShareTradeInfo_PNL)(nil),    // 9: social.stream.entity.v1.ShareTradeInfo.PNL
	(*Insider_Shareholder)(nil),   // 10: social.stream.entity.v1.Insider.Shareholder
}
var file_social_stream_entity_v1_stream_entity_v1_proto_depIdxs = []int32{
	4, // 0: social.stream.entity.v1.ReplyInfo.user:type_name -> social.stream.entity.v1.User
	4, // 1: social.stream.entity.v1.FollowingActivity.users:type_name -> social.stream.entity.v1.User
	0, // 2: social.stream.entity.v1.ShareTradeInfo.order_type:type_name -> social.stream.entity.v1.ShareTradeInfo.OrderType
	9, // 3: social.stream.entity.v1.ShareTradeInfo.pnl:type_name -> social.stream.entity.v1.ShareTradeInfo.PNL
	1, // 4: social.stream.entity.v1.ShareTradeInfo.PNL.type:type_name -> social.stream.entity.v1.ShareTradeInfo.PNL.Type
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_social_stream_entity_v1_stream_entity_v1_proto_init() }
func file_social_stream_entity_v1_stream_entity_v1_proto_init() {
	if File_social_stream_entity_v1_stream_entity_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_stream_entity_v1_stream_entity_v1_proto_rawDesc), len(file_social_stream_entity_v1_stream_entity_v1_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_social_stream_entity_v1_stream_entity_v1_proto_goTypes,
		DependencyIndexes: file_social_stream_entity_v1_stream_entity_v1_proto_depIdxs,
		EnumInfos:         file_social_stream_entity_v1_stream_entity_v1_proto_enumTypes,
		MessageInfos:      file_social_stream_entity_v1_stream_entity_v1_proto_msgTypes,
	}.Build()
	File_social_stream_entity_v1_stream_entity_v1_proto = out.File
	file_social_stream_entity_v1_stream_entity_v1_proto_goTypes = nil
	file_social_stream_entity_v1_stream_entity_v1_proto_depIdxs = nil
}
